### ISSUE TITLE
Update plugins CI to deploy snapshots

### ISSUE THREAD

**Issue by msavy** [apiman/apiman#1002]
See https://github.com/apiman/apiman/blob/master/.github/workflows/verify.yaml

Might as well also add builds for Java 11 and 15 while at it.

**Comment by msavy** [comment]
Blocked by #1004

**Comment by piyush-1234** [comment]
hi @msavy , if you would not mind, i can take up this issue, and I can start work on this, 
whats you suggestion

**Comment by msavy** [comment]
You are most welcome to contribute! However, unfortunately, I've already completed this issue but apparently did not realise.

I'll find something else for you and get back to you this week :-).

**Comment by piyush-1234** [comment]
> 
yes @msavy , thanks for reply, I m glad to see the next issue, which you will give me,,
