### ISSUE TITLE
[Vertx] EsClientFactory use SystemOutLogger for logging

### ISSUE THREAD

**Issue by kfeofantov** [apiman/apiman#1094]
Hi! I'm faced with a problem with log writing while using vertx. Afterwards, I can't use log4j for managing logs.

Part of my log:
```
[INFO ] 2021-04-07 14:22:48.475 [vert.x-eventloop-thread-0] InitVerticle - Successfully deployed all verticles
[INFO ] 2021-04-07 14:22:48.475 [vert.x-eventloop-thread-0] InitVerticle - Gateway API port: 8,081
[INFO ] 2021-04-07 14:22:48.476 [vert.x-eventloop-thread-1] VertxIsolatedDeployer - Succeeded in deploying verticle
INFO: Demand elasticsearch client for elasticsearch:9200 over http for index prefix apiman
INFO: Demand elasticsearch client for elasticsearch:9200 over http for index prefix apiman
INFO: Polling for Elasticsearch...
```

I found that EsClientFactory use [SystemOutLogger](https://github.com/apiman/apiman/blob/3a5a341213dac2f45f6e53ecc047fadb3b048be3/common/logging/core/src/main/java/io/apiman/common/logging/impl/SystemOutLogger.java#L27). 
Are there any settings to solve this problem?

Version: 2.0.0.Final

**Comment by msavy** [comment]
I'm reworking logging and it will be in the next release. It will fix this
problem 🙂.

**Comment by msavy** [comment]
See https://github.com/apiman/apiman/pull/1057

Will be in next release 👍

**Comment by kfeofantov** [comment]
@msavy thanks!
