### ISSUE TITLE
Unable to Publish API

### ISSUE THREAD

**Issue by AghaSaad04** [apiman/apiman#1244]
We are unable to create an API in APIMan and getting the below mentioned error. Configuration is attached.

#### Implementation Tab:
![image](https://user-images.githubusercontent.com/36513474/119709252-6f709680-be76-11eb-9f7a-4cb08c5152e9.png)

#### Definition Tab:
![image](https://user-images.githubusercontent.com/36513474/119709332-84e5c080-be76-11eb-8bb9-cfb65ddb49a0.png)

#### Plans Tab:
![image](https://user-images.githubusercontent.com/36513474/119709403-9c24ae00-be76-11eb-964c-39d5c77e8844.png)

#### Plan and Policy:
![image](https://user-images.githubusercontent.com/36513474/119709548-c5453e80-be76-11eb-8e4a-560419f06780.png)

### Output while publishing
![image](https://user-images.githubusercontent.com/36513474/119709020-2ddfeb80-be76-11eb-882a-d47a3908e969.png)

**Comment by msavy** [comment]
Can you show what's in the Javascript develop console please?

**Comment by AghaSaad04** [comment]
@msavy. Thanks for the quick response. I have attached the screenshot.

![image](https://user-images.githubusercontent.com/36513474/119710267-98ddf200-be77-11eb-948a-e2237818ece8.png)

**Comment by msavy** [comment]
Strange. Can you look at the network tab and see what the response payload is for that erroneous response?

Does anything come out on the terminal for the Apiman Manager backend?

Is the Apiman Gateway reachable? Go to admin -> gateways -> test the credentials.

**Comment by AghaSaad04** [comment]
Network tab output:
![image](https://user-images.githubusercontent.com/36513474/119710815-40f3bb00-be78-11eb-9c9c-73cb08bf58c4.png)

Terminal Output:
![image](https://user-images.githubusercontent.com/36513474/119710941-641e6a80-be78-11eb-8e9e-8224729cd60e.png)

Network Gateway:
![image](https://user-images.githubusercontent.com/36513474/119711082-8d3efb00-be78-11eb-9dcb-5b6312b41d12.png)

**Comment by msavy** [comment]
Unfortunately it looks like someone changed the default password of the `apimanager` client in the Apiman Realm definition, but didn't change it in the UI.

Please change the password to `apimanager123!` and try it out (and 'update gateway' if that works).

You can change the client password yourself to whatever you like at `localhost:8080/auth` in Keycloak.

**Comment by AghaSaad04** [comment]
![image](https://user-images.githubusercontent.com/36513474/119714708-9d58d980-be7c-11eb-9aba-fce70ffeaced.png)

Can you help me where I have to navigate further to update the password?

**Comment by msavy** [comment]
Users section

**Comment by msavy** [comment]
Please reopen if you have further questions.

**Comment by AghaSaad04** [comment]
@msavy I tried updating password in Users section but didn't work. Then I tried updating the password in Gateways and worked like a charm. Thanks for your support. :)

**Comment by msavy** [comment]
That's great! We'll try to fix the issue for our quickstarts for the next release (coming soon, hopefully).

I think you were misunderstanding me slightly.

The password is controlled in the Keycloak config, and you can change it to anything you want.

You still need to change the password in the Apiman Gateways config page to whatever you set in Keycloak.

**Comment by AghaSaad04** [comment]
I also want to know if there is any guide/article that has steps to implement JWT policy? like from where I would get Signing key and what configurations and changes I have to do etc.

Right now I have the following user guide.
https://apiman.gitbooks.io/apiman-user-guide/content/user-guide/gateway/policies.html#_jwt_policy

**Comment by msavy** [comment]
Ignore the preparation section, as you already have the quickstart running evidently.
