### ISSUE TITLE
Invalid parameter: redirect_uri

### ISSUE THREAD

**Issue by AghaSaad04** [apiman/apiman#1278]
Hi, I have cloned the master branch and trying to setup APIMan and DevPortal on VM by exposing the port of VM and accessing it from the browser of my local machine using VM-IP:PORT. 

I have run the following commands so far:
`mvn clean install -Pinstall-all-wildfly -DskipTests`
`cd tools/server-all/target/wildfly-dev-server`
`./bin/standalone.sh`

After pointing to browser with VM-IP:Port/apimanui I am getting the following output:
![image](https://user-images.githubusercontent.com/36513474/121016429-8dfb5980-c7b5-11eb-9174-84a46b41d8b7.png)

Any leads will be helpful. Thanks

**Comment by volkflo** [comment]
In Keycloak for the clients 

- apiman
- apimanui
- apiman-gateway-api
- devportal

You have to enter the IP of your VM as an additional valid redirect URL like:
![image](https://user-images.githubusercontent.com/13332383/121021848-140da500-c7a2-11eb-9a6d-b0f2d7238c9c.png)

**Comment by AghaSaad04** [comment]
Hi @volkflo,
I tried accessing KeyCloak by **VM-IP:Port/auth** but getting the following response:

![image](https://user-images.githubusercontent.com/36513474/121023628-e550f800-c7bc-11eb-85b6-a5306aa4a324.png)

**Comment by volkflo** [comment]
You have to access keycloak UI from inside your VM:
The easiest would be just to use the browser inside the VM then also you do not have to change the keycloak redirects.

**Comment by AghaSaad04** [comment]
@volkflo I have configured the DevPortal client but I am getting CORS error when I try to login the devportal.

![image](https://user-images.githubusercontent.com/36513474/121077168-bd7b8780-c7f0-11eb-9ec1-d43e1c6d621d.png)

![image](https://user-images.githubusercontent.com/36513474/121077282-e0a63700-c7f0-11eb-8eaf-6a7e95774b75.png)

**Comment by volkflo** [comment]
Can you please check the two things.
On the admin user verify if the `view-profile` and `manage-account` is assigned
![image](https://user-images.githubusercontent.com/13332383/121130268-76ac8280-c82e-11eb-9260-7726b0f95a84.png)
On the keycloak client `account` set
![image](https://user-images.githubusercontent.com/13332383/121130522-ce4aee00-c82e-11eb-8d7a-43285b9c6bf7.png)

The default keycloak settings are pretty secure but will maybe cause some problems with you vm setup.

**Comment by AghaSaad04** [comment]
Hi @volkflo, **view-profile** and **manage-account** was not assigned to admin. I have added them and the CORS error for account has been resolved and able to login to DevPortal.

But now I am facing CORS for gateway and unable to see public APIs here. 

![image](https://user-images.githubusercontent.com/36513474/121198994-fc125000-c88b-11eb-9fc6-54a6dce8e5c9.png)


![image](https://user-images.githubusercontent.com/36513474/121199288-3f6cbe80-c88c-11eb-9801-cbd8e5e48887.png)

**Comment by volkflo** [comment]
Can you please check your configs again? :)
It should be `xyz.abc/apiman` in the screenshot I can see that it is currently `xyz.abc/apimanui`

**Comment by AghaSaad04** [comment]
@volkflo which configs I need to check? Also, I access APIMan through VM-IP:Port/apimanui

**Comment by volkflo** [comment]
![image](https://user-images.githubusercontent.com/13332383/121357425-1a328b80-c932-11eb-9b30-7b634994d0f8.png)

This setting in the environment of the docker-compose.yml of the developer portal.
Replace `http://localhost:8443/apiman` with the IP of your `http://<virtual-machine-ip>:<port>/apiman`

**Comment by AghaSaad04** [comment]
Oh I updated that before but changed **apiman** to **apimanui** my bad. As my APIMan was running on apimanui endpoint. Now that CORS has been resolved for the gateways. 

But there are a few more CORS issue. Any configs that I need to update for them

![image](https://user-images.githubusercontent.com/36513474/121370710-60014b00-c956-11eb-8d20-4be4d9c8bcc5.png)

**Comment by volkflo** [comment]
Can you check if your `apiman.properties` file contains this setting:

```bash
# Set cross origin for the manager; *=any, comma separated names
apiman-manager-ui.allowed-cors-origins=*
```

**Comment by AghaSaad04** [comment]
Hi @volkflo,

yes `apiman/distro/wildfly/src/main/resources/overlay/standalone/configuration/apiman.properties` file contains the following settings

```
# Set cross origin for the manager; *=any, comma separated names
apiman-manager-ui.allowed-cors-origins=*
```

However it is not present in this file `apiman/distro/tomcat/src/main/resources/overlay/conf/apiman.properties`

**Comment by volkflo** [comment]
You can set this as well in the tomcat apiman.properties.
We are working right now on that to fix all the configuration files.

**Comment by AghaSaad04** [comment]
yes, I have added that in properties, Do I need to build that again or just need to run using **./bin/standalone.sh**
Also, sometimes, when I refresh the page I get this error
![image](https://user-images.githubusercontent.com/36513474/121684625-5ef82700-cad8-11eb-9377-33a01af7d6a6.png)

Also I am unable to add/create developers, May be they are linked to the error I have shared earlier.
![image](https://user-images.githubusercontent.com/36513474/121685590-8c91a000-cad9-11eb-9a29-f56fef65cfbe.png)

**Comment by volkflo** [comment]
You just have to restart the application server `./bin/standalone.sh` to apply this setting.
New Users are currently created in keycloak.
A "Developer" is basically just the mapping between a keycloak user and one ore many apiman clients (client apps).

I am currently not sure why you getting this weird CORS error anymore.
I will try to check it and come back to you.

**Comment by volkflo** [comment]
I cannot reproduce this bahavior right now.
Please make sure that `apiman-manager-ui.allowed-cors-origins=*` is really set.

Till the CORS problem is not fixed the Browser is not able to create a Developer.

**Comment by AghaSaad04** [comment]
Below is the snapshot of apiman.properties.

![image](https://user-images.githubusercontent.com/36513474/121697652-b2717180-cae6-11eb-975b-0537f1c19e56.png)

**Comment by AghaSaad04** [comment]
I have attached container logs/errors of apimanDevPortal, that may be helpful to figure out the problem.

[containerLogs.txt](https://github.com/apiman/apiman/files/6638968/containerLogs.txt)

**Comment by volkflo** [comment]
Thanks for the logs.

I was a little bit confused because I thought you are using tomcat. 
But from the logs I can see that you are running on wildfly.

So the config files in the repository (like the one you send to me) are just example.
If you have a running wildfly server the config has to be changed in there e.g. 
`wildfly-root-folder/standalone/configuration/apiman.properties`

But the actual errors are indicating that you now have the wrong/miss-configured database for apiman right now.
The Developer Portal is currently only working if the Apiman Manger has an Elasticsearch as database running.

Please have a look at your current apiman.properties if you have uncommetted the jpa setting if you do not use them.
Otherwise it would be helpful that you provide us the full apiman.properties

**Comment by AghaSaad04** [comment]
This is the apiman.properties currently I am using
Path of this file is `/apiman/distro/wildfly/src/main/resources/overlay/standalone/configuration/apiman.properties`

[apiman.properties.txt](https://github.com/apiman/apiman/files/6639219/apiman.properties.txt)

But I couldnt find apiman.properties file here. Below is the attachment
![image](https://user-images.githubusercontent.com/36513474/121703323-22cec180-caec-11eb-8bda-3981d26e7888.png)

**Comment by volkflo** [comment]
It looks like you are editing the source files in the repository and not the config file from the running application server (wildfly).
Make sure you run the following:
```bash
$ mvn clean install -Pinstall-all-wildfly
$ cd tools/server-all/target/wildfly-dev-server
$ ./bin/standalone.sh
```

In `tools/server-all/target/wildfly-dev-server` you find the `apiman.propties` to edit.

**Comment by AghaSaad04** [comment]
I ran the following commands.  I was getting some test errors, so I added **skipTests** parameter.
```
$ mvn clean install -Pinstall-all-wildfly -DskipTests
$ cd tools/server-all/target/wildfly-dev-server
$ ./bin/standalone.sh
```

I could find the apiman.properties on the following path. I have also attached the file.
 
![image](https://user-images.githubusercontent.com/36513474/121888317-4898d800-cd31-11eb-89f0-4c95b1e98974.png)

[apiman.properties-wildfly.txt](https://github.com/apiman/apiman/files/6648090/apiman.properties-wildfly.txt)

**Comment by AghaSaad04** [comment]
@volkflo any update?

**Comment by msavy** [comment]
Not sure what your issue is, to be honest. We'll be cutting a release soon, so it might be worth waiting for that?

**Comment by volkflo** [comment]
Make sure you have a running elasticsearch somewhere, for example:

`docker run -d --name elasticsearch -p 9200:9200 -e "discovery.type=single-node" elasticsearch:7.13.2`

And use the following properties file:
[apiman.properties.txt](https://github.com/apiman/apiman/files/6660493/apiman.properties.txt)

Please let us know if this is working :)

**Comment by AghaSaad04** [comment]
Hi @volkflo , yes it is working properly now. Thank you so much @volkflo  and @msavy for taking out time to resolve the issue.
So what I have figured out the issue was related to both properties and elasticSearch.

**Comment by volkflo** [comment]
Great to hear that it is finally working for you :)
It should be easier to set up once we changed the quickstarts during the next releases.

**Comment by AghaSaad04** [comment]
Yes that will be helpful. Cheers.
