### ISSUE TITLE
UI side-menu says "[... ] policiy" instead of "policy"

### ISSUE THREAD

**Issue by msavy** [apiman/apiman#1292]
![image](https://user-images.githubusercontent.com/423513/121417446-cfc90300-c961-11eb-8621-7f48688b4475.png)

**Comment by brennanw31** [comment]
I'd like to work on this.

**Comment by msavy** [comment]
Thank you! Please go ahead.

**Comment by msavy** [comment]
> Thank you! Please go ahead.

lol, the person who volunteered deleted their own comment.
