### ISSUE TITLE
How to update the Base URL of Clients

### ISSUE THREAD

**Issue by AghaSaad04** [apiman/apiman#1339]
I tried to setup the whole project again in a new VM after setting up and creating the initial user. I was not able to login, it redirects to some localhost URL but I want that URL to my VM IP.

The attached SS is when I opened up the browser inside VM as I was not able to access keycloak outside the VM due to redirection problems
![image](https://user-images.githubusercontent.com/36513474/122995078-91503100-d3c2-11eb-8ea4-61aeb158e2a6.png)

I am stuck here as I want to update the Base URL to my VM IP. Any properties or configurations that I need to update. Thanks

# Question:

How can I override the localhost IP to VM IP while building the project and before running the APIMan? Thanks

**Comment by volkflo** [comment]
I think you should have a look at the documentation of Keycloak (https://www.keycloak.org/documentation).
This is not apiman related and we cannot provide you much support with that.
