### ISSUE TITLE
Policies don't get updated with plugins

### ISSUE THREAD

**Issue by kkrauth** [apiman/apiman#137]
It appears that when a plugin is updated in the system (for example from 1.0.0-SNAPSHOT to 1.0.1-SNAPSHOT), the plugin-managed policy definition remains pointing at the implementation class of 1.0.0-SNAPSHOT. Because of this, it becomes impossible to upgrade plugin versions without changing their names or manually importing policies with different names for them. Is the idea to include the version of a particular plugin/policy directly in the name? The example plugins don't use this convention.

**Comment by EricWittmann** [comment]
This is a flaw in the current handling of apiman plugins.  Related issues are here, for tracking:

https://issues.jboss.org/browse/APIMAN-293
https://issues.jboss.org/browse/APIMAN-402
https://issues.jboss.org/browse/APIMAN-286

This is something we will be addressing soon.

**Comment by kkrauth** [comment]
Thanks for the update! I'll keep an eye on those tickets.
