### ISSUE TITLE
SAML 2.0 integration pingfederate.

### ISSUE THREAD

**Issue by PrashantMinjar** [apiman/apiman#138]
Hi,

We are trying to integrate apiman saml 2.0 with pingfederate but while configuring the saml option of apiman the NameID Policy Format configuration in the following screen does not provide any options.

We are seeing the following error in my SAML response:

Cannot provide requested name identifier with format urn:oasis:names:tc:SAML:2.0:nameid-       format:persistent

We would like to have the following available in this list

urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified

![image](https://cloud.githubusercontent.com/assets/7235972/7982382/5ba9c236-0ad4-11e5-9ed4-b5314d0b9425.png)

**Comment by EricWittmann** [comment]
This is actually an issue with keycloak (apiman uses keycloak to do some of the authentication related heavy lifting).  Could you file this as a bug or feature request here:

https://issues.jboss.org/browse/KEYCLOAK

There is also a keycloak mailing list here:  

https://lists.jboss.org/mailman/listinfo/keycloak-user

**Comment by msavy** [comment]
@PrashantMinjar did you ever get any feedback from the KC team?
