### ISSUE TITLE
Does ApiMan log requests ?

### ISSUE THREAD

**Issue by akashbhunchal** [apiman/apiman#142]
We need to find out the statistics like which API was used how many times, which user (Application) used the service how many times (metering).

I see the word metering in the docs but all that I could find in the console was RateLimitingPolicy

**Comment by EricWittmann** [comment]
This is the feature I'm working on right now, in fact.  It should be available in 1.1.4.Final.

**Comment by EricWittmann** [comment]
Yesterday I added this feature to master.  The distro will include an instance of Elasticsearch. The Gateway pushes request information into ES.  The UI pulls that information out and displays service metrics graphs.

If you'd like to try it I'd love to get some feedback.  There are three new API Manager REST endpoints:

````
/organizations/{orgId}/services/{serviceId}/versions/{version}/metrics/usage?interval={interval}&from={startDate}&to={endDate}
/organizations/{orgId}/services/{serviceId}/versions/{version}/metrics/appUsage?from={startDate}&to={endDate}
/organizations/{orgId}/services/{serviceId}/versions/{version}/metrics/planUsage?from={startDate}&to={endDate}
````

I'm interested in what other metrics endpoints might be of interest.  Understand that users could also use something like Kibana to create orthogonal metrics dashboards.  The intent is not to create a metrics dashboard within the API Manager UI.

**Comment by EricWittmann** [comment]
This feature is now part of apiman, as of 1.1.4.Final.  Have a look at the blog post about it:

http://www.apiman.io/blog/api-manager/service/ui/metrics/2015/07/06/metrics.html

There are more metrics we can make available, but it's a good start. Let us know what else you'd like to see!
