### ISSUE TITLE
No message error on TLS/SSL

### ISSUE THREAD

**Issue by JYassine** [apiman/apiman#1421]
Hello,

I'm currently working with the new version of apiman (i.e Apiman 2.1) and I'm facing an error when I try to connect to elasticsearch with the protocol https, the problem seems to be in certificate but the error message don't appear in logs :

**The message  :** 
 "Fatal SSL/TLS connection occurred when connecting to Elasticsearch. Underlying SSL/TLS config will likely need to be resolved before retrying): Fatal SSL/TLS connection occurred when connecting to Elasticsearch. Underlying SSL/TLS config will likely need to be resolved before retrying): {0}"

But it seems that the error message that should come from the library "javax.net.ssl.SSLException" is not replaced by the bracket notation "{0}" .

Thank you in advance for your response.

**Comment by msavy** [comment]
As a temporary solution I suggest turning on Java SSL logging: https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/ReadDebug.html
