### ISSUE TITLE
SSL Error thrown on https://localhost:8080/apimanui/

### ISSUE THREAD

**Issue by geertschuring** [apiman/apiman#1478]
When following the instructions on [https://www.apiman.io/latest/download.html](https://www.apiman.io/latest/download.html) and following the link to [https://localhost:8080/apimanui/](https://localhost:8080/apimanui/) my browser (Firefox & Chrome) shows me an error message: SSL_ERROR_RX_RECORD_TOO_LONG

I started Apiman using this command: `docker run -it -p 8080:8080 -p 8443:8443 apiman/on-wildfly:2.1.0.Final`

**Comment by msavy** [comment]
Hi,

8080 is for HTTP traffic.
8443 is for HTTPS traffic.

(This is offset from the official port ranges by 8000 to avoid issues with requiring elevated permissions/privileges for port numbers under 1024)

**Comment by msavy** [comment]
Unfortunately it looks like a bad link was put on the website 😬. I'll fix it.

**Comment by msavy** [comment]
Should be fixed now. Thanks, Geert.

**Comment by msavy** [comment]
https://github.com/apiman/apiman.github.io/commit/8b05f658427611a2d8e40df9556fb7e485e4226d

**Comment by geertschuring** [comment]
Thanks Marc!
