### ISSUE TITLE
UI: all organizations page has broken cards layout on 2.x

### ISSUE THREAD

**Issue by msavy** [apiman/apiman#1482]
* Click on "Browse/Find an Organization"

![image](https://user-images.githubusercontent.com/423513/131977789-f7f10f0f-a9fc-4ea1-9746-d186928d27b4.png)

Seems to have been introduced in 2.x?

**Comment by msavy** [comment]
All APIs page also

**Comment by volkflo** [comment]
![image](https://user-images.githubusercontent.com/13332383/135604142-1537a333-4bc0-494e-ab3c-d31de567a3b0.png)

**Comment by msavy** [comment]
Has this now been fixed?

**Comment by msavy** [comment]
This is really important. If nobody responds I'll have to sort it out myself.
