### ISSUE TITLE
Different rate limits based on path or HTTP method

### ISSUE THREAD

**Issue by ncasaux** [apiman/apiman#1500]
Hello,

I have a requirement where I would like to apply rate limits  to clients, but not to the complete api or clientApp. 

For example, I would like to:
- allow a client to request base path `/cars` with 1 req/s max for HTTP `GET` requests (typically `/cars?brand=toyota` which could return lots of cars, so lots of data, hence the low rate limit)
- allow a client to request base path `/cars}` with 5 req/s max for HTTP `POST` requests (typically a use case where the client provides a list of ids, which would return a quite some of data if the list is large, hence the medium rate limit)
- allow a client to request base path `/cars/{id}` with 20 req/s max for HTTP `GET` requests (typically `/cars/123` which would return only one car, hence the high rate limit)

I could not find how to implement these kind of scenario. Did I miss something ?

Thanks in advance !

**Comment by msavy** [comment]
Hi Nico. The policies we have today can't do exactly what you want. I am available to implement something like that if you want (check out my GH profile).

**Comment by ncasaux** [comment]
Thank you Marc for your answer.
