### ISSUE TITLE
HTTP DEL operation is not supported

### ISSUE THREAD

**Issue by cmoulliard** [apiman/apiman#152]
When using ApiMan 1.1.3.Final, we can't perform a HTTP DEL operation and we get as response :  

```
Request :
curl -v -k -X DEL -H "Authorization: Bearer $TOKEN" https://127.0.0.1:8443/apiman-gateway/Newcastle/CustomerService/2.0/124

Response :

HTTP/1.1 501 Not Implemented
Method DEL is not defined in RFC 2068 and is not supported by the Servlet API
```

Is there a workaround ?

**Comment by msavy** [comment]
Is there any reason you can't use DELETE? DEL doesn't exist in 2068.

**Comment by msavy** [comment]
By that I mean:
    curl -v -k -X DELETE -H "Authorization: Bearer $TOKEN" https://127.0.0.1:8443/apiman-gateway/Newcastle/CustomerService/2.0/124

**Comment by cmoulliard** [comment]
Sorry for the typo error `DEL` --> `DELETE`
