### ISSUE TITLE
Oauth2 keycloak can't be used with 1.1.4.Final as it tries to download policy config schema indefinitively

### ISSUE THREAD

**Issue by cmoulliard** [apiman/apiman#155]
![screenshot 2015-07-09 18 26 05](https://cloud.githubusercontent.com/assets/463790/8600783/174f75ae-2668-11e5-9e07-0b451fd6983c.png)

**Comment by msavy** [comment]
This has already been filed https://issues.jboss.org/browse/APIMAN-527

**Comment by EricWittmann** [comment]
Moved to JIRA - see above.
