### ISSUE TITLE
Eclipse error in persistence.xml due to unexisting class

### ISSUE THREAD

**Issue by cen1** [apiman/apiman#159]
Fresh Eclipse import gives a JPA error:
```
Class "[Ljava.lang.String;@50841467" cannot be resolved	persistence.xml	/apiman-manager-api-jpa/src/main/resources/META-INF	 	JPA Problem
```
I narrowed it down to ```<class>io.apiman.manager.api.beans.services.EndpointPropertyValueBean</class>``` in persiatance.xml which does not seem to exist in the referenced package. After removing the entry the error goes away.

**Comment by EricWittmann** [comment]
Thanks for the report!

**Comment by EricWittmann** [comment]
Fixed: https://github.com/apiman/apiman/commit/e7163f07bb1758a5565f5b23589977bec4c4f74b
