### ISSUE TITLE
Metrics API for hits per resource

### ISSUE THREAD

**Issue by cen1** [apiman/apiman#160]
One interesting addition to the Metrics would be to get number of hits per resource. This would tell you which of the endpoints get hit the most. I am new to ElasticSearch but I tried to first write a query to see if I can retrieve this data (very simplified GitHub API used as producer):
```
{
    "size": 0,
    "aggs" : {
        "resources" : {
            "terms" : { 
                "field" : "resource"
            }
        }
    }
}
```

Result:
```


    {
        "took": 0,
        "timed_out": false,
        "_shards":
        {
            "total": 5,
            "successful": 5,
            "failed": 0
        },
        "hits":
        {
            "total": 27,
            "max_score": 0,
            "hits":
            [
            ]
        },
        "aggregations":
        {
            "resources":
            {
                "buckets":
                [
                    {
                        "key": "cen1",
                        "doc_count": 21
                    },
                    {
                        "key": "users",
                        "doc_count": 13
                    },
                    {
                        "key": "repos",
                        "doc_count": 4
                    },
                    {
                        "key": "user",
                        "doc_count": 2
                    }
                ]
            }
        }
    }
```
This is not really what we want because ES broke the ```resource``` field apart. What I wanted are the full endpoints: ```/users/cen1``` and ```/users/cen1/repos``` for example. Googling around revealed that this happened because the ```resource``` field is "analyzed" and in order to solve the issue it would need to be set to "not_analyzed", but that hinders performance. Some other suggestions were multi field types and script field, the latter didn't work for me.

I'd greatly appreciate if someone with greater ES knowledge could give opinion on this matter.

http://stackoverflow.com/questions/10093638/how-to-prevent-facet-terms-from-tokenizing
http://stackoverflow.com/questions/26212808/get-complete-term-contents-with-aggregations-in-elasticsearch

**Comment by EricWittmann** [comment]
I think the best approach is to mark the field as not_analyzed.  The performance impact should be slight.  I'm going to move this to JIRA.

**Comment by EricWittmann** [comment]
https://issues.jboss.org/browse/APIMAN-540
