### ISSUE TITLE
Devportal Description is missing in overview

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#1623]
On Apiman 3.X the "Developer Portal" is missing in the description on the right side.
![image](https://user-images.githubusercontent.com/13332383/141998643-0224a2e8-d309-453f-ba91-b0d5e2fb1ce2.png)

**Comment by msavy** [comment]
the width of the page is way too much also for the layout. probably need to add a reasonable max-width or similar.

**Comment by DhairyaBahl** [comment]
@volkflo I would like to work on this ! Kindly tell me how can I get started. Thanks ! This will be my first contribution to this project.

**Comment by volkflo** [comment]
Hi @DhairyaBahl,

of couse you can work on that :)

1. Setup your dev environment (https://github.com/apiman/apiman/tree/3.x#quickstart-ie-how-to-run-it)
2. Setup UI dev environment (https://github.com/apiman/apiman/tree/3.x/manager/ui/war)
3.  You are looking for the file: https://github.com/apiman/apiman/blob/3.x/manager/ui/war/plugins/api-manager/html/api/api-overview.html

You can have a look on the other entries in this file.
Let us know if you need further help :)

**Comment by volkflo** [comment]
Done by @msavy or is there any reason to keep this open?
