### ISSUE TITLE
'View API Definition' link & available plans list overflow container on All APIs -> API Details page

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#1645]
### Bug
If you click on an API at All APIs the layout of the page is broken:
![image](https://user-images.githubusercontent.com/13332383/143222367-6ac0d57b-2935-46a8-8c87-6a2f2e9b26cd.png)

### Acceptance:
The plans section should go on the right side of the screen as it was in previous apiman versions.
The API Definition Button should be not displayed directly on the border

**Comment by volkflo** [comment]
Would be helpful if someone could verify that 2.x is not affected.

**Comment by msavy** [comment]
![image](https://user-images.githubusercontent.com/423513/143225651-fdca5095-aff9-443d-b86d-dad56ac224ba.png)

**Comment by volkflo** [comment]
Fixed in 3.x
