### ISSUE TITLE
Blobs: Endpoint should not contain username

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#1654]
### Current behavior

At the moment the V3 blobs endpoint will add the username to the file.
E.g `https://endpoint/apiman/blobs/blobs/46c2-9eb8-cbd054f22474/florian_volk1636461207051_png`

Its not a security problem but I think we should avoid leaking internal data if we can avoid that.
In the scenario of a complete external developer portal we should not have internal usernames viewable in the external views.

### Acceptance
Remove the username from the filename/url.
Eg. Use github style of a url `https:endpoint/143395165-c048f82b-61ab-4a96-88f1-939101371e52.png`

**Comment by msavy** [comment]
This reason for this was just so that it was obvious who actually uploaded the file as it's not explicitly tracked. It's not a problem to change it.
