### ISSUE TITLE
When using the docker image and 8443 logjam vulnerability

### ISSUE THREAD

**Issue by cooktheryan** [apiman/apiman#166]
When attempting to access an endpoint I run into the following error

[rcook@goku ~]$ curl -k https://localhost:8443/apiman-gateway/test/etcd/1.0
curl: (35) SSL received a weak ephemeral Diffie-Hellman key in Server Key Exchange handshake message.

Insecure works as planned
[rcook@goku ~]$ curl -k http://localhost:8080/apiman-gateway/test/etcd/1.0
etcd 0.4.6

This may easily be resolved by updating the image and pushing it to repository but I do not know the underlying OS

**Comment by EricWittmann** [comment]
OK thanks @cooktheryan - we'll have a look at this asap.  I've logged a bug in our JIRA instance if you care to track it there.

https://issues.jboss.org/browse/APIMAN-593

**Comment by msavy** [comment]
Which version of Java are you using? Which OS?

**Comment by cooktheryan** [comment]
I used the docker image from the website for my testing

**Comment by msavy** [comment]
Ah yes, sorry - my mistake

**Comment by cooktheryan** [comment]
All good. Let me know if you need any versions outside of the container
such as platform etc

**Comment by EricWittmann** [comment]
@cooktheryan - have a look at Jorge's response here: https://issues.jboss.org/browse/APIMAN-593

Let me know if that's useful.

**Comment by cooktheryan** [comment]
+1 that should definitely resolve in the fastest fashion
