### ISSUE TITLE
Unexposed APIs disappear completely from the developer portal

### ISSUE THREAD

**Issue by BastianGem** [apiman/apiman#1707]
**Describe the bug**
The following scenario:
An API has been published and exposed in the developer portal.
A developer has subscribed to this API via the developer portal.

After some time, the API publisher decides to remove it from the developer portal (unexpose).
Once this happens, the developer will no longer see his contract on the 'My Applications' page of the developer portal.

This is due to two factors:
1. the developer portal is currently filtering unexposed APIs from the 'My Applications' page to avoid errors.
2. some (maybe all?) endpoints for the developer portal, check if the API for which the information is requested is exposed and either the response remains empty or a 409 is returned

**To Reproduce**
Steps to reproduce the behaviour:
1. publish an API and expose it in the developer portal.
2. create a contract with this API via developer portal or main UI (doesn't matter)
3. unexpose the API from the developer portal
4. visit 'My Applications' page in the developer portal

**Expected behaviour**
Unexposed APIs shouldnt be displayed in the developer portal (featured APIs list, marketplace, API details page etc.).
But existing contracts to unexposed APIs should be displayed on the my apps page.

**Comment by volkflo** [comment]
Will be solved with new discoverability concept.
