### ISSUE TITLE
Pages that indicate that a search request returned no result are only displayed for a second

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#1796]
If a search does return zero results we automatically load the first page of a wildcard search.

# Acceptance

If a search does return zero results that should be shown to the user

**Comment by volkflo** [comment]
Fixed in 3.x.

**Comment by msavy** [comment]
Wonder if we should backport this one onto 2.x

**Comment by volkflo** [comment]
I think you backported this already :)

**Comment by msavy** [comment]
I can't find it on master, but I might be blind 😂

**Comment by volkflo** [comment]
Oh, I thought we merged that as well.
Maybe I remember something different/else.
________________________________
