### ISSUE TITLE
Elasticsearch metadata index ignores indexPrefix

### ISSUE THREAD

**Issue by esbakker** [apiman/apiman#1829]
**Describe your setup**
- Apiman version
  Using [wildfly manager docker image](https://hub.docker.com/layers/apiman/wildfly-manager/latest/images/sha256-677bffd51c7d3e2dae31eff96d77fd15cb652d41465d69aeac7d56af9db5f166?context=explore) in an openshift environment

**Describe the bug**
We're currently running 2 instances of apiman in different openshift projects (staging and prod) which both have their own elastic pods. We're migrating to a single elastic on azure service. This means we want both staging and prod data in the same elastic cluster.
I have configured the `indexPrefix` property and indexes are created correctly.
However on startup it still fails on a missing `apiman-manager-metadata`,`apiman_manager_policydef` and `apiman_manager_role` indexes. (log:  https://gist.github.com/esbakker/2ff774e5b07ea864ab7449245e57b728)

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure apiman manager with indexPrefix

**Expected behaviour**
Manager starts without issues

**Screenshots**
![image](https://user-images.githubusercontent.com/16238519/155738281-19377d01-73b8-468e-b4f9-0e158c7f1081.png)

**Additional context**
The role and policydef issues can be worked around by setting `apiman.migrate.function` to `NONE`

**Comment by msavy** [comment]
Hi Eddy,

A few people have brought up this issue and closely related problems; I think a contribution a while ago caused some issues in this area. I'll try to take a look at it when I have time, but I'm currently busy with some paid client support. 

Sounds like an interesting use-case for Apiman that you have 👍. Would be interested to touch base sometime to hear how you use Apiman and get your feedback (this bug aside 😊).

**Comment by msavy** [comment]
(p.s. my email is available in GH profile)

**Comment by msavy** [comment]
Please verify whether this is fixed for you in 2.2.1.Final. If not, please contact me.
