### ISSUE TITLE
Schema Update error on 1.1.6

### ISSUE THREAD

**Issue by jason-d-hobbs** [apiman/apiman#183]
ERROR [org.hibernate.tool.hbm2ddl.SchemaUpdate] (default task-1) HHH000299: Could not complete schema update: java.lang.UnsupportedOperationException: The application must supply JDBC connections

I'm trying to get apiman connected to a PGSql database.  I'm using the same config that worked with version 1.1.4, but something has changed.  Should I be using a different jndi name now?

standalone-apiman.xml has been patched to include the following:
```xml
<datasource jndi-name="java:/jdbc/ApiManagerDS" pool-name="apiman-manager-api" enabled="true" use-java-context="true">
					<connection-url>jdbc:postgresql://host:port/DBname</connection-url>
					<driver>postgresql-9.4-1201.jdbc41.jar</driver>
					<security>
						<user-name>xxx</user-name>
						<password>xxx</password>
					</security>
				</datasource>
```

Again, this configuration worked on 1.1.4, but no longer works on 1.1.6.  I also noticed that the persistence.xml no longer has the reference to this data source.

What am I doing wrong?

**Comment by EricWittmann** [comment]
Two things. First, 1.1.6.Final actually has a bug in the postgresql DDL.  However it seems you're just letting hibernate do its thing (which is fine).  That said, you can get the corrected DDL here if you wanted:

https://github.com/apiman/apiman/blob/1.1.x/distro/wildfly8/src/main/resources/overlay/apiman/ddls/apiman_postgresql9.ddl

More importantly, there has been a change to the DB support which is probably tripping you up.  Some hibernate/db settings have been moved here:

https://github.com/apiman/apiman/blob/1.1.x/distro/wildfly8/src/main/resources/overlay/standalone/configuration/apiman.properties#L20-L22

In particular the JNDI location is now:

java:jboss/datasources/apiman-manager

I hope that helps!

**Comment by jason-d-hobbs** [comment]
Thanks for the rapid reply!

I changed the JNDI name, and set up the apiman.properties file as you indicated.  The Hibernate schema update then failed on the svc_gateways table.  

I ended up just creating an empty database, switching Hibernate to validate mode, and running the DDL you provided.  Now I have 1.1.6 up and running.  We are still in the evaluation phase, so there wasn't anything in that db that I couldn't recreate quickly anyway.

Lesson learned:  Don't assume I can just upgrade ApiMan and let Hibernate handle the DB updates.  There probably needs to be some sort of migration guide (if there isn't already and I missed it) on how to move between point releases and retain the database.

**Comment by EricWittmann** [comment]
Yes - we need to create a comprehensive upgrade guide, but that doesn't exist yet.  Interestingly this is the second time today that upgrades have come up.  I guess it's time to escalate the task. :)

**Comment by maslick** [comment]
@jason-d-hobbs if you set those two lines in apiman.properties:
```
apiman.hibernate.connection.datasource=java:jboss/datasources/apiman-manager
apiman.hibernate.dialect=io.apiman.manager.api.jpa.ApimanH2Dialect
```
does this mean you are no longer using postgres database, but h2 instead?

**Comment by EricWittmann** [comment]
Yeah you definitely need to use the appropriate hibernate dialect for the database you want to use.
