### ISSUE TITLE
Role extraction in Keycloak OAuth2 plugin not always working?

### ISSUE THREAD

**Issue by msavy** [apiman/apiman#1857]
**Describe your setup**
- Apiman version: 3.0.0-SNAPSHOT

- Environment
  - Operating system: macOS
  - Java version: 11
  - WildFly
  
**Describe the bug**
Some downstream users have reported to me that they have issues extracting roles using the Keycloak OAuth2 plugin. That is, despite assigning a realm role and getting a token, the roles are not 'seen' in the auth policy.

**To Reproduce**
- Add KC OAuth2 policy  
- Extract + forward realm roles
- Add Authz policy
- Protect endpoint using realm role 

**Expected behaviour**
Should allow when has realm role
Should block when not has realm role

**Comment by volkflo** [comment]
I think this is fixed @msavy ? 
This was caused by a wrong configuration.

**Comment by msavy** [comment]
You are correct @volkflo -- closing
