### ISSUE TITLE
Unable to setup postgres for metrics

### ISSUE THREAD

**Issue by mendon26** [apiman/apiman#2013]
**Describe your setup**
- Apiman version
2.2.3
- Environment
  mac os
  - Java version (e.g. 8, 11, 17)
  java version "9.0.4"

- Manager platform e.g. Wildfly, Tomcat)
 wildfly
- Gateway platform (e.g. Vert.x, Wildfly, Tomcat, etc)
  wildfly

**Describe the bug**
I have a working apiman with simple wildfly overlay. Now I am trying to use postgres for metrics

I changed the below files:
apiman-ds.xml****

<?xml version="1.0" encoding="UTF-8"?>
```
<datasources>
  <datasource jndi-name="java:/apiman/datasources/apiman-manager" pool-name="apiman-manager-api" enabled="true" use-java-context="true">
    <connection-url>jdbc:postgresql://localhost:5433/apiman</connection-url>
    <driver>postgresql-42.3.4.jar</driver>
    <pool>
      <max-pool-size>30</max-pool-size>
    </pool>
    <security>
      <user-name>sa_apiman</user-name>
      <password>******</password>
    </security> 
  </datasource>
</datasources>
```

apiman.properties***

```
apiman.hibernate.connection.datasource=java:jboss/datasources/apiman-manager
apiman.hibernate.dialect=io.apiman.manager.api.jpa.ApimanPostgreSQLDialect
apiman.hibernate.hbm2ddl.auto=validate
```

`apiman-gateway.initializers.jdbc.datasource.type=postgresql9`

But when I start the server I get a few errors in the stdout:

![image](https://user-images.githubusercontent.com/32523247/167319518-412b4ca5-9d13-43b6-b520-332f208f7c3e.png)

I am new to apiman, all help is very much appreciated.

Thanks in advance.

**Comment by msavy** [comment]
Hi!

Your datasource names don't match in `apiman.properties` and your datasource `-ds.xml` files shown above.

Try making both of these the same. 

For example:

```
apiman.hibernate.connection.datasource=java:jboss/datasources/apiman-manager

<datasource jndi-name="java:jboss/datasources/apiman-manager" pool-name="apiman-manager-api" enabled="true" use-java-context="true">
```

**Comment by msavy** [comment]
Hi @mendon26, in order to help other Apiman users in the community, I would appreciate if you can let us know if this solution worked for you?

**Comment by mendon26** [comment]
HI @msavy,

The fix you mentioned worked. A stupid mistake by me.

Also, my responses will be mostly in the evenings or weekends.  Surely will have more doubts soon.

Thanks a lot
