### ISSUE TITLE
Layout in 'Edit' versions of policies has large left padding/margin

### ISSUE THREAD

**Issue by msavy** [apiman/apiman#2033]
![image](https://user-images.githubusercontent.com/423513/167945759-0654c5e8-1638-4480-acfe-4652b5149c7e.png)

This is not present when the policy is first inserted (add-policy).

Looks like this was introduced recently?

Should not be too complicated to fix.

**Comment by volkflo** [comment]
I will have a look, I think I know where this comes from.
