### ISSUE TITLE
Race condition on Elasticsearch index creation can occur

### ISSUE THREAD

**Issue by msavy** [apiman/apiman#2035]
Race condition on Elasticsearch index creation can occur. This relates to https://github.com/elastic/elasticsearch/issues/19862

Previously ES didn't throw an exception (you just had to parse the results manually), and it seems contributions that were made afterwards didn't have any logic to handle this.

# Acceptance criteria
- If race occurs, then swallow exceptions from secondary attempts to create the index
- Print a message, but don't stop.

**Comment by volkflo** [comment]
Interesting one :O

**Comment by msavy** [comment]
This issue evidently has been there a long time. 

In earlier versions of ES it didn't throw an exception, you just had to parse the response manually to inspect the errors.

During a contribution a couple of years ago to bump ES, this logic wasn't ported across to the exception-based mechanism. 

So it's very easy to get that error if you are instantiating a fresh index (more likely if your machine has good performance).
