### ISSUE TITLE
Failed to publish API

### ISSUE THREAD

**Issue by mendon26** [apiman/apiman#2044]
I am creating a new API but when I publish it get a failure with no details and no logs printing on the terminal too. It just says 'Failed to publish API'.

Is there a place where I can see the logs? This was working before I setup up postgres db.

Apiman version
2.2.3

Environment
mac os

Java version (e.g. 8, 11, 17)
java version "9.0.4"
Manager platform e.g. Wildfly, Tomcat)
wildfly

Gateway platform (e.g. Vert.x, Wildfly, Tomcat, etc)
wildfly

**Comment by msavy** [comment]
Somehow I missed this.

This isn't enough information for us to help you.

You need to post your Apiman server logs. 

Please either attach as a file or put into code quotation block

**Comment by msavy** [comment]
Please reopen this ticket if you want to follow up
