### ISSUE TITLE
ElasticSearch version

### ISSUE THREAD

**Issue by kkrauth** [apiman/apiman#210]
Apiman uses version 1.3.2 of elasticsearch. I don't know if that was a conscious decision, or just what was available at the time, but Kibana 4 doesn't work with that version of ES index. I recompiled apiman 1.1.7.Final with Elastic Search version 1.7 and ran the tests successfully. The metrics were recorded fine as well and I was able to connect to the index using Kibana 4 and generate some reports. Is there a reason I missed as to why you are not using the latest ES version?

**Comment by msavy** [comment]
FWIW, locally I use 1.7.1 and it works okay for me.

On 3 Sep 2015 19:24, "Kosta Krauth" <notifications@github.com <mailto:notifications@github.com>> wrote:
Apiman uses version 1.3.2 of elasticsearch. I don't know if that was a conscious decision, or just what was available at the time, but Kibana 4 doesn't work with that version of ES index. I recompiled apiman 1.1.7.Final with Elastic Search version 1.7 and ran the tests successfully. The metrics were recorded fine as well and I was able to connect to the index using Kibana 4 and generate some reports. Is there a reason I missed as to why you are not using the latest ES version?

**Comment by kkrauth** [comment]
OK, that sounds promising. I'll go ahead with the assumption that there is no known incompatibility between ES 1.3.2+ and APIman unless someone shouts otherwise. Thanks! :)

**Comment by msavy** [comment]
Bear in mind that we have integration requirements with other projects that
might mean we're tied to a specific version, but you can quite easily
override the version using the maven property associated with elastic
search version.

Look in the root POM.

**Comment by kkrauth** [comment]
That's what I did for now as we are still prototyping everything in embedded mode. It seems to work without a hitch. Thanks for the confirmation, I'll close the ticket.

**Comment by EricWittmann** [comment]
I will update the ES version number to something more reasonable.  We're not using version 1.3.2 for any specific reason.  At the time I implemented ES support, fabric8 (which was a target integration platform for us) was on 1.3.2.  They are now on 1.7.1.  :)
