### ISSUE TITLE
APIMAN UI don't working on tomcat 

### ISSUE THREAD

**Issue by KwanchaiJc** [apiman/apiman#2146]
i used
- Apiman version 2.2.3.Final
- Environment
  - Redhat 7.9
  - Java version 1.8.0_332
  - Apache Tomcat/9.0.64
- Manager platform  Tomcat

i get some error when i start tomcat
![image](https://user-images.githubusercontent.com/85068934/176184503-32fd5a07-12ed-40a7-9c43-655e095eab45.png)
![image](https://user-images.githubusercontent.com/85068934/176183865-7717daab-83db-48bc-b7de-b056dabf4ce5.png)
![image](https://user-images.githubusercontent.com/85068934/176183986-caf87b6a-6b8c-471d-864c-8e4c180a4968.png)
[apimanproperties.zip](https://github.com/apiman/apiman/files/9001242/apimanproperties.zip)

**Comment by KwanchaiJc** [comment]
I've installed elasticsearch and used default apiman.properties already i still found an errors
Please help me investigate this case

Many error : Failed while importing data, Failed to save metadata

![image](https://user-images.githubusercontent.com/85068934/176424586-5f686d4a-1dee-4881-9afd-2de67fcaa4ce.png)
![image](https://user-images.githubusercontent.com/85068934/176424637-4453dcb9-a2de-44ad-99ce-b9ffe9390633.png)
![image](https://user-images.githubusercontent.com/85068934/176424702-f81aa605-3ae1-496c-a89c-91ab7f8fa856.png)
![image](https://user-images.githubusercontent.com/85068934/176425183-78991cd0-d0de-4a32-8483-72321ebe6621.png)

**Comment by msavy** [comment]
Hi,

Can you please post your logs and exceptions as code blocks (bounded by
three backticks) instead of screenshots.

At first glance your keystore and truststore does not look correct. Can you
just leave those blank - you should still be able to connect, unless you
have set up Elasticsearch to be TLS only or similar.

**Comment by KwanchaiJc** [comment]
This apiman.log
[apiman.log](https://github.com/apiman/apiman/files/9010047/apiman.log)

**Comment by msavy** [comment]
I'm afraid I'm traveling right now so can't analyse logs easily.

Hopefully someone else from community will have time to answer

From Apiman 3 onwards it should be easier for people to figure out as we'll
do docker compose distributions.

Might be easier for you to start on the wildfly distribution.

**Comment by volkflo** [comment]
Please try:

- For the `keystore/trustore.path` give the full file name inlcuding the filename. Eg xyz/myKeyStore.jks"
- Please set a password 
- Set `allowAnyHost` and `allowSelfSigned` to true as you are using self signed certs now

**Comment by volkflo** [comment]
We are no elasticsearch experts, so we cannot provide with much elasticsearch support.
You have to read their documentation. I recommend you to use a docker container for elasticsearch. As they provide a quick way to start an elasticsearch for testing. 
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docker.html

Second I recommend to start without certifacates and run elasticsearch as http only. Once that is working you can enable https afterwards.

The tomcat apiman.properties is defaulted to elasticsearch as storage. If the apiman is not able to connect to it, it will not work.
