### ISSUE TITLE
NPE during bootstrap in apiman-manager-ui bower component

### ISSUE THREAD

**Issue by gashcrumb** [apiman/apiman#219]
When adding to a project via `bower install`, during bootstrap I see:

`Uncaught TypeError: Cannot read property 'auth' of undefined`

I'm guessing it's coming from here?

![apiman-manager-js](https://cloud.githubusercontent.com/assets/351660/9876203/49d08e38-5b82-11e5-8588-6a235d0700d4.png)

It'd be good to avoid hitting these NPEs so that the rest of the app can still bootstrap.

**Comment by gashcrumb** [comment]
Note in this case there's no APIMAN_CONFIG_DATA defined yet, planning on adding a dummy one for starters.

**Comment by EricWittmann** [comment]
It's a big problem if there is no APIMAN_CONFIG_DATA yet.  Will need to redesign things a bit if the apiman config isn't being pulled down from the server prior to the apiman UI components starting up.  Reference:

https://github.com/apiman/apiman/blob/master/manager/ui/hawtio/plugins/api-manager/ts/apimanPlugin.ts#L164

**Comment by gashcrumb** [comment]
Yeah, I'd like to have the plugin loaded and be able to configure the endpoint later, at least initially I'm hoping to just use apiman-manager-ui as a bower dependency to avoid linking off to another page from the main console.  Will have to see what else I hit though, am also seeing another conflict which I'm going to raise an issue for right now :-)

**Comment by gashcrumb** [comment]
BTW am working around it using the following so far in my local js which gets me a little further: 

```
var APIMAN_CONFIG_DATA = {
  "apiman": {
    "version": "",
    "builtOn": "",
    "logoutUrl": ""
  },
  "user": {
    "username": "n/a"
  },
  "ui": {
    "header": false
  },
  "api" : {
    "endpoint": "dynamic",
    "auth": {
      "type": "bearerToken",
      "bearerToken": {
        "refreshPeriod": 0
      }
    }
  }
};
```

**Comment by EricWittmann** [comment]
This might be better:

```javascript
var APIMAN_CONFIG_DATA = {
  "apiman": {
    "version": "",
    "builtOn": "",
    "logoutUrl": ""
  },
  "user": {
    "username": "n/a"
  },
  "ui": {
    "header": false
  },
  "api" : {
    "endpoint": "dynamic",
    "auth": {
      "type": "none"
    }
  }
};
```

**Comment by gashcrumb** [comment]
ooh, let me try that, thanks!

**Comment by gashcrumb** [comment]
Works a treat.  Wonder, maybe it's worth skipping [this](https://github.com/apiman/apiman/blob/master/manager/ui/hawtio/plugins/api-manager/ts/apimanPlugin.ts#L164) `getScript` if `APIMAN_CONFIG_DATA` is already defined, then we can avoid a couple 404s going to the console.

**Comment by EricWittmann** [comment]
Happy to skip the config.js script if it's not needed.  @KurtStam - is there anything in the config.js file you're currently bringing down from the server that cannot simply be hard-coded on the client?  Now that the API endpoint is dynamic and figured out in the client perhaps not?

**Comment by EricWittmann** [comment]
Closing as no longer relevant.
