### ISSUE TITLE
`authInterceptor` service name too generic

### ISSUE THREAD

**Issue by gashcrumb** [apiman/apiman#220]
It'd be best to prefix this service name, as it could easily conflict with other components:

https://github.com/apiman/apiman/blob/master/manager/ui/hawtio/plugins/api-manager/ts/apimanPlugin.ts#L115

In my case in the openshift console there's already an `AuthInterceptor` service which essentially serves the same purpose, but now we've a case where angular appears to mix the two (!) causing issues.

**Comment by gashcrumb** [comment]
Hm, and apparently service names in angular are not case sensitive :-/

**Comment by EricWittmann** [comment]
Bummed to learn that the services aren't sandboxed at all for hawtio plugins.  That seems like it could be problematic as the # of plugins grow.  Should *all* of the apiman services be prefixed with Apiman?

**Comment by gashcrumb** [comment]
Oh, take that back about case sensitivity, appears I'm wrong there, I've `authInterceptor` and `AuthInterceptor`.

Well, no, hawtio plugins are just angular modules, and angular apparently doesn't scope services by module at all.  Think in most cases we've been lucky or prefixed generic names as needed to date.  Wonder if angular 2.x makes it better perhaps...

**Comment by EricWittmann** [comment]
So yeah - what are your thoughts on prefixing all services?  It would be super annoying but I have a number of services with generic names (e.g. "Configuration").

**Comment by gashcrumb** [comment]
It's probably worth doing long-term where possible.

**Comment by msavy** [comment]
@gashcrumb Is this all irrelevant now BTW, given your change of tack on apiman as a hawtio plugin?

**Comment by EricWittmann** [comment]
+1 - this is now deprecated.  I'm closing.
