### ISSUE TITLE
1.1.8 Distro Zip is invalid

### ISSUE THREAD

**Issue by jason-d-hobbs** [apiman/apiman#225]
Downloading from here:
http://downloads.jboss.org/apiman/1.1.8.Final/apiman-distro-wildfly8-1.1.8.Final-overlay.zip

Is resulting in a corrupt archive.  Can someone double check that zip file please?

**Comment by jason-d-hobbs** [comment]
{ ~ }  » unzip -t apiman-distro-wildfly8-1.1.8.Final-overlay.zip                                                                                                                      ~
Archive:  apiman-distro-wildfly8-1.1.8.Final-overlay.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of apiman-distro-wildfly8-1.1.8.Final-overlay.zip or
        apiman-distro-wildfly8-1.1.8.Final-overlay.zip.zip, and cannot find apiman-distro-wildfly8-1.1.8.Final-overlay.zip.ZIP, period.

**Comment by EricWittmann** [comment]
I just tested the overlay zip and it seemed OK for me:

https://gist.github.com/EricWittmann/cfbf8ea0de52c2930756

**Comment by EricWittmann** [comment]
How big is the zip on your machine?

```
[ewittman@titmouse testing]$ ls -al apiman-distro-wildfly8-1.1.8.Final-overlay.zip
-rw-rw-r--. 1 ewittman ewittman 121696070 Sep 25 10:03 apiman-distro-wildfly8-1.1.8.Final-overlay.zip
```

**Comment by jason-d-hobbs** [comment]
1.1.7 pulled and unzipped fine.  Repulling 1.1.8 now to retry...

**Comment by jason-d-hobbs** [comment]
Looks like it might be a networking issue on our end.  I didn't notice curl bombing with bytes left to read before.  I've received similar errors on a couple of tries now.  Thanks for the quick reply... sorry to raise a false alarm.

```
curl http://downloads.jboss.org/apiman/1.1.8.Final/apiman-distro-wildfly8-1.1.8.Final-overlay.zip -o apiman-distro-wildfly8-1.1.8.Final-overlay.zip                        
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 97  116M   97  112M    0     0  3705k      0  0:00:32  0:00:31  0:00:01 4482kcurl: (18) transfer closed with 373891 bytes remaining to read
```

**Comment by msavy** [comment]
Maybe we should think about publishing the SHA-1 with the download on the website. What do you think, @EricWittmann?

**Comment by EricWittmann** [comment]
No problem at all, @jason-d-hobbs 

@msavy +1

**Comment by jason-d-hobbs** [comment]
Downloads fine tethered to my cellphone.  I'll talk to our network folks.  Thanks again.

**Comment by EricWittmann** [comment]
No problem and good luck.
