### ISSUE TITLE
Vert.x Gateway is ignoring most of the proxy settings

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#2250]
### Apiman Version

3.0.0-SNAPSHOT

### Apiman Manager Distro

Tomcat

### Apiman Gateway Distro

Vert.x

### Java Version

11

### Operating System

Alpine Linux

### Are you running Apiman in a container, or on an orchestration platform?

Docker / Podman

### Describe the bug

Currently the vert.x gateway does not handle the default java proxy settings (http.proxyHost/Port) in the ConnenctorFactory.
This leads to errors if the Gateway tries to open a connection to the unmanaged API or while trying to resolve the dns as this might be also handled via a corporate proxy.

Further information:

- https://stackoverflow.com/questions/21416114/running-vertx-behind-a-proxy
- https://vertx.io/docs/apidocs/io/vertx/core/net/ProxyOptions.html 

### Expected behaviour

The gateway handles proxy settings at least for the ConnectorFactory.

### Actual behaviour

Java default proxy settings are getting ignored.

### Relevant log output

Please contact me directly if you need logs as I am unable to upload these here.

### Anything else?

There is a partial implementation already existing for the download of plugins (e..g maven central).
It seems that their might be something missing if there is no further magic happening.
https://github.com/apiman/apiman/blob/16bbc9fe6b23dbd4d0bef73400c2ea6ebef38b56/gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/engine/VertxPluginRegistry.java#L197-L218

is probably missing:

```java
httpClientOptions.setProxyOptions(proxyOptions);
```

**Comment by venkatesh2090** [comment]
Hi, I would like to contribute to this project starting with this issue.

I have noticed the [ConnectorFactory](https://github.com/apiman/apiman/blob/master/gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/ConnectorFactory.java#L65-L71) never sets Proxy options, and neither does [HttpClientOptionsFactory](https://github.com/apiman/apiman/blob/master/gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/http/HttpClientOptionsFactory.java). Let me know if my initial analysis was correct. Looking forward to contributing :slightly_smiling_face:.

**Comment by volkflo** [comment]
Hey @venkatesh2090, nice that you would like to contribute.
I already fixed this problem, but did not pushed this to the upstream.
I will try to push a pull request tomorrow, so you can re-check and also test this :)

**Comment by msavy** [comment]
Hey @venkatesh2090 — I'd love to have you involved! 

What kind of areas are you able to contribute to?

**Comment by msavy** [comment]
I've had a quick look at your LinkedIn that was in your GitHub Profile, it seems you have some expertise in testing/test automation. That would be an awesome area to contribute to Apiman. If I created/some tickets for you in that area would it be interesting?

It would be important stuff like helping build some automated smoke tests for Apiman distributions, additional Cypress test coverage, refactoring existing Cypress testing to be more modular/best practices, etc.

If any of that sounds of interest, then I'd be happy to work with you to kick something off.

**Comment by venkatesh2090** [comment]
Hi @msavy. I am less familiar with Cypress and JavaScript, but I would like to start my journey somewhere! Looking forward to it :).

**Comment by msavy** [comment]
https://github.com/apiman/apiman/issues/1726
