### ISSUE TITLE
Issue to access the Admin portal on fresh installation "This site can’t be reached" URL http://localhost:9990/console

### ISSUE THREAD

**Issue by amirkaldor** [apiman/apiman#2292]
after installing a fresh version on windows machine using docker for windows I get the "Welcome to WildFly" page when trying to navigate to "[Administration Console](http://localhost:8040/console)"
I get the error above

Thanks,
Amir

**Comment by msavy** [comment]
What URL were you trying to access?

e.g. http://localhost:8080/apimanui ?

**Comment by amirkaldor** [comment]
thanks for pointing me to my error. I just started the docker and used its default page.

now when I try to get to: http://localhost:8040/apimanui/ I get the following error: 
`11:41:33,143 WARN  [org.keycloak.events] (default task-1) type=LOGIN_ERROR, realmId=apiman, clientId=apimanui, userId=null, ipAddress=172.17.0.1, error=invalid_redirect_uri, redirect_uri=http://localhost:8040/apimanui`

I am using port 8040 and not the default port 8080 is it is used on my machine for a different service
