### ISSUE TITLE
Support Spring Boot microservice for gateway

### ISSUE THREAD

**Issue by donovanmuller** [apiman/apiman#242]
It would be nice to have the gateway available on Spring Boot as an additional [platform](https://github.com/apiman/apiman/tree/master/gateway/platforms).

Our environment is based primarily on Spring Boot services and it would be nice to have the gateway integrate into our stack consistently.

**Comment by EricWittmann** [comment]
Thanks for the feature request.  I've moved it over to our tracking system, JIRA:

https://issues.jboss.org/browse/APIMAN-724
