### ISSUE TITLE
Use of static AES encryption key

### ISSUE THREAD

**Issue by cen1** [apiman/apiman#2466]
### Apiman Version

master

### Apiman Manager Distro

WildFly

### Apiman Gateway Distro

WildFly

### Java Version

8

### Operating System

Ubuntu 20.04

### Are you running Apiman in a container, or on an orchestration platform?

No (Bare Metal)

### Describe the bug

What is the significance of this hardcoded AES key? https://github.com/apiman/apiman/blob/master/common/util/src/main/java/io/apiman/common/util/AesEncrypter.java#L39

1. What is the encryption used for?
2. Is this key overriden with some config?
3. Is it a security issue?

I tried to parse through the code but could not quite answer any of the above.

**Comment by msavy** [comment]
It's an optional feature that allows data to be encrypted in the database at-rest.

It means that certain configuration fields that might contain passwords can't be viewed in the database fields and require decryption in the application.

You don't have to use it.

https://www.apiman.io/blog/data-encryption/

It comes with an example/default key, but it's

**Comment by cen1** [comment]
@msavy thank you for the quick explanation, last part of your comment seems to have cut off.

**Comment by msavy** [comment]
was meant to say 'but it's something you can change if you want'

If your company needs support or anything custom doing, don't hesitate to reach out 👍

**Comment by klemenfn** [comment]
Just thinking out loud, and it might be a breaking change, but wouldn't it make more sense to not have a default key at all and throw a runtime error (refuse to start) if key is not provided? Because using a default key is the same as not using encryption at all so it really should never be used.

**Comment by cen1** [comment]
Just thinking out loud, and it might be a breaking change, but wouldn't it make more sense to not have a default key at all and throw a runtime error (refuse to start) if key is not provided? Because using a default key is the same as not using encryption at all so it really should never be used.

**Comment by msavy** [comment]
Yes, we don't advertise it as being of more than obfuscatory value unless you actually provide your own key. You also need to provide the same key clusterwide or it won't work (as I'm sure you had guessed). 

For example, it means that if you do an export of Apiman's config you don't accidentally expose the details directly in cleartext when catting it out or something like that.

Happy to have a feature request ticket opened and we can see if someone offers to sponsor some kind of enhancement in that area. It would require some thought as there are also complications around key rotation and other best practices, assuming it's ever got more than obfuscatory value in practice to at-rest encrypt certain DB fields.

In a tangential issue, I'd also like to implement better support for things like Hashicorp Vault throughout Apiman, but that will likely be through my company's enterprise offering.
