### ISSUE TITLE
Failed to load API definition

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#2502]
### Discussed in https://github.com/orgs/apiman/discussions/2501

<div type='discussions-op-text'>

<sup>Originally posted by **ronimhd** April 11, 2023</sup>
Dear all,

I got this error if I click "API Documentation" button in Portal, and I do not logged in. If I already logged in, the page will be displayed correctly without error.
![image](https://user-images.githubusercontent.com/25297110/231063628-534f99b4-36de-4d87-b4d5-1e72337150ad.png)
(http://apiman.localhost:8080/portal/swagger/mylab/myhttpbin/1.0?try=false&publicAPI=false)
I use 3.1.1 Final version.
My question is, whether this is bug, or I missed some configuration?
</div>

**Comment by msavy** [comment]
This evidently needs to be handled a bit more gracefully in the backend API (and possibly the UI too). If the API has been exposed publicly, there's no reason the API definition can't be displayed without requiring a login.

**Comment by msavy** [comment]
Unless anyone disagrees?

**Comment by msavy** [comment]
Okay, thanks. I'm hoping to find a bit more time to spend tidying up and reworking UI stuff soon, but I'm trying to juggle several different things at the moment.

I'll get there 😅.
