### ISSUE TITLE
IPBlacklist Policy is not working and needs a guidance for testing the IP Blacklist policy to check if it is working or not 

### ISSUE THREAD

**Issue by mansighule1** [apiman/apiman#2520]
### Apiman Version

2.1.0.Final

### Apiman Manager Distro

WildFly

### Apiman Gateway Distro

WildFly

### Java Version

1.8.0_262

### Operating System

windows 10

### Are you running Apiman in a container, or on an orchestration platform?

Docker Compose

### Describe the bug

IPBlacklist Policy is not working and needs a guidance for testing the IP Blacklist policy to check if it is working or not..?

I added the IP blacklist policy to the API and added my system's IP in the blacklist's list.
I hit the generated endpoint(using postman) from my system's IP and then also I'm able to access that endpoint and not getting any response that access from this IP is restricted.

Want a detail guidance over that how to test the IP blacklist/whitelist policy and check if the policy is applied to the particular endpoint

### Expected behaviour

Want to figure out that is IP blacklist policy working or not?

**Comment by volkflo** [comment]
Just a hint as I just saw the platform is windows:
The IP address of docker is probably a different one than the one of your system.
