### ISSUE TITLE
Malformed URL proxying in service gateway.

### ISSUE THREAD

**Issue by mrogelja** [apiman/apiman#257]
Hi ! Thanks for this project that rocks !

Here is a bug : Proxified url containing %23 (aka: urlencoded #) are cut after the char %23.

Ex: https://192.168.99.100:8443/apiman-gateway/my-arg/my-service/1.0/api/persons/%2325:12/knows is proxified into https://api.something.com/api/persons/

Tks.

**Comment by EricWittmann** [comment]
Thanks for the bug report.  I've added it to the official apiman bug tracker here:

https://issues.jboss.org/browse/APIMAN-763
