### ISSUE TITLE
Problems with allowedIssuers 

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#2578]
### Apiman Version

3.1.2.Final

### Apiman Manager Distro

Tomcat

### Apiman Gateway Distro

Vert.x

### Java Version

11

### Operating System

Linux

### Are you running Apiman in a container, or on an orchestration platform?

Kubernetes

### Describe the bug

Recent changes (https://github.com/apiman/apiman/commit/759a0d2e4c87419693725e7e331d0e8522f780fb) cause problems depending on your keycloak endpoint.

If the auth server url contains an path with `/` (e.g. `http://keycloak/my/Cool/Path`) the following does not work:
https://github.com/apiman/apiman/blob/c4419395ba2b5858304bd21b81fb2639af2a545b/gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/auth/KeycloakOAuthFactory.java#L178-L194

The path is treated as one segment which causes problems in the later URL constructions as the `/` will be encoded to `%2f` which causes problems in the discovery.

In addition this feature forces you to use allowedIssuers.
If you do not want this (as you may are only using the internal domain) we should the option in the default config to disabled allowedIssuer checks.

### Expected behaviour

Path should be correctly supported.

We could do it something like this, which correctly splits the path by `/`
```java
List<String> pathSegments = builder.getPathSegments();
         pathSegments.add("realms");
         pathSegments.add(realmName);
``` 

In addition the check can be disabled via `   "validateIssuer": false` in the gateway config json.

**Comment by msavy** [comment]
Did you make a PR for this? Or you just letting me know about it

**Comment by volkflo** [comment]
Ehm, that is a good question.
Will check again. I can probably provide a PR.
First, I have to remember if a fixed it already or just disabled the check

**Comment by msavy** [comment]
Unless there is a compelling reason, I'm probably not going to do another v3 release, so may not be worth it.

**Comment by volkflo** [comment]
Yeah, I guess that is not worth it as this is a very special use case for us.
Not sure how much changes are for Apiman 4 but I guess it would be useful for the V4 release

**Comment by msavy** [comment]
Fixed in supported version of 3.x, I'll roll it into Apiman 4
