### ISSUE TITLE
Support for specifying muliple elasticsearch hosts

### ISSUE THREAD

**Issue by cen1** [apiman/apiman#2587]
### Apiman Version

master

### Apiman Manager Distro

WildFly

### Apiman Gateway Distro

WildFly

### Java Version

11

### Operating System

Centos 8

### Are you running Apiman in a container, or on an orchestration platform?

No (Bare Metal)

### Describe the bug

It seems that it is not possible to specify multiple ES hosts when running against a proper multi node production ES cluster.

A look into the code also reveals that a single host is used: https://github.com/apiman/apiman/blob/347f4a8de4d3f9feea7a4daa01cec7d12f654a0d/common/es/src/main/java/io/apiman/common/es/util/DefaultEsClientFactory.java#L105 even though the builder can accept multiple.

Is this just an original sin that was overlooked when ES support was added? Is there a way to do it that I missed?

I saw some workarounds with keepalived thrown across the ES nodes but that is not a good solution, all ES libraries I have ever used accept an array and handle the proper selection internally.

**Comment by msavy** [comment]
This is not a bug
