### ISSUE TITLE
Issuer build Error in KeycloakOAuthFactory.buildIssuerWithRealm

### ISSUE THREAD

**Issue by deathknight0718** [apiman/apiman#2622]
### Apiman Version

3.1.2.Final +

### Apiman Manager Distro

WildFly

### Apiman Gateway Distro

Vert.x

### Java Version

openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)

### Operating System

Fedora 38

### Are you running Apiman in a container, or on an orchestration platform?

No (Bare Metal)

### Describe the bug

When the program calls `KeycloakOAuthFactory.buildIssuerWithRealm("http://keycloak:8080/auth", "apiman")`.
The generated endpoint has one more character `%2F`:

```
http://keycloak:8080/%2Fauth/realms/apiman
```

Causes the URL call to fail.

**Comment by msavy** [comment]
Duplicate. 

This is fixed in the [commercially supported version of Apiman 3.x](https://www.blackparrotlabs.io).

It'll be rolled into Apiman 4 when that is ready
