### ISSUE TITLE
APIMAN Gateway encodes even the reserve characters from query parameter value

### ISSUE THREAD

**Issue by dhruvesh9** [apiman/apiman#2639]
### Apiman Version

2.2.3.Final

### Apiman Manager Distro

WildFly

### Apiman Gateway Distro

WildFly

### Java Version

JDK 8

### Operating System

GNU/Linux

### Are you running Apiman in a container, or on an orchestration platform?

No (Bare Metal)

### Describe the bug

Client sends request /openapi-fun-product-catalog/productOffering?id=PKG1,PKG2

APIMAN forwards the request to backend server encoding the query parameter value. Hence, the query parameter becomes
id=PKG1%2CPKG2

Based on URI rfc specification document, there are predefined reserved characters like , (comma) ;(semicolon) ,..
https://www.rfc-editor.org/rfc/rfc3986#page-12

Is there a reason why APIMAN encodes the param values? anyway to override this behavior?

Note : I sense the behavior should be same even for the latest APIMAN version i.e. 3.x as the code hasn't changed.

https://github.com/apiman/apiman/blob/2.2.3.Final/gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpApiConnection.java#L131-L138

### Expected behaviour

APIMAN not to encode the reserve characters
id=PKG1,PKG2

### Actual behaviour

id=PKG1%2CPKG2

**Comment by msavy** [comment]
2.2.3.Final is not supported in the community version, if you want support for older versions http://www.blackparrotlabs.io — happy to be connected

**Comment by msavy** [comment]
My address is marc-at-blackparrotlabs.io

**Comment by msavy** [comment]
Ah @dhruvesh9 — I just realised you are from Cerillion. I have some contacts there already. Would you like me to connect everyone together via email?
