### ISSUE TITLE
apiman with mariadb ver 10.11

### ISSUE THREAD

**Issue by Satishshelake** [apiman/apiman#2662]
got below exception when tried to use mariadb 10.11 database 
 Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [payload] in table [notifications]; found [longtext (Types#LONGVARCHAR)], but expecting [json (Types#OTHER)] 

Added alter  tabe script -

ALTER TABLE notifications MODIFY COLUMN payload JSON;

But same issue found.

**Comment by msavy** [comment]
I suggest using Postgres for now. If you are a support customer who needs MariaDB then feel free to reach out.

**Comment by Satishshelake** [comment]
need to support Mariadb 10.11 version now. Please could you help me in it?

**Comment by Satishshelake** [comment]
Recursive sql 'WITH' statement is not supported in triggers mariadb, chanaged triggers.mysql.sql file. Triggers are working now, But couldn't managed error 

Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [payload] in table [notifications]; found [longtext (Types#LONGVARCHAR)], but expecting [json (Types#OTHER)]
17:30:37,770 ERROR [stderr] (Thread-112) at [org.hibernate@5.3.20.Final](mailto:org.hibernate@5.3.20.Final)//org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateColumnType(AbstractSchemaValidator.java:159)

Also tried alter in liquibase configuration.

**Comment by msavy** [comment]
> need to support Mariadb 10.11 version now. Please could you help me in it?

Sorry, I can't work for your company for free  . We need to put food on the table like everyone else.

 If you are a support customer, I'd be happy to put in the work to make it happen?

**Comment by Satishshelake** [comment]
No problem, Let me find out first :)

**Comment by msavy** [comment]
If not, it may be that someone in the community can help  you.
