### ISSUE TITLE
apiman ui - angularjs can't be loaded when using 'gulp'

### ISSUE THREAD

**Issue by cmoulliard** [apiman/apiman#271]
When we start the nodejs server using gulp command and next we access the web server using the browser, then angularjs can't be loaded

````
├── anymatch@1.3.0 (arrify@1.0.0, micromatch@2.3.2)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, object-assign@3.0.0, fancy-log@1.1.0, lodash._reinterpolate@3.0.0, has-gulplog@0.1.0, minimist@1.2.0, through2@2.0.0, chalk@1.1.1, lodash.template@3.6.2, gulplog@1.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── chokidar@1.2.0 (arrify@1.0.0, async-each@0.1.6, glob-parent@2.0.0, is-glob@2.0.1, is-binary-path@1.0.1, lodash.flatten@3.0.2, readdirp@2.0.0, fsevents@1.0.5)
dabou:~/Code/redhat/apiman/apiman-core/manager/ui/hawtio$ gulp
[19:02:15] Using gulpfile ~/Code/redhat/apiman/apiman-core/manager/ui/hawtio/gulpfile.js
[19:02:15] Starting 'default'...
[19:02:15] Starting 'build'...
[19:02:15] Starting 'browserify'...
[19:02:15] Starting 'css'...
[19:02:15] Starting 'fonts'...
[19:02:16] Starting 'images'...
[19:02:16] Finished 'build' after 80 ms
[19:02:16] Starting 'watch'...
[19:02:16] Finished 'watch' after 30 ms
[19:02:16] Starting 'connect'...
[19:02:16] Finished 'connect' after 18 ms
[19:02:16] Finished 'default' after 133 ms
[19:02:16] Server started http://localhost:2772
[19:02:16] Finished 'css' after 640 ms
[19:02:24] Finished 'images' after 8.18 s
[19:02:26] Finished 'browserify' after 11 s
[19:02:26] Finished 'fonts' after 11 s
[19:02:26] Starting 'path-adjust'...
[19:02:26] Finished 'path-adjust' after 50 ms
[19:02:26] Starting 'clean-defs'...
[19:02:26] Finished 'clean-defs' after 15 ms
[19:02:26] Starting 'tsc'...
[19:02:31] Finished 'tsc' after 4.83 s
[19:02:31] Starting 'template'...
[19:02:32] Finished 'template' after 286 ms
[19:02:32] Starting 'concat'...
[19:02:32] Finished 'concat' after 9.13 ms
[19:02:32] Starting 'clean'...
[19:02:32] Finished 'clean' after 6.41 ms
````

![screenshot 2015-11-12 19 03 34](https://cloud.githubusercontent.com/assets/463790/11126678/5adfcfb0-8970-11e5-923d-081ac9277db3.png)

This warning message is repeated continuously : apiman [7:11:22 PM]>>  |Dash| >> Loading page.
VM510:34942 WARNING: Tried to load angular more than once.

**Comment by EricWittmann** [comment]
Running gulp will only serve up the UI... but the UI won't work without a valid backend running.  Note the error is referring to localhost:8080/apiman - this is where the UI is (by default) looking for the API Manager REST services.

I'm going to take this opportunity to write a blog post about this (I haven't blogged in awhile!).  I'll post a link to the blog when I'm done.

**Comment by cmoulliard** [comment]
Problem solved after running also the manager-es project. Should be good to document that like also that ElasticsSearch version 1.7.2 is required (doesn't work with 2.0)

**Comment by EricWittmann** [comment]
Yep - that's the solution.  Still a good idea to blog about it.  And +1 to documenting the required version of ES.

I'm also going to add the maven shade plugin to each of the apiman-servers so that an executable fat JAR is built for each.

**Comment by EricWittmann** [comment]
http://www.apiman.io/blog/micro-services/development/2015/11/12/micro-services.html

**Comment by cmoulliard** [comment]
The problem is still there even if we start manager-es ...

**Comment by EricWittmann** [comment]
What problem, specifically?  Are you referring to the CONNECTION REFUSED error from your earlier screenshot?  If so, can you access the manager's REST API via the URL included in the error?

If not, do you have any more details about the error?

**Comment by cmoulliard** [comment]
Here is what has been started :  
- front (= hawtio apiman front) using gulp
- manager-es
- gateway-es
- external elasticsearch server (1.7.2)

When, I try to open http://localhost:2772/api-manager, I will get these javascripts warning message reported many times till we get the error added hereafter

```
deps.js:157394 yes!
apiman-manager-ui.js:1377 Using header: plugins/api-manager/html/headers/true.include
apiman-manager-ui.js:1543 apiman [2:13:33 PM]>>  |Dash| >> Loading page.
deps.js:76459 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
VM61:55502 WARNING: Tried to load angular more than once.
VM61:157394 yes!
apiman-manager-ui.js:1543 apiman [2:13:34 PM]>>  |Dash| >> Loading page.
VM63:55502 WARNING: Tried to load angular more than once.
VM63:157394 yes!
apiman-manager-ui.js:1543 apiman [2:13:34 PM]>>  |Dash| >> Loading page.
VM65:55502 WARNING: Tried to load angular more than once.
VM65:157394 yes!
apiman-manager-ui.js:1543 apiman [2:13:35 PM]>>  |Dash| >> Loading page.
VM67:55502 WARNING: Tried to load angular more than once.
VM67:157394 yes!
apiman-manager-ui.js:1543 apiman [2:13:36 PM]>>  |Dash| >> Loading page.
VM69:55502 WARNING: Tried to load angular more than once.
VM69:157394 yes!
apiman-manager-ui.js:1543 apiman [2:13:36 PM]>>  |Dash| >> Loading page.
VM71:55502 WARNING: Tried to load angular more than once.
VM71:157394 yes!
apiman-manager-ui.js:1543 apiman [2:13:37 PM]>>  |Dash| >> Loading page.
VM73:55502 WARNING: Tried to load angular more than once.
```

Error
```
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"headerInclude","newVal":"plugins/api-manager/html/headers/true.include"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"isAdmin"},{"msg":"pageState == 'loaded'","newVal":false}],[{"msg":"headerInclude","newVal":"plugins/api-manager/html/headers/true.include"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"isAdmin"},{"msg":"pageState == 'loaded'","newVal":false}],[{"msg":"headerInclude","newVal":"plugins/api-manager/html/headers/true.include"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"isAdmin"},{"msg":"pageState == 'loaded'","newVal":false}],[{"msg":"headerInclude","newVal":"plugins/api-manager/html/headers/true.include"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"isAdmin"},{"msg":"pageState == 'loaded'","newVal":false}],[{"msg":"headerInclude","newVal":"plugins/api-manager/html/headers/true.include"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":""},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"fn: regularInterceptedExpression","newVal":"api-manager"},{"msg":"isAdmin"},{"msg":"pageState == 'loaded'","newVal":false}]]
http://errors.angularjs.org/1.4.7/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22ms…g%22%3A%22pageState%20%3D%3D%20'loaded'%22%2C%22newVal%22%3Afalse%7D%5D%5D
    at deps.js:26810
    at Scope.$digest (deps.js:42606)
    at Scope.$apply (deps.js:42839)
    at done (deps.js:37288)
    at completeRequest (deps.js:37486)
    at XMLHttpRequest.requestLoaded (deps.js:37427)


```

I can reach this url `http://localhost:8080/apiman/currentuser/info` manually within my browser  

```
{"username":"admin","fullName":"admin","email":"admin@example.org","joinedOn":1447679409427,"admin":true,"permissions":[]}
```

**Comment by kahboom** [comment]
@cmoulliard - From your error, it looks like Angular is trying to load a header that does not exist. This is likely because the header is loaded dynamically, using a value defined in the configuration file (see step 3 below). I'm not able to reproduce this. Can you run me through from clone to build? Do you notice any errors in the console where you are running gulp? Also, what is the environment? Here is what I did to try and reproduce, to no avail:

1. Clone the APIMan repo: `$ git clone git@github.com:apiman/apiman.git`
2. `cd` into the repo. Build with `mvn clean install -Pinstall-all-wildfly8`
3. Duplicate `/manager/ui/hawtio/apiman/config.js-SAMPLE` and rename to `config.js`
4. Run manager-es, gateway-es, and elasticsearch server (for reference, I'm running 1.7.2 as well).
5. From within the `/manager/ui/hawtio` dir run `$ gulp`.

Then in the browser I navigated to http://localhost:2772/api-manager/, which loaded without issues.

**Comment by msavy** [comment]
Can you post your current `/manager/ui/hawtio/apiman/config.js`? Wonder if there's something funky in there.

**Comment by cmoulliard** [comment]
- I have cloned apiman to my github account and I'm using the latest version of the code
- I have also cloned the confg.js sample file localy. Here is its content
- manager-es, gateway-es and elasticsearch (1.7.2) are running

````
var APIMAN_CONFIG_DATA = {
  "apiman" : {
    "version" : "1.1.0-SNAPSHOT",
    "builtOn" : "2015-01-01",
    "logoutUrl" : "logout"
  },
  "user" : {
    "username" : "admin"
  },
  "ui" : {
    "header" : true,
    "metrics" : true
  },
  "api" : {
    "endpoint" : "http://localhost:8080/apiman",
    "auth" : {
      "type" : "basic",
      "basic" : {
        "username" : "admin",
        "password" : "admin123!"
      }
    }
  }
};
```

**Comment by cmoulliard** [comment]
I don't really understand why we get so many times this message ` WARNING: Tried to load angular more than once.`

**Comment by EricWittmann** [comment]
You see that error message because there is *some* javascript file that is referenced by the index.html but which can't be found.  When this happens, gulp seems to serve up the index.html file again.  So, for example, if the "deps.js" file hasn't been generated, then all hell breaks loose.

Rachel - any way we can configure gulp to return a 404 for a resource it can't find?

**Comment by kahboom** [comment]
@cmoulliard - The default contents for config.js ([see here](https://github.com/apiman/apiman/blob/master/manager/ui/hawtio/apiman/config.js-SAMPLE)) should be as follows:

```
var APIMAN_CONFIG_DATA = {
  "apiman" : {
    "version" : "1.1.0-SNAPSHOT",
    "builtOn" : "2015-01-01",
    "logoutUrl" : "logout"
  },
  "user" : {
    "username" : "admin"
  },
  "ui" : {
    "header" : "apiman",
    "metrics" : true
  },
  "api" : {
    "endpoint" : "http://localhost:8080/apiman",
    "auth" : {
      "type" : "basic",
      "basic" : {
        "username" : "admin",
        "password" : "admin123!"
      }
    }
  }
};
```

Your `header` property is currently defined as `true`, but should instead be `apiman`. Because the header is loading dynamically like `'/headers/<config.ui.header>.include`, it is trying to load `true.include`, which doesn't exist. Changing that property in your config.js should resolve the issue.

@EricWittmann - I'm not sure that it's a Gulp-specific issue. Angular crashes because it tries to trigger a `$digest` cycle over and over again ([see here](https://docs.angularjs.org/error/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22ms%E2%80%A6g%22:%22pageState%20%3D%3D%20%27loaded%27%22,%22newVal%22:false%7D%5D%5D)). The best way to prevent this is to include a default value in the code if the .include file doesn't exist, and use one that does.

**Comment by kahboom** [comment]
@EricWittmann - Just to reiterate, we're both saying the same thing because, you're 100% right, it's basically referencing JavaScript that doesn't exist, which in this case is a template (the include file). The HTML of the include file is transpiled into JS through a Gulp plugin during the build process.

**Comment by EricWittmann** [comment]
Good catch @kahboom - the value of `header` should definitely be `"apiman"` instead of `true`.

Also @kahboom - we definitely agree on the problem.  However, my question is this:  how come if I type in some non-existent path in my browser, gulp serves up the `index.html` file rather than giving me a 404 error?  Example, type this into your browser:

```
http://localhost:2772/should-be-404
```

You'll get the UI instead of a 404.  I don't care very much about this, but ultimately it's what causes the "you're loading angular multiple times!" error rather than just failing to load some particular resource.

**Comment by EricWittmann** [comment]
There is no error message in the console.  Did you perhaps just reload the /500 error page?  Instead try going to:

http://127.0.0.1:2772/

**Comment by cmoulliard** [comment]
I don't see anymore this screen after doing a cleanup locally of my elasticsearch server.

**Comment by EricWittmann** [comment]
So is everything working properly now?

On Tue, Nov 17, 2015 at 8:09 AM, Charles Moulliard <notifications@github.com

**Comment by cmoulliard** [comment]
Yes. We can close the ticket

**Comment by EricWittmann** [comment]
Great!

On Tue, Nov 17, 2015 at 8:13 AM, Charles Moulliard <notifications@github.com

**Comment by kahboom** [comment]
@EricWittmann - This is certainly possible, though perhaps not with the Gulp third-party library we are using now, since that seems to be a known issue. I'll open up a JIRA for this and will test out a few things.
