### ISSUE TITLE
Support loadbalancing feature with multiple vertx instances

### ISSUE THREAD

**Issue by cmoulliard** [apiman/apiman#272]
See here for an example : https://github.com/vert-x3/vertx-examples/tree/master/core-examples/src/main/java/io/vertx/example/core/http/sharing

**Comment by msavy** [comment]
This already happens. Just change the number of verticles in the config file to suit your requirements.

Please consult the README: https://github.com/apiman/apiman/blob/master/gateway/platforms/vertx3/vertx3/README.adoc#verticles <https://github.com/apiman/apiman/blob/master/gateway/platforms/vertx3/vertx3/README.adoc#verticles>

Also, note that the Vert.x 3 gateway is not considered to be production ready quite yet - hence we don’t make a lot of noise about it (presently).
