### ISSUE TITLE
Gateway default credentials

### ISSUE THREAD

**Issue by maslick** [apiman/apiman#284]
When creating a gateway via UI which **Configuration Endpoint** and **Configuration Endpoint credentials** should I use? 

Using this 
```
Configuration Endpoint: http://localhost:8080/apiman-gateway-api/
Username: apimanager
Password: apimanager
```

results in: 
```
Authentication to the gateway failed.  Perhaps check that your credentials are correct.
```

**Comment by EricWittmann** [comment]
That must be old documentation.. where did you find it so that I can update it? :-) 

I believe those settings are correct except for the password which should be:

```
apiman123!
```

**Comment by maslick** [comment]
It works! Where is it in the documentation? And is it possible to change the credentials? How?
Thank you.

**Comment by EricWittmann** [comment]
Excellent!  The gateway api is protected by keycloak ... If you log into the KC console you can change the user credentials.

```
http://localhost:8080/auth
admin
admin123!
```

**Comment by maslick** [comment]
Thanks @EricWittmann !
