### ISSUE TITLE
Create a branch to support deployment of apiman on OSGI container (Karaf, JBoss Fuse)

### ISSUE THREAD

**Issue by cmoulliard** [apiman/apiman#285]
The existing project is not really OSGI compliant and can'y be deployed as such within the OSGI containers as Apache Karaf, Felix or JBoss Fuse

So, we should crate a branch within the project to manage these things : 
- Convert the JAR into Bundles (-> add the Apache Felix Maven plugin to generate the OSGI METADATA)
- Create a feature file to deploy the project on Karaf - JBoss Fuse
- Add some pax-exam tests to "test" apiman into a OSGI container
- Contact JBoss Logging & Resteasy project to request that they deliver their project as OSGI bundles too (https://issues.jboss.org/browse/RESTEASY-1267)
- Fix issue with Weld - https://github.com/weld/core/pull/1229

**Comment by cmoulliard** [comment]
- Summit a PR to weld project to add the missing packages : https://github.com/weld/core/pull/1229

**Comment by msavy** [comment]
AFAIK we make no real attempt to be OSGi compliant - we had an initial requirement for this way back at the start of the project, but that was dropped. 

I'll let @EricWittmann chime in on this definitively, but in my view:

I think part of the difficulty is that we don't have enough resources to reliably develop, maintain, test, support (etc) OSGi compliance. The project was never really designed upfront for OSGi, so will likely be quite difficult.

**Comment by EricWittmann** [comment]
Exactly, @msavy - we don't have a requirement to run on karaf/osgi and I don't think there has been much call for it in the community.  Certainly not enough for us to spend apiman development time on it.  However, I believe that Charles is actually working on the items in his bulleted list - so if he contributes the osgi support then that will be great! :)

**Comment by minibiti** [comment]
Hi guys,
Is there anything new regarding this issue?
We are using JBoss Fuse in production and it would be really nice to have this kind of possibility in order to avoiding having one extra server (wildfly) in front in order to be able to use APIMAN.
Thanks for the update!

**Comment by msavy** [comment]
@cmoulliard Charles, any update on this?

**Comment by EricWittmann** [comment]
@minibiti - I think it is probably fair to say that this effort has died out.  I know from experience that converting software designed to run in a j2ee application server environment can be quite challenging to convert to apache karaf.  I suspect there were just too many roadblocks to make the effort worthwhile.  Sorry. :(

**Comment by cmoulliard** [comment]
The work is not yet finished as I'm struggling to discover all the CDI Annotated class packaged into a WAR deployed on Karaf / JBoss Fuse. The war archive has been created with all the Apiman jar files
