### ISSUE TITLE
Stack trace lost during service publication

### ISSUE THREAD

**Issue by outofcoffee** [apiman/apiman#312]
In `GatewayClient`, the method `readRegistrationException()` makes certain assumptions about the stack trace string returned by the `GatewayApiErrorBean`. Unfortunately, in some cases, where the stack trace cannot be parsed by the `parseStackTrace()` method, a `null` value is returned and the following happens:

1. `readRegistrationException()` attempts to set a `null` stack trace on the `exception` object, causing a `NullPointerException` to be thrown
2. The actual stack trace is never logged and the reason for the failure is lost, making debugging difficult

## Example

If the ES instance is unreachable, an `io.apiman.gateway.engine.beans.exceptions.PublishingException` is thrown at `io.apiman.gateway.engine.es.ESRegistry.publishService(ESRegistry.java:81)`. This is passed to `readPublishingException()`, which throws an exception trying to parse the stack trace, resulting in `null` being returned and the behaviour above occurring.

The end result is that the original issue (actually `java.net.ConnectException: Connection refused`) is masked by the `NullPointerException` in the logs.

## Suggestions

1. Check the value returned by `readPublishingException()` is non-null before calling `setStackTrace()`
2. If an exception is thrown by the parsing code, at least log the original stack trace string at ERROR level

**Comment by EricWittmann** [comment]
I think this might be fixed on master already.  I am out until after the new year but will have a look then!

**Comment by outofcoffee** [comment]
Hi @EricWittmann, thanks for your reply. Unfortunately on master, both `readRegistrationException()` and `readPublishingException()` methods exhibit this behaviour:

https://github.com/apiman/apiman/blob/master/manager/api/gateway/src/main/java/io/apiman/manager/api/gateway/rest/GatewayClient.java

The `return null;` on line 332 causes a NPE to be thrown on lines 271 and 291 when they call `exception.setStackTrace(null)`, meaning any parsing issue, such as the one described here, results in the loss of the `error.getStacktrace()` String, and the NPE being logged instead.

**Comment by EricWittmann** [comment]
Yep you're right.  Will fix this asap.
