### ISSUE TITLE
 No options to delete or rename organisations, services, applications.

### ISSUE THREAD

**Issue by ade90036** [apiman/apiman#320]
Hi There, 

i was playing around apiman-ui from the wildfly container. I created a couple of test organisation and then  when i understood what they are used for i wanted to model them the way they are in our organisation. 
However i didn't find any documentation that explained this or found a  way from the UI to achieve this.

I had to delete the database and start from scratch.

Is this functionality hidden or missing?

Regards

Andrea

**Comment by EricWittmann** [comment]
Surprisingly this functionality is missing.  It's actually trickier than you'd think to implement.  However, deleting in particular is something we'll finally have implemented sometime during the current 1.2.x line of development.  There will be some pre-conditions that will need to be met before something can be deleted, but it should at least solve this use-case you have mentioned.

In particular, it's tricky to do a delete of an Organization if it were to have one or more *published* APIs in it.  Especially when those APIs could have valid Contracts from registered Apps.  And those Apps could exist in other Orgs.  

However, if we set some pre-conditions, then it becomes a more manageable problem - and we can simply inform the user why a delete is not currently possible.  :)

**Comment by ade90036** [comment]
Ok, 

I really would like to contribute. Can you tell me what components classes i would need to change? 

Once i've created proper unit-test i could create a pull request if you like.

Regards

Andrea

**Comment by EricWittmann** [comment]
HI Andrea - contributions are always welcome!  For reference, here are the various JIRA tickets associated with deleting entities:

https://issues.jboss.org/browse/APIMAN-890
https://issues.jboss.org/browse/APIMAN-883
https://issues.jboss.org/browse/APIMAN-882

If you wanted to start with deleting Organizations I would be happy to write up some information in the relevant JIRA ticket (APIMAN-890) that would help get you started.

How does that sound?

**Comment by ade90036** [comment]
Fantastic...

We are probably going to start working quite extensively with this tool, so
please don't be offended if we are going to create a lot of noise by
reporting issues. :)

I really appreciate your prompt reply.

Regards

Andrea

**Comment by EricWittmann** [comment]
No problem at all.  Happy to have strong community interest!

**Comment by EricWittmann** [comment]
I'll write up some notes in JIRA:

https://issues.jboss.org/browse/APIMAN-890

Hopefully I can add some information to help you get started on it.  Can you let me know what your JIRA userId is?

**Comment by EricWittmann** [comment]
OK Andrea - I have updated the JIRA with some information that will hopefully get you started.  Let me know if anything is unclear!

**Comment by EricWittmann** [comment]
Closing this in favor of the JIRA tickets for tracking purposes.  See links to JIRA above.
