### ISSUE TITLE
issue regarding breaking a contract

### ISSUE THREAD

**Issue by ade90036** [apiman/apiman#322]
Hi there, 

I think i have found an bug, but i'm not sure.

I'm testing the capabilities of apiman, and one feature which i'm trying to simulate is the ability to revoke an apikey. 

So keeping this in mind, I've created one service based on the apiman-echo service from the tutorial and i've setup an client-app called test-app. 

I've created a contract from the the service and the application which has given me an client-api with URL as follows:

http://localhost:8081/apiman-gateway/test-organisation/echo/1.3?apikey=480dac84-829c-4d24-8402-2020eec4a982 

Now if i test the url, it works it returns me the correct response. BTW, i'm using the latest and grates 1.2.0. (which i got it from here)

The interesting bit happens when i go back to my test-app under the Contract section and i click on "Break Contract" button.  I would have expected to see that the previous request would have thrown some sort of error but this is not the case.

I can call the URL indefinitely and it is only when i create a new contract that the URL (apikey) stops working.

N.B. I've "Re-Register" the application after i've broken the contract.

Is this the intended behaviour.

You help is extremely appreciated. 

Regards

Andrea

**Comment by EricWittmann** [comment]
It is very possible that you have hit a bug with breaking a contract and re-registering.  I'll have to reproduce this locally to confirm, but what you've described *should* work.  You can track our progress for this bug here:

https://issues.jboss.org/browse/APIMAN-895

**Comment by EricWittmann** [comment]
Hi @ade90036 - I have created an automated test for this use-case *and* I've tested it manually with the latest version of apiman and I have been *unable* to reproduce this problem.

If you can provide specific steps to reproduce the problem, could you add them to the JIRA issue linked above?

Thanks!

**Comment by ade90036** [comment]
Hi Eric,

It's strange that the unit tests are passing, i'm wondering is there is an
issue with the UI not firing correct AJAX request.

i've added steps to reproduce and a screen recording of the apimanui.

Regards

Andrea

**Comment by EricWittmann** [comment]
Thanks for the video, in particular.  That's very helpful in confirming that I really did understand your steps.  I'll try to reproduce in a couple of other configs and we'll see how it goes.
