### ISSUE TITLE
Website: API docs don't load due to CORS issue

### ISSUE THREAD

**Issue by outofcoffee** [apiman/apiman#326]
The API docs at http://www.apiman.io/latest/api-manager-restdocs.html display an empty page:

<img width="1436" alt="docs_fail" src="https://cloud.githubusercontent.com/assets/1248633/12372556/e4877db4-bc54-11e5-8946-7249809a9725.png">

The page tries to load this URL http://www.apiman.io/latest/apidoc/manager/index.html but fails due to a CORS issue:
```
Refused to display 'http://www.apiman.io/latest/apidoc/manager/index.html' in a frame because it set 'X-Frame-Options' to 'DENY'.
```

**Comment by msavy** [comment]
Might be a security feature being injected by one of your addons (e.g. ABP, noscript)? Works OK for me; looking at the headers I don't see `X-Frame-Options` being set.

```
[msavy@mmbp tmp]$ curl -vv http://www.apiman.io/latest/api-manager-restdocs.html
*   Trying 185.31.18.133...
* Connected to www.apiman.io (185.31.18.133) port 80 (#0)
> GET /latest/api-manager-restdocs.html HTTP/1.1
> Host: www.apiman.io
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: GitHub.com
< Content-Type: text/html; charset=utf-8
< Last-Modified: Sat, 09 Jan 2016 19:19:30 GMT
< Access-Control-Allow-Origin: *
< Expires: Sat, 16 Jan 2016 13:46:59 GMT
< Cache-Control: max-age=600
< X-GitHub-Request-Id: B91F1218:2F2E:1069EA6:569A477B
< Content-Length: 7987
< Accept-Ranges: bytes
< Date: Sat, 16 Jan 2016 13:36:59 GMT
< Via: 1.1 varnish
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-lcy1122-LCY
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1452951419.877224,VS0,VE96
< Vary: Accept-Encoding
< X-Fastly-Request-ID: f5194981b96da6f77d2ca1416fac840797cb37f7
<
```

**Comment by msavy** [comment]
![image](https://cloud.githubusercontent.com/assets/423513/12372641/09f40a20-bc57-11e5-9ab3-dddbaeb05896.png)

**Comment by outofcoffee** [comment]
Thanks @msavy - 'twas AdBlock.

**Comment by EricWittmann** [comment]
Well I suppose we *are* advertising our API... ;)
