### ISSUE TITLE
Add a test case covering system variable to externalize endpoint host

### ISSUE THREAD

**Issue by cmoulliard** [apiman/apiman#334]
Following our discussion about how to externalize the host defined within the Api Implementation `http://${api_host}/service/echo`, it could be interesting to include a test case covering that

Questions :  
- Where is the best place to add this use case (here --> https://github.com/apiman/apiman/blob/master/gateway/test/src/test/java/io/apiman/gateway/test/) ?
- Can we design I design the test use case based on this example - https://github.com/apiman/apiman/blob/master/gateway/test/src/test/java/io/apiman/gateway/test/SimpleEchoReplacementTest.java ?

**Comment by EricWittmann** [comment]
Yes, and yes. :)

**Comment by cmoulliard** [comment]
Perfect. I will have a look tomorrow. BTW, the existing unit test works with a System Properties while this is not the case when we pass this Systemp properties to wildfly on the command line or when defined within its standalone.sh file ...

**Comment by EricWittmann** [comment]
Yes that's true - because in this particular case, the unit test is where the property replacement needs to happen, not on the server.  That unit test is *not* testing server-side property replacement.

**Comment by EricWittmann** [comment]
Sorry - are you saying that SimpleEchoReplacementTest.java fails when you run it against apiman in Wildfly?  Even when defining the appropriate system property in WF?

**Comment by cmoulliard** [comment]
This is working after specifying the System Property within the domain.xml file of Wildfly
```
        <property name="api_host" value="9191"/>
```

**Comment by EricWittmann** [comment]
Closing as this seems to be working now.

**Comment by cmoulliard** [comment]
Yep and we have also a test covering that

On Wed, Jan 27, 2016 at 5:54 PM, Eric Wittmann <notifications@github.com>
wrote:

> Closing as this seems to be working now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apiman/apiman/issues/334#issuecomment-175741494>.
>



-- 
Charles Moulliard
Apache Committer & PMC / Architect @RedHat
Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io
