### ISSUE TITLE
APIMan 1.2.2-SNAPSHOT not available in JBoss public repo

### ISSUE THREAD

**Issue by kunallimaye** [apiman/apiman#371]
When trying to build the latest quickstarts, the build fails because APIMan components with version **1.2.2-SNAPSHOT** are not available in JBoss public repository group.

> http://repository.jboss.org/nexus/content/groups/public

**Comment by kunallimaye** [comment]
Obvious workaround is the download and build apiman locally. Not ideal though

**Comment by EricWittmann** [comment]
Our artifacts are actually deployed to sonatype.  You can see that 1.2.2-SNAPSHOT is available:

https://oss.sonatype.org/content/repositories/snapshots/io/apiman/apiman-manager-api-core/1.2.2-SNAPSHOT/

Sadly we neglected to add the sonatype snapshot repository to the relevant pom.xml files.  :(  I'll get that taken care of asap.

**Comment by kunallimaye** [comment]
Thanks Eric.

Any reason why we wouldn't add to JBoss Public though?

**Comment by EricWittmann** [comment]
We used to publish to jboss public, but it sometimes took a couple of days for artifacts to be rsync'd over to central.  This was problematic for releases and for some downstream projects.

I guess there's no reason we couldn't go back to jboss just for snapshot releases.  But I think central tends to be more stable and is easier to deploy into.

**Comment by msavy** [comment]
And another reason is that JBoss Nexus is slow for those of us outside of US (and also slow for CI, for whatever reason - I think they have transparent caches for central but not JBoss ).

**Comment by EricWittmann** [comment]
@kunallimaye - by the way, can you confirm the original bug report?  I'm looking at the quickstarts and remembering that they don't actually reference any apiman components.

Did you perhaps mean that the apiman-plugins repository failed to build?

**Comment by kunallimaye** [comment]
@EricWittmann you are correct. I meant **apiman-plugins** and not **apiman-quickstarts**.

Apologies for the confusion.
