### ISSUE TITLE
Reuse data of the testing plans

### ISSUE THREAD

**Issue by cmoulliard** [apiman/apiman#384]
The gateway and manager data used for their testing plans data could be reused also to test Karaf osgi container, ...

test-plan-data
test-plans
test-configs

I propose to generate a test-jar file containig them or to move them under another maven module

**Comment by EricWittmann** [comment]
The bulk of these tests are already contained within separate test modules:

https://github.com/apiman/apiman/tree/master/manager/test/api
https://github.com/apiman/apiman/tree/master/gateway/test

These modules are intended to be used to share tests across platforms.

**Comment by msavy** [comment]
If there is more to add to this, please feel free to repopen.
