### ISSUE TITLE
"Component not found: io.apiman.gateway.engine.components.IHttpClientComponent"

### ISSUE THREAD

**Issue by drushmarkit** [apiman/apiman#414]
I am writing my own policy plugin and I am trying to use the IHttpClientComponent which the developer docs say is available.  However I receive a ComponentNotFoundException when my plugin tries to retrieve it.  On further inspection I can't find an implementation of the component in the repo.  Is this component actually available anywhere?  This is on 1.2.1.Final.

<code>
Component not found: io.apiman.gateway.engine.components.IHttpClientComponent","trace":"io.apiman.gateway.engine.beans.exceptions.ComponentNotFoundException: Component not found: io.apiman.gateway.engine.components.IHttpClientComponent\n\tat io.apiman.gateway.engine.impl.ConfigDrivenComponentRegistry.createAndRegisterComponent(ConfigDrivenComponentRegistry.java:115)\n\tat io.apiman.gateway.engine.impl.ConfigDrivenComponentRegistry.getComponent(ConfigDrivenComponentRegistry.java:71)\n\tat io.apiman.gateway.engine.policy.PolicyContextImpl.getComponent(PolicyContextImpl.java:81
</code>

Thanks
David

**Comment by msavy** [comment]
Can you try adding the following to your `apiman.properties`

```
apiman-gateway.components.IHttpClientComponent=io.apiman.gateway.platforms.servlet.components.HttpClient
```

**Comment by msavy** [comment]
Looks like the default servlet `apiman.properties` is missing this for some reason. This should fix our issue, and if so, I'll make a PR to add that omission.

**Comment by drushmarkit** [comment]
Slight correction, but that works.  Class name is HttpClientComponentImpl.

Thanks
David

**Comment by msavy** [comment]
Thanks for reporting! This was somehow overlooked/removed at some point from the servlet's default `apiman.properties` config.

**Comment by msavy** [comment]
See also: https://issues.jboss.org/browse/APIMAN-1002

**Comment by drushmarkit** [comment]
Thanks for the quick response!
