### ISSUE TITLE
init scripts for wildfly 10

### ISSUE THREAD

**Issue by drushmarkit** [apiman/apiman#428]
This may be a question for the wildfly repo, but I am trying to setup 1.2.2.Final as a service on redhat.  I'm not seeing the init.d scripts under the wildfly/bin directory.  Is there a reason that is no longer present?  Can the init script from v9 still be used?  Will apiman 1.2.2 run with wildfly 9?

Thanks
David

**Comment by EricWittmann** [comment]
The question of where the init scripts might have gone is definitely a wildfly question.

However, I call tell you that apiman should run just fine on Wildfly 9.  There is a "Wildfly 9" tab on the download page:

http://www.apiman.io/latest/download.html

Just go to that link and then select "Wildfly 9" in the "Getting Started (WildFly)" section.

**Comment by drushmarkit** [comment]
Thanks, appreciate the response.

**Comment by EricWittmann** [comment]
No problemo!  :)
