### ISSUE TITLE
Apiman 1.2.2 external Keycloak Issue

### ISSUE THREAD

**Issue by garysmi2** [apiman/apiman#430]
Hi,
not sure if it's actually myself doing something wrong here. Anyway,

Apiman 1.2.2-Final
KeyCloak 1.9.0-Final

I am trying to get apiman to authenticate against an external existing working keycloak with existing realms which work fine.

For the moment, for convenience, I am running Apiman and Keycloak on the same machine using 
-Djboss.socket.binding.port-offset=1000 parameter when invoking Apiman standalone.

Apiman start command, where standalone-apiman,xml is in the "bin" directory:
`
./standalone.sh -Djboss.socket.binding.port-offset=1000 -Djboss.bind.address=10.0.2.15 -c standalone-apiman.xml `

Using DNSMasq for name resolution locally.

Both Apiman and Keycloak are under https://scamps.cit.ie        
Self Signed Certs.
API Man https port 9443
Keycloak https port 8443

1. I've imported the apiman realm into the existing Keycloak  server using this file:
 ```
https://github.com/apiman/apiman/blob/master/distro/data/src/main/resources/data/apiman-
realm.json
```

and set the redirect URL's for apimanui client.

2. I've modified standalone-apiman.xml   auth-server   element to point to 

`https://scamps.cit.ie:8443/auth`

3. I login to Apiman using:

`https://scamps.cit.ie:9443/apimanui`

Issue:

After attempting to login the redirect to keycloak occurrs, however it is to:

`https://scamps.cit.ie:9443/auth ... ... ..`

rather than the external keycloak server

`https://scamps.cit.ie:8443/auth`

As a result it does not work.

Wondering if this is a known issue or if it's my own mistake.

**Comment by msavy** [comment]
Can you post your `standalone-apiman.xml`?

**Comment by garysmi2** [comment]
Hi msavy,
I've attached my config.

Forgot to mention too incase it is significant using WildFly-10.0.0-Final,

thanks.

[standalone-apiman.xml.txt](https://github.com/apiman/apiman/files/160038/standalone-apiman.xml.txt)

**Comment by garysmi2** [comment]
Hi msavy,

I've resolved the redirect issue.  In addition I have to pass in   -Djboss.server.config.dir parameter at the command line which I noticed was in standalone.sh startup script.

However, on inputting login credentials and redirecting to apiman I'm getting a 403 Forbidden. I'll close this now though and see if I can resolve my 403,

cheers.

**Comment by EricWittmann** [comment]
Quick note:  the apiman realm file we have checked in is just a starting point - it may require a bit of tweaking to get it working with apiman in your particular configuration.

**Comment by garysmi2** [comment]
Hi Eric,

yes you are right on the mark.  A bit of looking at the logs and incrementally getting rid of the errors got me going. 
Basically I  cut and pasted from Keycloak the jboss client installation configs into standalone-apiman.xml and now Apiman is up and running using the external Keycloak. 

Now I know the procedure I can regenerate the public/private keys etc.,

Cheers.

**Comment by EricWittmann** [comment]
Great!  Nice job. :)
