### ISSUE TITLE
Getting error=invalid_client_credentials, grant_type=authorization_code

### ISSUE THREAD

**Issue by jcruiz95** [apiman/apiman#433]
I tried to follow the instructions to point to an external keycloak server. However, I keep getting 'Forbidden' error after attempting to login using admin/admin123! My apiman is running on my local machine and is going against a keycloak running on a docker container (http://192.168.99.100:8080/auth). Is there anything I'm doing wrong? 

**On my apiman console instance, I get the following error:**
22:39:47,262 ERROR [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-2) failed to turn code into token
22:39:47,264 ERROR [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-2) status from server: 400
22:39:47,264 ERROR [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-2)    {"error_description":"Client secret not provided in request","error":"unauthorized_client"}

**On the keycloak server, I get the following:**
02:09:45,832 WARN  [org.keycloak.events] (default task-9) type=CODE_TO_TOKEN_ERROR, realmId=apiman, clientId=apimanui, userId=null, ipAddress=192.168.99.1, error=invalid_client_credentials, grant_type=authorization_code
02:35:49,216 ERROR [org.keycloak.theme.ExtendingThemeManager] (default task-10) Failed to find LOGIN theme apiman, using built-in themes
02:39:47,156 WARN  [org.keycloak.events] (default task-16) type=CODE_TO_TOKEN_ERROR, realmId=apiman, clientId=apimanui, userId=null, ipAddress=192.168.99.1, error=invalid_client_credentials, grant_type=authorization_code

**Comment by EricWittmann** [comment]
Hi there.  We definitely need to improve the External Keycloak instructions as well as the realm file we include in the distribution!  But for now, I think the discussion here should help:

https://github.com/apiman/apiman/issues/431

**Comment by jcruiz95** [comment]
Thanks, Eric. I did try the 2 things that were noted in #431 and similar to the person who reported the issue, marking it 'public' worked. I was initially contemplating on doing this, however, I thought doing so will somehow lessen the security in place or is that not the case? Anyway, thanks again for the fast response to my reported issue--really appreciate it! I have been searching for similar issues on the web for a few days so this was a great help indeed.

**Comment by EricWittmann** [comment]
I do think that using a public client may be somewhat less secure, but to be honest I'm not sure in what way.  I've been looking for an explanation in the keycloak documentation but so far I haven't found anything (to be honest I haven't looked THAT hard).  :)

Note that I believe you can get Confidential clients to work - you should "simply" need to generate secret credentials for each client (via the keycloak UI) and then copy/paste those credentials into the appropriate place in standalone-apiman.xml.

An example of where the secret gets configured in standalone-apiman.xml is here:

https://github.com/apiman/apiman/blob/master/distro/wildfly10/src/main/resources/overlay/standalone/configuration/standalone-apiman.xml#L439

If you choose to do this, make sure you also remove the _*public-client*_ element as well:

https://github.com/apiman/apiman/blob/master/distro/wildfly10/src/main/resources/overlay/standalone/configuration/standalone-apiman.xml#L439

**Comment by jcruiz95** [comment]
I thought that the other guy did that and it didn't work--I did change the secret to the default secret (password) in the example config file and was my current setting prior to the change. What I have not tried is re-generate via the KC server but I don't see how that would be any different? :-)

**Comment by EricWittmann** [comment]
I know there have been some folks who managed to get Confidential clients working - so I'm 90% sure it's possible.  :)

We have a task on our to-do list to really get the instructions for this improved.

**Comment by jcruiz95** [comment]
Anyway I can reach out to those folks who got it working? :-)

**Comment by EricWittmann** [comment]
I think you might be able to hit up @garysmi2 - see this thread:  https://github.com/apiman/apiman/issues/430
