### ISSUE TITLE
Multiple endpoint addresses on an APIMan-fronted service

### ISSUE THREAD

**Issue by jason-d-hobbs** [apiman/apiman#440]
We have a situation where the backend service could be running on a clustered server, in an active/active configuration.  That is, the service we're protecting with APIMan could be running on two server instances at the same time.

Is there support for APIMan doing load-balancing across these two back ends?  We could, of course, do it via DNS and just tell APIMan the CName and that would sort of work, but wouldn't recover in case of failure of one of the back ends.

We could also perhaps handle it in OpenShift, since we are hosting APIMan inside OpenShift Enterprise. 

Any suggestions appreciated.

**Comment by EricWittmann** [comment]
We don't currently have any load balancing support, but this isn't the first time the topic has come up.  We're trying to be a bit careful about our scope, and it's not really clear to us whether load balancing should be in scope for apiman.

What you could do of course is run haproxy or something similar in front of your API impl.  Then point apiman at the load balancer endpoint.

I could be convinced that *simple* load balancing might be appropriate for apiman to handle, but it's a can of worms that already has very good solutions.

I'm open to counter-arguments!  :)

**Comment by jason-d-hobbs** [comment]
I understand the can-o-worms issue.  I think we'll try to use the 'external services' procedures in OpenShift Enterprise to handle it... as outlined here.

https://docs.openshift.com/enterprise/3.1/dev_guide/integrating_external_services.html

If this feature makes it in, we could make use of it.  Not a showstopper, as you are correct in stating there are other ways to handle it.

Thanks for the prompt response, Eric.

**Comment by EricWittmann** [comment]
No problem - would you be up for creating a JIRA ticket for this?  That's always helpful, and it would give you a way to track its progress.

**Comment by jason-d-hobbs** [comment]
Sure.  I'll do that now.

**Comment by jason-d-hobbs** [comment]
https://issues.jboss.org/browse/APIMAN-1045

**Comment by EricWittmann** [comment]
Thanks!
