### ISSUE TITLE
Add Policy disabled

### ISSUE THREAD

**Issue by ashee** [apiman/apiman#454]
I am following the video at https://vimeo.com/112063377. I am stuck at the 3:09 mark, while adding Basic Authentication Policy. The "Add Policy" button is disabled. I see a bug report at https://issues.jboss.org/browse/APIMAN-695. Is there any workaround?

**Comment by msavy** [comment]
The bug likely isn’t related to what you’re describing

Did you fill in the ‘authentication realm’ field?

Which version of apiman are you using?

**Comment by ashee** [comment]
Realm: HttpBin (just made it up like screencast that has Echo)

apiman version: 1.2.3.Final

**Comment by ashee** [comment]
Using chrome Version 49.0.2623.112 (64-bit) on osx - 10.10.5 (14F1713)

<img width="607" alt="screen shot 2016-04-17 at 3 27 42 pm" src="https://cloud.githubusercontent.com/assets/237894/14589479/13f17bfa-04b1-11e6-8d28-7ee5d561054c.png">

**Comment by msavy** [comment]
You didn't already publish the API Version or ClientVersion, did you? 

That's the only way I seem to be able to reproduce this behaviour (which is correct, but possibly confusing you).

**Comment by msavy** [comment]
For instance, as shown below you can try to add a policy, even thought the API Version is published and is unmodifiable (you must retire or create a new version). 

![image](https://cloud.githubusercontent.com/assets/423513/14589656/72f68d88-04df-11e6-9000-7a07d38921b6.png)

@EricWittmann @kahboom We should probably hide the 'Add Policy' button when an API, ClientApp and/or Plan has been published. Here's a ticket - https://issues.jboss.org/browse/APIMAN-1114

**Comment by ashee** [comment]
I tried it by creating a new version of the API - same result. 

<img width="1209" alt="screen shot 2016-04-17 at 4 08 33 pm" src="https://cloud.githubusercontent.com/assets/237894/14589713/e2947a52-04b6-11e6-8dbf-7efe308c2e26.png">

**Comment by ashee** [comment]
Here is a screencast 
![apiman-add-policy-bug](https://cloud.githubusercontent.com/assets/237894/14589842/1b20bc3e-04ba-11e6-93da-c16a2c147a83.gif)

**Comment by msavy** [comment]
It's your password manager that's causing the problem by the looks of it, possibly because it's intercepting some of the data the app is trying to store. 

Try disabling the add-on. I couldn't quite make it what it is called, but it popped up after you attempted to add the password.

**Comment by ashee** [comment]
I am using 1Password. I tried it on another browser (Safari) that does not have this plugin - no joy.

**Comment by ashee** [comment]
Ok - retried from beginning in Safari. It seems to have worked now. However, IMO this is still a bug since there are 1Password users like me at large.
![apiman-add-policy-bug-safari](https://cloud.githubusercontent.com/assets/237894/14589999/b069e1dc-04bd-11e6-93ba-b4fd50eaf6cb.gif)

**Comment by msavy** [comment]
I'm not actually sure why your addon would cause that behaviour. Perhaps it's stealing focus from the window in a way that's breaking the validation. I wonder if it's at all related to this  https://github.com/angular/angular.js/issues/3133

Hopefully our UI expert @kahboom will be able investigate. 

Glad you got things resolved!
