### ISSUE TITLE
Intermittent plugin load failures

### ISSUE THREAD

**Issue by drushmarkit** [apiman/apiman#457]
I have a custom plugin that is is being loaded through a local maven repo.  However I am intermittently seeing an exception being returned when I hit the gateway:

`at java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.Exception: Invalid plugin file at: /opt/wildfly/standalone/data/apiman/plugins/**plugin-path**/plugin.war
at io.apiman.gateway.engine.impl.DefaultPluginRegistry.readPluginFile(DefaultPluginRegistry.java:322)
at io.apiman.gateway.engine.impl.DefaultPluginRegistry.loadPlugin(DefaultPluginRegistry.java:250)
... 40 more\nCaused by: java.io.FileNotFoundException: /opt/wildfly/standalone/data/apiman/plugins/**plugin-path**/**plugin-name**.war/.work/lib/keycloak-core-1.9.0.CR1.jar (No such file or directory)`

David

**Comment by drushmarkit** [comment]
Issue also recorded here: https://issues.jboss.org/browse/APIMAN-1021

**Comment by EricWittmann** [comment]
Thanks for the report.  I am closing this in favor of the JIRA issue report.
