### ISSUE TITLE
Missing initialisation configuration using the es storage type for manager

### ISSUE THREAD

**Issue by donovanmuller** [apiman/apiman#477]
As [per the docs](http://www.apiman.io/latest/installation-guide.html#_how_to_use_elasticsearch_instead_of_an_rdbms_in_the_api_manager) on how to use Elasticsearch for the API Manager storage type, on first run, the same initialisation that happens for the `jpa` storage type does not happen for the `es` storage type.

This leads to some funnies:

* No auto-grant roles have been configured. (See #273)
* No default gateway created
* Client apps and contracts are not linked:

![screen shot 2016-05-19 at 10 34 12 am](https://cloud.githubusercontent.com/assets/1175891/15388032/51a2eba6-1db0-11e6-8fec-f490116a6676.png)

Note that `apiman-manager.storage.es.initialize=true` is set:

```
apiman-manager.storage.type=es
apiman-manager.storage.es.protocol=${apiman.es.protocol}
apiman-manager.storage.es.host=${apiman.es.host}
apiman-manager.storage.es.port=${apiman.es.port}
apiman-manager.storage.es.username=${apiman.es.username}
apiman-manager.storage.es.password=${apiman.es.password}
apiman-manager.storage.es.timeout=${apiman.es.timeout}
apiman-manager.storage.es.initialize=true
```

**Comment by EricWittmann** [comment]
As it happens, my last checkin should have resolved this.  The quickstart used to ship with a pre-configured H2 database, loaded with all the default apiman settings (roles, gateway, etc).

As of https://github.com/apiman/apiman/commit/d059ecbbaa31922d68bb817b57c0c250f204bf8e we've move away from that.  Instead, there is a bootstrap config file (an apiman formatted import/export file) which will be consumed on first startup.  This will work regardless of the configuration.

So, in the next release this should no longer be a problem!

**Comment by EricWittmann** [comment]
PS: the next release will be 1.2.6.Final

**Comment by EricWittmann** [comment]
Also note: the *apiman-manager.storage.es.initialize* option only controls whether the index mappings will get automatically installed.  It doesn't control whether default "out of the box" data gets populated on start up.  Confusing I guess. :(

**Comment by donovanmuller** [comment]
Understood, as it's sort of related 😄 , please see https://gitter.im/apiman/apiman?at=573d7280831fd2d97d9fe412

**Comment by donovanmuller** [comment]
For posterity, as replied by @EricWittmann from the [mailing list](https://lists.jboss.org/mailman/listinfo/apiman-user):

> There's no way to *disable* it - but you can simply delete the
> deployment.  For example:
> 
> rm -f
> ~/apiman-1.2.6.Final/wildfly-10.0.0.Final/standalone/deployments/apiman-es.*
> 
> Basically there is a simple WAR file that bundles up and deploys the
> embedded ES instance called "apiman-es.war".  Delete it and you're good
> to go.
