### ISSUE TITLE
Error trying to delete plan with multiple versions

### ISSUE THREAD

**Issue by donovanmuller** [apiman/apiman#478]
Using 1.2.5 and given two versions of the `default` plan, when I try deleting the plan:

![screen shot 2016-05-19 at 10 38 29 am](https://cloud.githubusercontent.com/assets/1175891/15388172/e6201c4a-1db0-11e6-8182-40150aa48937.png)

![screen shot 2016-05-19 at 10 38 43 am](https://cloud.githubusercontent.com/assets/1175891/15388175/ecfc0376-1db0-11e6-87d5-115cce61343c.png)

I get and error that something already exists:

![screen shot 2016-05-19 at 10 38 50 am](https://cloud.githubusercontent.com/assets/1175891/15388192/0155938c-1db1-11e6-9d82-a20c6125a958.png)

As a side note, what I actually wanted to do was delete the latest unlocked *version*, however, this doesn't seem possible (should it be?).
It is also worth mentioning that this was using the `es` storage type for API Manager (perhaps related to #477)

**Comment by EricWittmann** [comment]
Thanks for the report.

I've logged this bug here:  https://issues.jboss.org/browse/APIMAN-1152

Feel free to watch the JIRA issue for changes. :)
