### ISSUE TITLE
Using Apiman behind Nginx proxy

### ISSUE THREAD

**Issue by ploef** [apiman/apiman#495]
Hi,

Did anybody got Apiman working behind a Nginx proxy? Like this:

```
 location /apiman {
        proxy_pass http://localhost:8080;
        proxy_set_header  Host $host;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

So not on the root of the server.
Above configuration gives me a 404 on /apiman/apimanui (and probably all other endpoints).

Regards,
Peter

**Comment by EricWittmann** [comment]
I'm afraid I don't know of anyone who has used nginx in front of apiman.
