### ISSUE TITLE
Incorrect latest version on website

### ISSUE THREAD

**Issue by kevto** [apiman/apiman#663]
Hi!

Just noticed a minor issue (probably forgotten) on the website of apiman. If you hover over the "Latest" navbar button, it shows the deprecated 1.1.x version of apiman and not 1.3.5 or 1.3.x. Screenshot added below.

![afbeelding](https://user-images.githubusercontent.com/10073027/40771463-acb603a6-64bd-11e8-8e5e-f3dba0468e8e.png)

**Comment by msavy** [comment]
Hmm, I'll think about how I can make it less confusing.

**Comment by bekihm** [comment]
@EricWittmann I think this is also solved? :-)

**Comment by EricWittmann** [comment]
Closed by removing that dropdown entirely!
