### ISSUE TITLE
[Bug]TimeRestrictedAccessPolicy

### ISSUE THREAD

**Issue by MosesFu** [apiman/apiman#664]
Hi,

The method of **TimeRestrictedAccessPolicy** named **matchesDay** has a judgemental problem. Which in lines number 161, origin code `return dayNow <= dayEnd && dayNow <= dayStart;`, should change to `return dayNow <= dayEnd && dayNow >= dayStart;`.

**Comment by msavy** [comment]
Could you make a PR for this?
