### ISSUE TITLE
APIMan does not handle PATCH verb on Authorization Policy

### ISSUE THREAD

**Issue by SebastienDr** [apiman/apiman#705]
While trying to setup some policies on our webservices through apiman, we found out that it does not seem to handle PATCH method (ie link).
I tried to dig in documentation but there does not seem to be anything about that. 
Is there a workaround for this, like using POST mapping or else or am i missing something ?
![apiman](https://user-images.githubusercontent.com/1300673/43906597-f4601846-9bf3-11e8-9634-19d450c5969b.png)

**Comment by msavy** [comment]
This is a bug. Will fix it.

**Comment by msavy** [comment]
Bug in the "clear omission" sense.
