### ISSUE TITLE
Ability to switch on/off debugging at runtime without outage

### ISSUE THREAD

**Issue by kvbanantha** [apiman/apiman#727]
I tried to set the log level in the console, but some how I found there is a log level at standalone-apiman.xml, would like to know if we can change log level dynamically at runtime with out restarting the server?

**Comment by msavy** [comment]
This is not possible, I don't think

**Comment by EricWittmann** [comment]
This could be a feature request though.  We have an open PR in Apicurio Registry that does this: 

https://github.com/Apicurio/apicurio-registry/pull/1107

**Comment by msavy** [comment]
Good point, Eric. Perhaps we should have a think about it; let's stick it
on the backlog.
