### ISSUE TITLE
Improve Caching Policy including HTTP method and path pattern

### ISSUE THREAD

**Issue by bekihm** [apiman/apiman#737]
Hello @EricWittmann ,
We have a first in progress prototype for a caching policy which meets our requirements.  You can restrict the caching with this policy to some path resources, http methods and status codes. Unlike the old caching policy, which caches all replies from the time the policy was created, no caching is performed by default.
The old policy cached all responses by default without care about http methods and path resources.  We can use wildcards for http methods and path resources to support the old behavior.
![2019-06-04 10_33_15-API Management - Edit Policy](https://user-images.githubusercontent.com/33115480/58869192-08bca600-86be-11e9-9062-613904843844.png)

We are looking forward to your opinion.
Kind regards
Benjamin Kihm

**Comment by EricWittmann** [comment]
These look like nice additions to caching - did you create your own separate custom policy, or did you modify the existing caching policy?

**Comment by bekihm** [comment]
In fact, I have adapted the existing one.
That means we have modified the CachingConfig class which is serialized. So there is the need to migrate already existing data of the old policy.

**Comment by EricWittmann** [comment]
In that case it would perhaps be easier to duplicate the caching policy instead?

**Comment by bekihm** [comment]
We thought about it. The migration of the old caching policy to our new one would be ugly to implement. The new policy works also very different to the old caching. So we will deliver it as a new policy named "Caching Resources" and may mark the old caching policy as deprecated.

**Comment by bekihm** [comment]
@EricWittmann Today I will prepare a PR to cache POST requests concerning their payload (https://github.com/apiman/apiman/pull/746#issuecomment-513747780). I think then we can close this issue.

**Comment by EricWittmann** [comment]
Now that your PR was merged, should this be closed?
