### ISSUE TITLE
Que: ES Cluster support in APIMan

### ISSUE THREAD

**Issue by ashishkp** [apiman/apiman#740]
How to configure APIMan to point to ES Cluster of 3 nodes means 3 IPs/hostnames ? 

Does `apiman.es.host` accept multiple IPs/hostnames ?

**Comment by EricWittmann** [comment]
No - that property does not support multiple IPs/hostnames.  Are you sure that's necessary?

While I don't know much about clustering ES, I would be surprised if the client were required to know about all of the nodes in the ES cluster.  Rather, I would expect that the client would only need to know about one of the nodes (or more likely a load balancer that balances traffic across the ES cluster nodes).

So my expectation would be that clients always only connect to a single IP/domain and ES does the rest.

**Comment by ashishkp** [comment]
Thanks Eric for a quick answer.

Yeah, already checked possibilities of HAProxy in front of ES Cluster - however read mixed reviews - i.e [elastic-search-cluster-active-passive](https://discuss.elastic.co/t/elastic-search-cluster-active-passive/144693)

Just wanted to know the support in APIMan - as it's not there (rightly so) - will figure out HA need through ES Team.
