### ISSUE TITLE
Problems with keycloak oauth plugin and postgres database

### ISSUE THREAD

**Issue by knottnhupfer** [apiman/apiman#754]
Hi,

we observed and reproduced a really strange behavior using PostgreSQL in combination with the keycloak oauth authentication plugin. As soon as we configure postgres as apiman-manager database and install the "keycloak-oauth-policy" policy any time we open the plugin editor we double the entries of this plugin in the table "pd_templates". After reaching a really high number of duplicated entries the application is not able to handle it anymore and from that point in time we are not able to open the policies in the UI or publish them.
 
I followed more or less the chapter 7.2.2 from http://www.apiman.io/latest/production-guide.html except the datasource configuration has been moved inside standalone-apiman.conf (needed that to evaluate environment properties). I also tried a newer postgres driver without any change.

I created a small docker-compose demo which can be downloaded [here](https://drive.google.com/file/d/1bvivdHRv-LI-syo18uGdakgT_Jbu-JY1/view?usp=sharing)

After starting the demo with:

docker-compose up --build

- Login into apiman and install the "Keycloak OAuth Policy Plugin" plugin.
- Connect to the local exposed postgres database "apiman_manager" on localhost:5432 with user "apiman" and password "apiman" and execute following select query:
`SELECT * FROM pd_templates WHERE policydef_id = 'keycloak-oauth-policy';`
The result should be a single entry.
- Create a new organization and API.
- Go to "Add Policy" and choose "Keycloak OAuth Policy" so that the plugin configuration page opens.
- Again fetch the entries of the database with:
`SELECT * FROM pd_templates WHERE policydef_id = 'keycloak-oauth-policy';`
- Any time this editor is opened the entries are doubled in the database.

Any idea about the cause of such a behaviour?

Thx for any help

best

/david

**Comment by EricWittmann** [comment]
I'll have to dig into this one.  I have no idea offhand why something like that would happen.  Unless @msavy has any ideas. :)

**Comment by msavy** [comment]
Hmm, no idea at all. Wonder if it's Liquibase-related.

**Comment by EricWittmann** [comment]
I'll dig into it when I get a chance... :(

**Comment by knottnhupfer** [comment]
@EricWittmann thx a lot, if you need any help pls let me.

If I detect something I'll let u know ...

best

/david

**Comment by EricWittmann** [comment]
No problem.  Unfortunately I'm traveling for awhile without access to my centos box (only have a personal laptop with me) so I won't be able to test using your docker compose reproducer.  Once I get back I will do that.  For now I will have a look at the code to see if anything stands out, and try to reproduce using some other setup.

**Comment by EricWittmann** [comment]
I've had a few minutes to look into this and have a bit of information.  Note that this sort of thing is why I don't like using JPA very much.  When the user selects **Keycloak OAuth Policy** from the **Policy Type** dropdown on that page, the following (relevant) code is executed:

```
entityManager.find(PluginBean.class, pluginId);
entityManager.find(PolicyDefinitionBean.class, pluginId);
```

These are obviously purely QUERY operations, but this is the SQL that hibernate executes:

```
14:53:55,460 INFO  [stdout] (default task-115) Hibernate:
14:53:55,460 INFO  [stdout] (default task-115)     select
14:53:55,461 INFO  [stdout] (default task-115)         pluginbean0_.id as id1_18_0_,
14:53:55,461 INFO  [stdout] (default task-115)         pluginbean0_.artifact_id as artifact2_18_0_,
14:53:55,461 INFO  [stdout] (default task-115)         pluginbean0_.classifier as classifi3_18_0_,
14:53:55,461 INFO  [stdout] (default task-115)         pluginbean0_.created_by as created_4_18_0_,
14:53:55,461 INFO  [stdout] (default task-115)         pluginbean0_.created_on as created_5_18_0_,
14:53:55,461 INFO  [stdout] (default task-115)         pluginbean0_.deleted as deleted6_18_0_,
14:53:55,461 INFO  [stdout] (default task-115)         pluginbean0_.description as descript7_18_0_,
14:53:55,461 INFO  [stdout] (default task-115)         pluginbean0_.group_id as group_id8_18_0_,
14:53:55,461 INFO  [stdout] (default task-115)         pluginbean0_.name as name9_18_0_,
14:53:55,461 INFO  [stdout] (default task-115)         pluginbean0_.type as type10_18_0_,
14:53:55,461 INFO  [stdout] (default task-115)         pluginbean0_.version as version11_18_0_
14:53:55,461 INFO  [stdout] (default task-115)     from
14:53:55,461 INFO  [stdout] (default task-115)         plugins pluginbean0_
14:53:55,461 INFO  [stdout] (default task-115)     where
14:53:55,461 INFO  [stdout] (default task-115)         pluginbean0_.id=?
14:53:55,462 INFO  [stdout] (default task-116) Hibernate:
14:53:55,462 INFO  [stdout] (default task-116)     select
14:53:55,462 INFO  [stdout] (default task-116)         pluginbean0_.id as id1_18_0_,
14:53:55,462 INFO  [stdout] (default task-116)         pluginbean0_.artifact_id as artifact2_18_0_,
14:53:55,462 INFO  [stdout] (default task-116)         pluginbean0_.classifier as classifi3_18_0_,
14:53:55,462 INFO  [stdout] (default task-116)         pluginbean0_.created_by as created_4_18_0_,
14:53:55,462 INFO  [stdout] (default task-116)         pluginbean0_.created_on as created_5_18_0_,
14:53:55,462 INFO  [stdout] (default task-116)         pluginbean0_.deleted as deleted6_18_0_,
14:53:55,462 INFO  [stdout] (default task-116)         pluginbean0_.description as descript7_18_0_,
14:53:55,462 INFO  [stdout] (default task-116)         pluginbean0_.group_id as group_id8_18_0_,
14:53:55,462 INFO  [stdout] (default task-116)         pluginbean0_.name as name9_18_0_,
14:53:55,462 INFO  [stdout] (default task-116)         pluginbean0_.type as type10_18_0_,
14:53:55,462 INFO  [stdout] (default task-116)         pluginbean0_.version as version11_18_0_
14:53:55,462 INFO  [stdout] (default task-116)     from
14:53:55,462 INFO  [stdout] (default task-116)         plugins pluginbean0_
14:53:55,462 INFO  [stdout] (default task-116)     where
14:53:55,462 INFO  [stdout] (default task-116)         pluginbean0_.id=?
14:53:55,463 INFO  [stdout] (default task-115) Hibernate:
14:53:55,463 INFO  [stdout] (default task-115)     select
14:53:55,463 INFO  [stdout] (default task-115)         policydefi0_.id as id1_20_0_,
14:53:55,463 INFO  [stdout] (default task-115)         policydefi0_.deleted as deleted2_20_0_,
14:53:55,463 INFO  [stdout] (default task-115)         policydefi0_.description as descript3_20_0_,
14:53:55,463 INFO  [stdout] (default task-115)         policydefi0_.form as form4_20_0_,
14:53:55,463 INFO  [stdout] (default task-115)         policydefi0_.form_type as form_typ5_20_0_,
14:53:55,463 INFO  [stdout] (default task-115)         policydefi0_.icon as icon6_20_0_,
14:53:55,463 INFO  [stdout] (default task-115)         policydefi0_.name as name7_20_0_,
14:53:55,463 INFO  [stdout] (default task-115)         policydefi0_.plugin_id as plugin_i8_20_0_,
14:53:55,463 INFO  [stdout] (default task-115)         policydefi0_.policy_impl as policy_i9_20_0_,
14:53:55,463 INFO  [stdout] (default task-115)         templates1_.policydef_id as policyde1_14_1_,
14:53:55,463 INFO  [stdout] (default task-115)         templates1_.language as language2_14_1_,
14:53:55,464 INFO  [stdout] (default task-115)         templates1_.template as template3_14_1_
14:53:55,476 INFO  [stdout] (default task-115)     from
14:53:55,476 INFO  [stdout] (default task-115)         policydefs policydefi0_
14:53:55,476 INFO  [stdout] (default task-115)     left outer join
14:53:55,476 INFO  [stdout] (default task-115)         pd_templates templates1_
14:53:55,476 INFO  [stdout] (default task-115)             on policydefi0_.id=templates1_.policydef_id
14:53:55,476 INFO  [stdout] (default task-115)     where
14:53:55,476 INFO  [stdout] (default task-115)         policydefi0_.id=?
14:53:55,477 INFO  [stdout] (default task-116) Hibernate:
14:53:55,477 INFO  [stdout] (default task-116)     select
14:53:55,477 INFO  [stdout] (default task-116)         policydefi0_.id as id1_20_0_,
14:53:55,477 INFO  [stdout] (default task-116)         policydefi0_.deleted as deleted2_20_0_,
14:53:55,477 INFO  [stdout] (default task-116)         policydefi0_.description as descript3_20_0_,
14:53:55,477 INFO  [stdout] (default task-116)         policydefi0_.form as form4_20_0_,
14:53:55,477 INFO  [stdout] (default task-116)         policydefi0_.form_type as form_typ5_20_0_,
14:53:55,477 INFO  [stdout] (default task-116)         policydefi0_.icon as icon6_20_0_,
14:53:55,477 INFO  [stdout] (default task-116)         policydefi0_.name as name7_20_0_,
14:53:55,477 INFO  [stdout] (default task-116)         policydefi0_.plugin_id as plugin_i8_20_0_,
14:53:55,477 INFO  [stdout] (default task-116)         policydefi0_.policy_impl as policy_i9_20_0_,
14:53:55,477 INFO  [stdout] (default task-116)         templates1_.policydef_id as policyde1_14_1_,
14:53:55,477 INFO  [stdout] (default task-116)         templates1_.language as language2_14_1_,
14:53:55,477 INFO  [stdout] (default task-116)         templates1_.template as template3_14_1_
14:53:55,477 INFO  [stdout] (default task-116)     from
14:53:55,477 INFO  [stdout] (default task-116)         policydefs policydefi0_
14:53:55,477 INFO  [stdout] (default task-116)     left outer join
14:53:55,477 INFO  [stdout] (default task-116)         pd_templates templates1_
14:53:55,477 INFO  [stdout] (default task-116)             on policydefi0_.id=templates1_.policydef_id
14:53:55,477 INFO  [stdout] (default task-116)     where
14:53:55,477 INFO  [stdout] (default task-116)         policydefi0_.id=?
14:53:55,480 INFO  [stdout] (default task-115) Hibernate:
14:53:55,480 INFO  [stdout] (default task-115)     delete
14:53:55,480 INFO  [stdout] (default task-115)     from
14:53:55,480 INFO  [stdout] (default task-115)         pd_templates
14:53:55,480 INFO  [stdout] (default task-115)     where
14:53:55,480 INFO  [stdout] (default task-115)         policydef_id=?
14:53:55,482 INFO  [stdout] (default task-116) Hibernate:
14:53:55,482 INFO  [stdout] (default task-116)     delete
14:53:55,482 INFO  [stdout] (default task-116)     from
14:53:55,482 INFO  [stdout] (default task-116)         pd_templates
14:53:55,482 INFO  [stdout] (default task-116)     where
14:53:55,482 INFO  [stdout] (default task-116)         policydef_id=?
14:53:55,482 INFO  [stdout] (default task-115) Hibernate:
14:53:55,482 INFO  [stdout] (default task-115)     insert
14:53:55,482 INFO  [stdout] (default task-115)     into
14:53:55,482 INFO  [stdout] (default task-115)         pd_templates
14:53:55,482 INFO  [stdout] (default task-115)         (policydef_id, language, template)
14:53:55,482 INFO  [stdout] (default task-115)     values
14:53:55,482 INFO  [stdout] (default task-115)         (?, ?, ?)
14:53:55,492 INFO  [stdout] (default task-116) Hibernate:
14:53:55,492 INFO  [stdout] (default task-116)     insert
14:53:55,492 INFO  [stdout] (default task-116)     into
14:53:55,492 INFO  [stdout] (default task-116)         pd_templates
14:53:55,492 INFO  [stdout] (default task-116)         (policydef_id, language, template)
14:53:55,492 INFO  [stdout] (default task-116)     values
14:53:55,492 INFO  [stdout] (default task-116)         (?, ?, ?)
```

Why everything twice?  I don't know, maybe just a logging artifact?

Why deletes and inserts?  I don't know.

The SQL looks **ok** (I guess) if you assume that the INSERTS are supposed to replace whatever was DELETEd prior.  Perhaps that's not working in postgres?  Again I don't know.

I will change the code to rollback the Tx being used for these queries (rather than committing the Tx as we're doing now) and perhaps that will solve the issue... :(

**Comment by knottnhupfer** [comment]
@EricWittmann thx a lot for your help and fix

The delete and insert looks very interesting, will have a look asap and let you know.

**Comment by EricWittmann** [comment]
Changing the code from a `commit()` to a `rollback()` definitely prevented the extra DELETE and INSERT statements, so I think it's appropriate.  You'll have to give it a test and let me know. :)  If it works, I guess I should consider making the same change for all read-only operations.

**Comment by knottnhupfer** [comment]
Unfortunately with the latest docker image "apiman/on-wildfly11:master" the keycloak plugin editor is not loading at all in this docker-compose environment.

![image](https://user-images.githubusercontent.com/33702886/64861316-e973d400-d62f-11e9-9f48-a0b4a6c52a66.png)

I also can't see any error message in the console. It surprised me a little bit that most plugins are pre-installed. Not sure if this is a master/version feature or something else is responsible for it.

**Comment by EricWittmann** [comment]
The pre-installed thing I can't explain (although I did see that in my local environment as well).  Try uninstalling them all and then re-installing just the Keycloak one. :(

**Comment by msavy** [comment]
Can you look in the networks tab when the request happens to see if there's
anything funny in there? For example, a CORS failure or similar? Typically
those are in the console, but worth having a look.

**Comment by knottnhupfer** [comment]
Hi Eric,
sorry for my late reply, have been in vacation ;)
So finally I verified your changes in 1.5.3-SNAHOST, git-hash: 13ffd8e4f4dd98a23ed12f3c862e9ae40f660910

Replaced apiman.war and apimanui.war in docker image "apiman/on-wildfly11:1.5.1.Final" and the entries are not reduplicated anymore. Problem is fixed!

Thx a lot.

**Comment by knottnhupfer** [comment]
Hi Eric,

just to organize our time schedule in the next weeks, is there a release plan for 1.5.3.Final? Would be really helpful so that we can update our installation to a final release.

best

/david

**Comment by EricWittmann** [comment]
Releases are pretty much now done at the request of the community.  So we can definitely do a release of 1.5.3.Final whenever we feel it's the right time.

**Comment by knottnhupfer** [comment]
Hi, would it be possible to have a new release 1.5.3.Final within the next 1 to 2 weeks? Would be really useful for us. Or are there some bug fixes/features we should wait for?

**Comment by EricWittmann** [comment]
Yes for sure we can do that.  @volkflo @msavy any issues with that?

**Comment by volkflo** [comment]
No concerns from our side :)

**Comment by EricWittmann** [comment]
OK I'll do an apiman release on Monday Nov 11 then.

**Comment by EricWittmann** [comment]
Release is done.  FYI
