### ISSUE TITLE
is there any way to enable idle connection reaping for jest client

### ISSUE THREAD

**Issue by arunabh123** [apiman/apiman#757]
Hi, 
I am getting socket time outs intermittently. might be due to idle connections staying alive for too long.
is there a way to enable idle connection reaping as provided in jest client(using the option maxConnectionIdleTime) using some configuration.

Thanks in advance

**Comment by EricWittmann** [comment]
Is this happening in the Gateway or the Manager?

**Comment by EricWittmann** [comment]
It looks like the answer to your question is "no" unfortunately.  The code that creates the Jest client is here:

https://github.com/apiman/apiman/blob/master/common/es/src/main/java/io/apiman/common/es/util/DefaultEsClientFactory.java#L69-L126

The good news is that it would be rather trivial to add support for that.  Perhaps you'd be interested in creating a PR for it?  :)

**Comment by arunabh123** [comment]
> Is this happening in the Gateway or the Manager?

it happening in the manager

**Comment by arunabh123** [comment]
> It looks like the answer to your question is "no" unfortunately. The code that creates the Jest client is here:
> 
> https://github.com/apiman/apiman/blob/master/common/es/src/main/java/io/apiman/common/es/util/DefaultEsClientFactory.java#L69-L126
> 
> The good news is that it would be rather trivial to add support for that. Perhaps you'd be interested in creating a PR for it? :)

Thanks for the prompt reply ..

can I extend this class and probably override the method to write my own implementation? Im using 1.3.1Final

**Comment by bekihm** [comment]
Hello @arunabh123, 
you may have not to overwrite the whole function, you can add in line 77 the reading of the config:
` Boolean maxConnectionIdleTime = NumberUtils.toInt(config.get("client.maxConnectionIdleTime", 1000),); //$NON-NLS-1$`
And set the option in the client in line 102
`.maxConnectionIdleTime(maxConnectionIdleTime);`

**Comment by EricWittmann** [comment]
Exactly right - just modify the method directly to add the new functionality.  Steps to submit a PR:

1. Fork the apiman repository
2. Clone the forked repository
3. Create a new branch (git checkout -b support-idle-conn-reaping)
4. Add the code suggested by @bekihm  to the `createJestClient` method
5. Commit and push your changes to the branch
6. Go to github.com and submit a PR

Sorry if all that was obvious.  In any case - such a contribution would be most welcome!

**Comment by arunabh123** [comment]
Thanks guys for the help , will submit a PR for this.

**Comment by arunabh123** [comment]
added a PR https://github.com/apiman/apiman/pull/761

**Comment by EricWittmann** [comment]
Closed by https://github.com/apiman/apiman/pull/761

Thanks for the contribution.
