### ISSUE TITLE
Where can I find the API Key?

### ISSUE THREAD

**Issue by geertschuring** [apiman/apiman#774]
The documentation reads as follows: "When an API Contract is created, the system generates a unique API key specific to that contract."
https://apiman.gitbooks.io/apiman-user-guide/user-guide/manager/concepts.html#_providing_apis

I can't find any generated API Key in the web admin console. Am I looking in he wrong place?

**Comment by volkflo** [comment]
You can check the crash course:
 
http://www.apiman.io/latest/crash-course.html#_section_4_consuming_apis

![image](https://user-images.githubusercontent.com/13332383/68945908-d7d6b600-07b1-11ea-9bff-99e3c81f0a0e.png)
![image](https://user-images.githubusercontent.com/13332383/68945935-e3c27800-07b1-11ea-8890-f983bbbaf6dd.png)

**Comment by geertschuring** [comment]
Thanks for the swift reply. However, the crash course says: "https://localhost:8443/apiman-gateway/Prorail/PTICOM/1.0". This is not the case in the most recent version of apiman. (1.5.4 on Wildfly11)

This is what the admin console shows:
![Missing API Key](https://user-images.githubusercontent.com/598355/68946508-731c5b00-07b3-11ea-9d3c-2d00f1de3a19.png)

When I press "Copy endpoint" there is no Key included.

**Comment by volkflo** [comment]
You looking at the API page but for an API Key is located on the Client App page.

You need a contract via a plan to you client app. If you register the client app there will be a new tab called "APIs" on the client app (look carefully at the screenshots).

**Comment by geertschuring** [comment]
Ah I see. Thanks!
