### ISSUE TITLE
Maven-Enforcer-Plugin

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#776]
Hi @EricWittmann 

I saw that you disabled the maven-enforcer-plugin in this [commit](https://github.com/apiman/apiman/commit/53029707f24fe98d73741eb88a51dffcc0506728).

I tried to upgrade the whole enforcer-plugin, but this did not worked either.
Also the "illegal-transitive-dependency-check" wasn't updated the last 4 years by their maintainers.

Maybe it would be better to remove the whole thing instead of disabling it.

What do you think?

Regards
Florian :)

**Comment by EricWittmann** [comment]
Yes +1 to removing it!

**Comment by volkflo** [comment]
Will you do this or should I provide a PR?

**Comment by msavy** [comment]
+1

**Comment by EricWittmann** [comment]
If you have time soon to do it, that's great.  I probably can't get to it until Friday.

**Comment by volkflo** [comment]
Closed due to https://github.com/apiman/apiman/pull/777
