### ISSUE TITLE
Manager UI - Applying security updates on Javascripts libraries

### ISSUE THREAD

**Issue by jhauray** [apiman/apiman#783]
A recent security audit on our Apiman deployment reported vulnerabilities that I would like to share with you.

Javascripts libraries are not up-to-date :
- jQuery : v2.1.4.
- angularjs :  v1.4.7.
- bootstrap : v3.3.5.

It could be interesting to update them. At least to last minor security updates. Upgrade to last major versions could require a lot of rework

Proposal :
- jQuery : v2.2.4.
- angularjs :  v1.4.9.
- bootstrap : v3.3.7, or if possible v3.4.1

I see that dependabot already try to update angularjs : #781

**Comment by EricWittmann** [comment]
Those proposed versions are likely OK.  We definitely can't upgrade Angular to the latest major.  That would be a total re-write of the UI.  Same with bootstrap and probably jQuery as well, although jQuery is only used as part of Bootstrap I believe.

**Comment by volkflo** [comment]
Marc already tried to update angular and this caused an issue. See: https://issues.jboss.org/browse/APIMAN-1302

In our fork we modified the UI and we using jQuery 3.3.1 without problems.

**Comment by EricWittmann** [comment]
Right but it looks like Marc tried to go to Angular 1.6 - the suggestion above is just to bump it up by a couple of patch versions to 1.4.9.

Interesting information about jQuery!

@volkflo have you also upgraded Bootstrap?  I'm guessing we could go to 3.4.1 without any trouble.

**Comment by msavy** [comment]
If thorough testing is done I have no objection.

The angular one is highly problematic in my experience as it requires other
dep updates that can cause mysterious failures.

Feel free to give it a crack though.

I think the other deps are much lower risk, but a full sweep of UI is still
needed as it can cause very weird glitches.

**Comment by EricWittmann** [comment]
I guess then, @jhauray would you be able to give the UI a sweep to make sure there aren't any problems?

**Comment by volkflo** [comment]
@EricWittmann Did you mean the angular-ui-bootstrap or the bundled one with patternfly?

I looked it up:
We updated patternfly as well to 3.43.0 inlcluding bootstrap 3.3.7. There are no problems for our fork, but I have no clue how this could affect the original apiman design

**Comment by jhauray** [comment]
> I guess then, @jhauray would you be able to give the UI a sweep to make sure there aren't any problems?

@EricWittmann I don't know. I'm looking for some free time to do it. I will try to do the upgrades only if I could do a full sweep.

If somebody who knows Apiman UI well could help me to, it could be nice.

**Comment by EricWittmann** [comment]
I can give it a try when I have some time.  Unfortunately we do not have UI tests (e.g. selenium) for apiman, so the only way to make sure everything is working is by manual testing.  That said, the proposed version upgrades are, in my opinion, pretty low-risk.

@volkflo Thanks for the info - I forgot that Bootstrap was being bundled with Patternfly.  We'll need to upgrade both of those (patternfly and bootstrap).

**Comment by msavy** [comment]
This has been resolved in 3.x
