### ISSUE TITLE
Manager REST API - Securing CORS by checking Origin

### ISSUE THREAD

**Issue by jhauray** [apiman/apiman#784]
A recent security audit on our Apiman deployment reported vulnerabilities that I would like to share with you.

Manager REST API accept CORS requests without any controls on origin. All requests are allowed.

An example : A POST request to create an organization via manager api with a **faked Origin header** :
![Apiman - manager api cors attack](https://user-images.githubusercontent.com/42616019/70238352-6911ca80-1769-11ea-8921-f0c11453b0b1.png)

We can see in [ApimanCorsFilter.java](https://github.com/apiman/apiman/blob/master/common/servlet/src/main/java/io/apiman/common/servlet/ApimanCorsFilter.java) that Origin header is automatically return in "Access-Control-Allow-Origin".

Proposal :
Check that the Origin present in the http header belongs to a list of authorized domains. This list must be configurable.

This could be done with minimal changes inspired by this Github filter project : [eBay/cors-filter](https://github.com/eBay/cors-filter). It covert all CORS uses cases, including Origin checking. And when a request is invalid, replying with an HTTP 403 error code.

Filter implementation has advantage to be compatible with Tomcat and WildFly. Otherwise, maybe with JAX-RS ContainerResponseFilter.

**Comment by rp-intm** [comment]
Hello maintainers,

Have you already started working on this? I'm considering contributing for this issue, I just want to avoid double work :)

If not, what's your opinion on @jhauray suggestion to rely on https://github.com/eBay/cors-filter?

Also, do you any suggestion on your side for a better pull request?

**Comment by volkflo** [comment]
Hi @rp-intm,

as far as I knew there is no one working on this at the moment. 
But I think these improvements would be good to have :)

I just looked a little bit over https://github.com/eBay/cors-filter but the GitHub project is achieved and that means the project is pretty dead (also the last changes are 4 years ago).
So personally I would not recommend to include a dead project.

I think it is we could start with replacing this block:
https://github.com/apiman/apiman/blob/f96e517b8bf9a523b05a5cf5f7b89877e7b067ad/common/servlet/src/main/java/io/apiman/common/servlet/ApimanCorsFilter.java#L58-L70
with fixed allowed cors origin from a system property instead of reading it from the request.

Also @tevosouza, @bekihm what would you think about this?

**Comment by bekihm** [comment]
@rp-intm what would be your suggestion to solve this issue? Would you implement it completely by your own or would you depend on the project dependency of the ebay cors-filter project?

**Comment by EricWittmann** [comment]
I definitely agree that depending on an archived project seems like a bad choice.  :)

**Comment by rp-intm** [comment]
> as far as I knew there is no one working on this at the moment.

OK good to know!
 
> I just looked a little bit over https://github.com/eBay/cors-filter but the GitHub project is achieved and that means the project is pretty dead (also the last changes are 4 years ago).
> So personally I would not recommend to include a dead project.

> I definitely agree that depending on an archived project seems like a bad choice. :)

Of course, it seems fair :+1:

> I think we could start with replacing this block:
> 
> https://github.com/apiman/apiman/blob/f96e517b8bf9a523b05a5cf5f7b89877e7b067ad/common/servlet/src/main/java/io/apiman/common/servlet/ApimanCorsFilter.java#L58-L70
> 
> with fixed allowed cors origin from a system property instead of reading it from the request.

Thanks for the hint!

**Comment by jhauray** [comment]
Hi all,

[eBay/cors-filter](https://github.com/eBay/cors-filter) was just an example of existing CORS filters to help with the implementation. I found it interesting because it covered all classic CORS use cases. But as you see, it is pretty dead. So, **It should therefore not be included**.

I agree with @volkflo proposal : **Just fix the vulnerability by replacing** "Access-Control-Allow-Origin" value in response header, with a setting from system properties, that contain predefined allowed origins.

No need to create a new feature. Just fix **doFilter** method in existing [ApimanCorsFilter.java](https://github.com/apiman/apiman/blob/master/common/servlet/src/main/java/io/apiman/common/servlet/ApimanCorsFilter.java) : replace values in lines `httpResp.setHeader("Access-Control-Allow-Origin", <value_from_system_properties>); `

I recommend to consider a string array parameters, as this header could contains a space separated list (see https://www.w3.org/TR/cors/#access-control-allow-origin-response-header).

Sorry, but I don't have enough free time to contribute and propose a pull request. But maybe @rp-intm could do it.

**Comment by tevosouza** [comment]
I agree with @volkflo proposal too and I think that is an elegant and quite simple way to resolve this vulnerability

**Comment by rp-intm** [comment]
Any suggestion for the system property name?

**Comment by volkflo** [comment]
I would go with "allowed-cors-origins" or in the apiman.properties files with `apiman-manager-ui.allowed-cors-origins`
