### ISSUE TITLE
Miredot License has expired

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#787]
Hey all, 

I wanted to build the API REST documentation locally with the maven miredot plugin (maven profile "apidocs") but the license is expired:
> License key expired on 16 Feb 2018

Is there any chance that somebody can renew this and/or switch to the newest version? 

Regards
Florian

**Comment by bekihm** [comment]
We want to refactor the REST resources to check that we have no other security issues. The update of the Miredot License would be very helpful to check all possible REST resources.

@EricWittmann @msavy Can someone of you update the license please? :-)

Thank you :-)
Benjamin

**Comment by EricWittmann** [comment]
Sorry I saw this when it was posted and forgot about it.  I'll see what I can do on this.  Hopefully won't be a problem.

**Comment by msavy** [comment]
Hey @DenEwout I recall you setting us up with a new open source license for MireDot some time back #398 

If you could help us out again that would be fantastic 😄

**Comment by EricWittmann** [comment]
I just got word back from miredot.  Here are the new licenses:

For **io.apiman / apiman-manager-api-rest**:

```
cHJvamVjdHxpby5hcGltYW4uYXBpbWFuLW1hbmFnZXItYXBpLXJlc3R8MjAyMy0wMS0zMXxmYWxzZXwtMSNNQ3dDRkJlbVhWb2dLTk5CYXlkNm9GVUZ6amNNQjc3REFoUUloTUxvVkovY0pyNERVM1c1V0h1WVhSaTl0QT09
```

For **io.apiman / apiman- gateway -api-rest**:

```
cHJvamVjdHxpby5hcGltYW4uYXBpbWFuLWdhdGV3YXktYXBpLXJlc3R8MjAyMy0wMS0zMXxmYWxzZXwtMSNNQ3dDRkh2ZU5RbmNWUzFZK1R1UWFYNWc2L1l0MDRldkFoUUN5aXFJKzNMNFEwQXVoTlI2MVc0alNldmY5UT09
```

@volkflo and/or @bekihm - can you give these a try and then submit a PR if they work?

**Comment by volkflo** [comment]
Thanks! I'll probably try it out tomorrow and get back to you or open a PR directly :)
