### ISSUE TITLE
Support Java 11+

### ISSUE THREAD

**Issue by EricWittmann** [apiman/apiman#796]
Right now I think we're stuck on Java 8.  Let's make sure we can build and run using Java 11!

**Comment by msavy** [comment]
I'll take a look at this, as I had to do something similar recently.

**Comment by msavy** [comment]
This is going to take a bit longer than I hoped as some transitive dependencies (Apache LDAP related stuff) required major version upgrades and initialisation is more complex than it was before. Debugging a few issues relating to LDAP/LDIF as default behaviour seems to have changed.

Will provide an update here soon.

**Comment by msavy** [comment]
Argh, I accidentally blew all of this work away locally and it wasn't yet checked in.

So I will likely have to do it all again... 😭

**Comment by msavy** [comment]
Good news, I managed to find my WIP in a git stash.

I've had a close family issue I've been dealing with for the last while, so have not been doing any OSS work lately. I will try to continue work soon.

**Comment by phenompavan** [comment]
I'll try that. When can we expect 2.1.0 release? And also Java newer version support please?
