### ISSUE TITLE
Minor UI improvement

### ISSUE THREAD

**Issue by tevosouza** [apiman/apiman#803]
Hello guys!
What do you think about this kind of improvement? 
I'm developing pagination on the UI side for some lists that were returned by APIs.
![image](https://user-images.githubusercontent.com/58958299/73889120-aff56c80-484d-11ea-9468-e96538bc4cb6.png)

**Comment by volkflo** [comment]
Hey :)

this looks good, a while ago I used another workaround to get all Orgs/APIs not only the first 20.
I did a wildcard search and set the page size to 10000 if I remember that correctly.

See https://github.com/apiman/apiman/pull/668

Maybe this helps you, but I think your approach is the better one :)

**Comment by bekihm** [comment]
Looks like a very good improvement 👍

**Comment by tevosouza** [comment]
Hi!
> Looks like a very good improvement  I'm not sure if we need also an implementation for the backend side for huge data.
> Hey :)
> this looks good, a while ago I used another workaround to get all Orgs/APIs not only the first 20.
> I did a wildcard search and set the page size to 10000 if I remember that correctly.
> See #668
> Maybe this helps you, but I think your approach is the better one :)

@volkflo
I saw your PR and it was the trigger for my "pagination" idea..thanks for it!

> Looks like a very good improvement  I'm not sure if we need also an implementation for the backend side for huge data.
@bekihm, I agree with you, I think we no need to spend effort on it right now, maybe another time.

Well, I'll improve my code and make a new PR soon

**Comment by bekihm** [comment]
@tevosouza 
Here is the corresponding [Java 11 issue](https://github.com/apiman/apiman/issues/796).
@msavy has said there he is working on this but maybe you can report your problems there.

**Comment by tevosouza** [comment]
> @tevosouza
> Here is the corresponding [Java 11 issue](https://github.com/apiman/apiman/issues/796).
> @msavy has said there he is working on this but maybe you can report your problems there.

haha!
I'm "just" trying it and discovering how difficult it is. This is a job for apiman gurus .. LoL

**Comment by msavy** [comment]
Still working on it (Java 11), but due to personal life commitments (family
illness etc) I've not been able to spare much mental energy for Apiman.

I'll get back on it soon.

**Comment by tevosouza** [comment]
Hi @volkflo and @bekihm 
The first part of the 'pagination-project' is done!
I've made a pull request #806 with some adjustments, pagination and page size selection only on organization search, if the way that I've used is accepted I'll implement it on other pages and lists (if it fits).

**Comment by tevosouza** [comment]
Good evening!
@bekihm and @volkflo, what do you think about to send pagesize and currentpage on $location parameters.

ex.
http://localhost:2772/api-manager/browse/orgs?q=*&cp=1&ps=10

Is it a good idea?

**Comment by bekihm** [comment]
Hello @tevosouza,
I think this is a good idea 👍 Some thoughts about what happens if the user modifies this parameters to invalid numbers which does not exist?

Best wishes
Benjamin

**Comment by volkflo** [comment]
Hi @tevosouza 
Do you mean this in additions to the buttons of your last PR or instead of the dropdown and the page buttons?

**Comment by tevosouza** [comment]
> Hello @tevosouza,
> I think this is a good idea  Some thoughts about what happens if the user modifies this parameters to invalid numbers which does not exist?
> 
> Best wishes
> Benjamin

Thanks! I'll check these parameters calculating by if currentPage and pageSize are in the range using results.totalSize, if it is not, I'll override the value of the parameters setting it to max values.


> Hi @tevosouza
> Do you mean this in addition to the buttons of your last PR or instead of the dropdown and the page buttons?

Hi!
I intend to add this approach to my pull-request( #806 ) as we talked. I asked you and @bekihm to see if I'm on the correct way to implement it  but I'm worried about adding this logic to the controller and end up polluting, I'm trying to think of a way to modularize the pagination to reuse it in other pages

**Comment by volkflo** [comment]
Modularization sounds good for this! :)
