### ISSUE TITLE
Forward apikey query param to backend service

### ISSUE THREAD

**Issue by OSMOSA44** [apiman/apiman#812]
Hi,

I'm in trouble to forward a query param named "apikey" to a backend service,
Unfortunately, i cannot change the backend which expect this and only this named query param :0(

And i cannot use "URL Rewriting Policy" (i believe so) 

In ApiRequestExecutorImpl.java, it seems apikey & X-Api-Key are stripped before the plugins sequence,

A way to solve this issue could be to NOT strip apikey query param when its value doesn't match the X-Api-Key value,

Bref,

Is there a way to solve this issue via a custom plugin policy ?

Thanks,
Regards

Laurent from Nantes, France

**Comment by tevosouza** [comment]
Hi @ OSMOSA44
How are you?

I think that you have created a plan and a client (contract) before sending a request to your API that needs apikey.
Is there anything that blocks the use of simple header policy and adds a new header with apikey param with the value. 
If I understood your use case, you need to send the key for identification, that usually fixed by every client.

Is it correct?

**Comment by volkflo** [comment]
@OSMOSA44 The api-key (query param or header) is stripped before the policy chain applies. So I don't think you can use a custom policy for this. 

But I think the approach of @tevosouza should work. You can send you a special api key as a different header like Custom-API-Key and use the policy to extract this and step it to a header that matches your backend application.

**Comment by EricWittmann** [comment]
I guess the question is whether the `apikey` being sent is the one used by Apiman and if it is, why does it need to be sent to the backend?  That would be a very unusual thing for the backend to need.  Unless the backend needs some *other* apikey value (something not related to Apiman).  In that case, I agree that passing it some other way and using a policy to appropriately passing it down to the backend is correct.

**Comment by OSMOSA44** [comment]
**@tevosouza** Adding "?apikey=1237687as87167as1526" doesn't work :0(

https://support-clicrdv.force.com/s/article/Authentification-API?language=en_US

Above is the backend service i want to access and with which i cannot negotiate the protocol since it's multi-tenant and not in my organization,

As you can see, it accepts only the **apikey** (with no way to alternative name) via **param query only**

In the actual implementation, it's impossible to forward X-Api-Key nor apikey terms to a backend

Such suggestions:
* **on a Public API declaration** :

1. do not looking for any Api Key and let pass eventual X-Api-Key or apikey present in the client request through the gateway to the backend

* **on a Private API declaration (with contract and client)** : In order

1. if only X-Api-Key in header is present : it is the one for the api and we can strip it
2. if only apikey in query param is present : it is the one for the api and we can strip it
3. if both X-Api-Key and apikey are present :
-> Check first the X-Api-Key : 
if X-Api-Key doesn't match any client :
-> Check for apikey :
if apikey doesn't match any client
-> return error,
if one of them match a client : 
set ApiRequest.apiKey with the right value and strip it BUT don't touch those of them which is not for access the api.
if both match different clients or the same client : set ApiRequest.apiKey with X-Api-Key value and strip all of them (as currently).

Voilà l'idée :0)

Regards

**Comment by EricWittmann** [comment]
OK thank you for the explanation.  And for proposing a solution as well.  I'm comfortable with the approach you have suggested!  Basically the idea is that we only strip the apiKey if we're actually consuming it (using it for Apiman auth).  Otherwise we assume it's intended for the back-end server and pass it through unchanged.   That makes sense to me.

Anyone else? @volkflo or @msavy ?

**Comment by volkflo** [comment]
I think this is okay for me but this is very special usecase and this behavior should be documented somewhere in the docs :)

**Comment by tevosouza** [comment]
How about this approach?
![image](https://user-images.githubusercontent.com/58958299/76151084-a13de780-608f-11ea-8347-dcd39aef2946.png)

**Comment by EricWittmann** [comment]
I think that's also a reasonable approach - except we should probably reverse the option so instead of an opt-in it's an opt-out.  That would preserve backwards compatibility.

**Comment by OSMOSA44** [comment]
Yes, i'm agree too with this approach and also the opt-out remark from @EricWittmann 

With a suggestion however, **enable/disable each item** (apikey end X-Api-Key) **separately for more flexibility**

**Comment by tevosouza** [comment]
> Yes, i'm agree too with this approach and also the opt-out remark from @EricWittmann
> 
> With a suggestion however, **enable/disable each item** (apikey end X-Api-Key) **separately for more flexibility**

Sorry about that @OSMOSA44, when I did my analysis I decided to remove both because I have no found 'in my mind' a specific use case to remove only one key from request and this decision reduced dramatically the complexity of implementation.
I hope you enjoy this brand new feature.

**Comment by EricWittmann** [comment]
Fixed in #828

**Comment by OSMOSA44** [comment]
@tevosouza 

In my mind, i did not want to forward the X-Api-Key specific to the API Gateway to the backend server but only the apikey waited by it

In my use case, **X-Api-Key** is for the API Gateway contract client and **apikey** is for the backend service

**Comment by tevosouza** [comment]
I understood!
Is there any problem if you forward x-api-key (for quick solution) to your backend too?
When I have some time, I'll try to improve this solution changing the approach of key stripping control.

**Comment by OSMOSA44** [comment]
Hi @tevosouza 
No problemo to forward x-api-key for my use case
Have a good day
