### ISSUE TITLE
Non-admin users cannot create organizations

### ISSUE THREAD

**Issue by EricWittmann** [apiman/apiman#817]
In testing a recent PR I noticed that I wasn't able to create an organization unless I was logged in as an admin.  @volkflo suggested that was due to a recent change that his team made for that specific purpose.  We should discuss.

The UI assumes that all users can create organizations.  I think what we should do is make this configurable (globally).  By default I think the old behavior should be restored (all users can create Orgs) but with a configuration option the new behavior (admins only) could be enabled.  Along with that change we would need to update the UI so that the option to create an Org only exists (e.g. on the Dashboard) when it's allowed.

**Comment by volkflo** [comment]
Yes, I checked this again. See here: https://github.com/apiman/apiman/blob/e14d18ec74b20a675591fa0384ead48e55519f3c/manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/OrganizationResourceImpl.java#L139-L141

In our UI is this the case, the create button is hidden if you are not logged in as admin.
But I agree with your suggestion, that It would be cool the make this configurable somewhere (not sure where?).

**Comment by EricWittmann** [comment]
Yeah I can't remember how configuration options work in Apiman or even if we had something like that.  I'll need to dig in a bit to refresh my memory. :)

**Comment by tevosouza** [comment]
If I understood correctly, organizations are the "base" for all other things in apiman. I'm not sure if deny the creation of the organization to the user even if they don't have admin privileges is a good idea.
I'm assuming that if the user is logged on the system is for doing some action and the access was granted by one administrator and if the organization is the "base" the user could be blocked to use the system (can't do any other action).

**Comment by EricWittmann** [comment]
Yeah that was the idea for Orgs for sure (basically the same concept as GitHub).  But I also understand that some companies may want to limit the creation of Orgs to only admins.  Then those admins will be responsible for adding other users to those orgs.  This would centralize the admin and configuration of organizations.  I can see that as a valid use-case.  So I'm fine with the option, but it shouldn't be the default IMO.

**Comment by volkflo** [comment]
@EricWittmann I think we can close this now? :)
