### ISSUE TITLE
Swagger definitions failing

### ISSUE THREAD

**Issue by tevosouza** [apiman/apiman#818]
After the merge of commit e14d18e, swagger rest API definitions begin to fail.
I'm reporting it, but if I can I will try to take a look onto that later

![image](https://user-images.githubusercontent.com/58958299/76478998-1dfef780-63e9-11ea-8ae4-df27160f5ac7.png)

Steps to reproduce:

```
cd <apiman_root>
mvn clean
mvn clean install -Pinstall-all-wildfly10
./tools/server-all/target/wildfly-10.1.0.Final/bin/standalone.sh -b 0.0.0.0
```
Open the browser and navigate to http://localhost:8080/apimanui and click on menu entry 'REST API' on profile menu.

Edit:
Works like a charm on tomcat T_T

**Comment by volkflo** [comment]
@tevosouza I just wanted to comment on this and saw your edit note. I should check my features in the future on wildfly too. Sorry about that.

**Comment by volkflo** [comment]
But one thing came into my mind after @EricWittmann explained the RestExceptionMapper problem.
For tomcat this applies:
https://github.com/apiman/apiman/blob/e14d18ec74b20a675591fa0384ead48e55519f3c/manager/api/war/tomcat8/src/main/java/io/apiman/manager/api/war/tomcat8/Tomcat8ApiManagerApplication.java#L39-L48
So there is a special config for the swagger part and I don't see such config for wildfly.

@EricWittmann Maybe you have an idea where we need to configure this for wildfly? :)

**Comment by tevosouza** [comment]
@volkflo I've added this to pom.xml of apiman-manager-api-war-wildfly8 and error is gone, but still not generating rest documentation.
```
    <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-jaxrs</artifactId>
      <exclusions>
        <exclusion>
          <groupId>javax.ws.rs</groupId>
          <artifactId>jsr311-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```
After the explanation of @EricWittmann i believe that the problem is on the configuration of project

**Comment by EricWittmann** [comment]
Can someone create some screen captures or a video or something to show what's happening from the user's perspective.  That would help me better understand this. :)

**Comment by tevosouza** [comment]
The functionality is very simple,
After login as admin, click on 'admin' profile menu and REST API
![image](https://user-images.githubusercontent.com/58958299/76627841-87325800-651a-11ea-8352-8f26b245e66f.png)

On tomcat, the page showed correctly
![image](https://user-images.githubusercontent.com/58958299/76627896-a4672680-651a-11ea-8c63-c078449dd4f7.png)

And on wildfly the same procedure throw an error
![image](https://user-images.githubusercontent.com/58958299/76478998-1dfef780-63e9-11ea-8ae4-df27160f5ac7.png)

**Comment by EricWittmann** [comment]
OK great - this is helpful, thank you.

**Comment by EricWittmann** [comment]
This should be fixed by: https://github.com/apiman/apiman/pull/821
