### ISSUE TITLE
Validation for policy configurations

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#827]
At the moment the config for policies is not validated in the UI. You can enter also wrong configurations.
E.g.
![image](https://user-images.githubusercontent.com/13332383/77647275-69c3ac00-6f66-11ea-83b7-e6e06c01433c.png)
```json
{
    "responseCode": 500,
    "message": "a header name cannot contain the following prohibited characters: =,;: \\t\\r\\n\\v\\f: X-API-Key: 42"
}
```

This config causes a Runtime Exception which could be avoided if we would validate the input.
I am not sure how easy we could achieve this because many policies are imported via a plugin and the HTML is generated with [angular-schema-form](https://github.com/json-schema-form/angular-schema-form)

**Comment by msavy** [comment]
You can add a regex check to the schema-based definitions, which should work for this case I think

**Comment by msavy** [comment]
See https://github.com/apiman/apiman-plugins/blob/master/keycloak-oauth-policy/src/main/apiman/policyDefs/schemas/keycloak-oauth-policyDef.schema#L94

**Comment by volkflo** [comment]
@msavy Oh that's cool, we didn't check the other policies. 
If we have the time we may add this to all policies :)

**Comment by volkflo** [comment]
I made these changes in https://github.com/apiman/apiman-plugins/pull/95
