### ISSUE TITLE
Field injection does not work for all classes

### ISSUE THREAD

**Issue by bekihm** [apiman/apiman#829]
I steped into a limitation with field injection during the [introduction of the new elasticsearch client for version 7.X](https://github.com/apiman/apiman/issues/766). The class RestHighLevelClient is not injectable because it contains final fields:

`WELD-001480: Bean type class org.elasticsearch.client.RestHighLevelClient is not proxyable because it contains a final method public final org.elasticsearch.action.index.IndexResponse org.elasticsearch.client.RestHighLevelClient.index(org.elasticsearch.action.index.IndexRequest,org.elasticsearch.client.RequestOptions) throws java.io.IOException - Producer Method [RestHighLevelClient] with qualifiers [@Default @Named @Any] declared as [[BackedAnnotatedMethod] @Produces @ApplicationScoped @Named public static io.apiman.manager.test.server.TestCdiFactory.provideStorageJestClient()]`

Using a wrapper for the class works:

![2020-04-01 11_44_14-apiman  C__Projekte_apiman  -  _manager_test_api_src_main_java_io_apiman_manag](https://user-images.githubusercontent.com/33115480/78123388-6325b080-740e-11ea-8049-c34d07a4d34e.png)

But I personally not like this approach that much, because we have an unnecessary getter call to get the client from the wrapper. I would prefer to avoid injections by passing the client via parameter of the EsStorage initilize method or constructor e.g. here:
https://github.com/apiman/apiman/blob/8e8fc6d8a64b270ed536b1df0ffd43137b89f854/manager/test/api/src/main/java/io/apiman/manager/test/server/TestCdiFactory.java#L123

@EricWittmann @msavy What you are thinking about this?

**Comment by bekihm** [comment]
Of course the injection gives some comfort to not care about all cases in the provideStorage method but I'm not sure if this is a strong argument to use injection here.

**Comment by EricWittmann** [comment]
I don't have a strong preference here.  Injection is great when it works well but it doesn't always.  In this case feel free to update the `initialize` method to accept the client as a parameter.  Or, if it makes sense, just have the `EsStorage` class instantiate the client directly.

**Comment by bekihm** [comment]
@EricWittmann Ok thanks for your opinion :-) So I will probably make the client a parameter.

**Comment by EricWittmann** [comment]
That's fine with me.  However, what do you think about having the `EsStorage` class (or some base class) instantiate the client?  Any reason to pass it in?

**Comment by bekihm** [comment]
I have to think about it again. I know that there was something with the different configurations for tests and production and the test framework. But maybe this is not really a problem and we can instantiate the client whin the `EsStorage` class.

So I will take a look on this again.

**Comment by EricWittmann** [comment]
Ah yes good point - there may be a test vs. production difference that I'm not thinking about.  Either way, as long as you consider that option (even if you choose the alternative) I'm happy. :)
