### ISSUE TITLE
API Catalog import not possible anymore

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#830]
After we merged https://github.com/apiman/apiman/pull/809 the import via the API Catalog does not work anymore.
![image](https://user-images.githubusercontent.com/13332383/78145011-a85ada00-7430-11ea-86cb-3d72be339146.png)

Also, many HTML form tags have the wrong closing tag.
![image](https://user-images.githubusercontent.com/13332383/78145137-cf191080-7430-11ea-9efe-25c14ae831b8.png)
@dbayub Can you please have a look at this?

**Comment by volkflo** [comment]
## There are more things failing:

### You can't add a policy correctly "Time Restricted Access Policy"
![image](https://user-images.githubusercontent.com/13332383/78236717-acdbcd00-74da-11ea-99cb-4ca33b0fa911.png)
### You can't add a policy correctly "Authorization Policy"
![image](https://user-images.githubusercontent.com/13332383/78236747-b8c78f00-74da-11ea-983f-f928da25a186.png)
### White spaces are not allowed anymore, which was possible before
![image](https://user-images.githubusercontent.com/13332383/78236782-c5e47e00-74da-11ea-97cd-99e11d4be6cf.png)

And I'm not sure if there are also other things that does not work.
I checked the API Catalog this will not work because the `<form>...</form>` is not part of the modal that is used there.

The problem with the policies is that you set the value `required` into the fields, but the policy config is totally fine if one entry is in the table, but because of the `required` the button gets disabled.

@dbayub Can you please rework the validation of the forms?

**Comment by tevosouza** [comment]
I don't know if I understood correctly, but in my opinion, allowing whitespaces maybe a bug because org name integrates the endpoint URL and whitespaces in a URL is not a good practice.

> URLs with whitespace characters are not recommended as they could cause issues when site visitors share or link to the URL, potentially leading to broken links and a loss of potential link equity. Whitespace characters in URLs are considered unsafe

**Comment by bekihm** [comment]
@tevosouza The handling of whitespaces in such names was previously possible and handled correctly. We want to keep this behaviour for existing installations.

**Comment by volkflo** [comment]
As @bekihm mentioned this is just a UI thing.
See here :)
![image](https://user-images.githubusercontent.com/13332383/78255706-f8e93a80-74f7-11ea-872c-ace9fa7643dc.png)

**Comment by tevosouza** [comment]
Got it! ;)

**Comment by volkflo** [comment]
Hi together,
unfortunately, we found more problems that make the UI unusable for us.
See the newly introduced regex validations:
![image](https://user-images.githubusercontent.com/13332383/78346116-de1dd100-759e-11ea-8f9a-91768dd6f81b.png)
[Gateway URL Working Example](https://regexr.com/51okp)
![image](https://user-images.githubusercontent.com/13332383/78346175-f55cbe80-759e-11ea-8d1d-0664847b6df2.png)
[Gateway URL Not Working Example](https://regexr.com/51oks)
![image](https://user-images.githubusercontent.com/13332383/78346234-07d6f800-759f-11ea-86f4-934c7716e86f.png)
[Description Example](https://regexr.com/51okv)
This means you can't configure any vert.x gateway anymore.

@EricWittmann Can we do a temporary revert of the #809 till this gets reworked because the UI is not usable as before

**Comment by EricWittmann** [comment]
What part of #809 is causing this?  I'll revert it anyway but am curious.

**Comment by volkflo** [comment]
Hi @EricWittmann,
that problem is that since this PR all input fields are validated with new mechanisms.  But the most input fields were already validated in the typescript code. Such as policies. So now we have some validation methods that do nothing anymore but still reside in the code.

And some fields are now validated via some regular expressions, that do not catch all cases, like white spaces or colons. See in `manager/ui/war/plugins/api-manager/ts/directives.ts`

For the gateway management in the UI now this regex applies: https://github.com/apiman/apiman/blob/a43cc345c890d52096f29648c57e550d5e5075a7/manager/ui/war/plugins/api-manager/ts/directives.ts#L776
And this does not make sense because not every gateway-endpoint will end with `/apiman-gateway-api`. The vertx gateway implementation does listen to the API calls only on a port without any suffix.

On Friday I tried to fix the problems, but unfortunately, we do not have the time to fix each input field validation.

**Comment by dbayub** [comment]
Hopefully everything is fixed now.
