### ISSUE TITLE
Travis Status Missing

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#837]
Hi @msavy,
do you have any clue why we do not see the Travis status anymore? 
![image](https://user-images.githubusercontent.com/13332383/78666857-47bc1900-78d8-11ea-8d5e-5ef75d97e11b.png)

**Comment by msavy** [comment]
Hmm none. I'll look into it shortly

**Comment by msavy** [comment]
https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798

**Comment by volkflo** [comment]
Can we fix this easily and switch to the new version?

**Comment by EricWittmann** [comment]
Perhaps we should just throw out Travis and switch to GitHub Actions?

**Comment by volkflo** [comment]
Would be also a cool option :)

**Comment by msavy** [comment]
Either option seems good!

**Comment by msavy** [comment]
Seems like it has reappeared now, though?

**Comment by tevosouza** [comment]
Yeah! It appeared! 
Maybe this issue should be closed.

![image](https://user-images.githubusercontent.com/58958299/78926990-70791580-7a74-11ea-96be-c782b95d654e.png)

**Comment by EricWittmann** [comment]
Magic?

**Comment by volkflo** [comment]
@EricWittmann and @msavy It seems that have this issue again. Maybe we can move to GitHub Apps/Actions? Otherwise, we do not directly see if a new PR breaks something.

**Comment by EricWittmann** [comment]
Yes I would like to switch to GitHub Actions for sure.

**Comment by EricWittmann** [comment]
I'm making the change to GitHub actions now.

**Comment by EricWittmann** [comment]
Should be done now.  Have a look at the new workflow and feel free to suggest changes.  I just adapted what we had in Travis...

**Comment by volkflo** [comment]
Great :) Thanks for this quick fix 🚀 
Seems we have some red test, we will look into it :)

**Comment by EricWittmann** [comment]
Yes we did - I'm on it.  👍

**Comment by EricWittmann** [comment]
Done.  I'm also going to set up a GitHub Action workflow for performing a release.  We should do that as part of the 2.0.0 release.  I'll need to review the current release process as the basis for the workflow.
