### ISSUE TITLE
Question: Can I pass apikey to backend?

### ISSUE THREAD

**Issue by spsvon** [apiman/apiman#848]
Helou, 
My backend needs apikey to identify client, but gateway stripes out apikey param.

Can I force to pass apikey param to backend?

Thank you very much,
Sergio.

**Comment by tevosouza** [comment]
Hello @spsvon,
Take a look into issue #812 and pr #325

:)

**Comment by volkflo** [comment]
@tevosouza Maybe we could combine your disableKeyStrip Feature with the apikey plugin https://github.com/apiman/apiman-plugins/tree/master/apikey-policy.
I think now we have more or less the same functionality:

- The policy allows stripping the api-key into a header of your choice
- The disableKeyStripping allows sending key/header to the backend

Would it be possible to move your functionality into the policy or the other way around?

**Comment by tevosouza** [comment]
Hi @volkflo!!
My original idea was to update the policy, but I changed my mind because if I remember correctly the stripKey function is the first call of `execute()` on `ApiRequestExecutorImpl.java` before the execution of the policy chain. 

Is there any purpose to stripkey is the first call on `execute()` block?

**Comment by spsvon** [comment]
> Hello @spsvon,
> Take a look into issue #812 and pr #828
> 
> :)

Thank you very much @tevosouza . Maybe it's strange, but we use apiman apikey as id to identify client requests on our backend. 
We need apiman apikey value on apikey parameter.

Thanks in advance for your help.

**Comment by tevosouza** [comment]
> > Hello @spsvon,
> > Take a look into issue #812 and pr #828
> > :)
> 
> Thank you very much @tevosouza . Maybe it's strange, but we use apiman apikey as id to identify client requests on our backend.
> We need apiman apikey value on apikey parameter.
> 
> Thanks in advance for your help.

I didn't test this use case, but in theory, if you check the flag "disable key strip" on the endpoint configuration tab, the key will be sent to the backend with header `X-API-Key` or `apikey` query parameter.
![image](https://user-images.githubusercontent.com/58958299/80521773-f5fc3100-8961-11ea-8a2a-cebea548aa6f.png)

**Comment by spsvon** [comment]
@tevosouza Thank you

**Comment by tevosouza** [comment]
@spsvon maybe this issue could be closed, right?
