### ISSUE TITLE
How to configure separate timeouts for separate services

### ISSUE THREAD

**Issue by MinniArora** [apiman/apiman#851]
There is a global timeout configuration in configs/conf-es.json file, as below,

  "connector-factory": {
    "class": "io.apiman.gateway.platforms.vertx3.connector.ConnectorFactory",
    "config": {
      "http.timeouts.connect": 500,
      "http.timeouts.read": 1000,
      .....

Is there a way to define different timeouts for different services (esp. read timeout ) because few services might be slow.

**Comment by volkflo** [comment]
Hi @MinniArora,
as far as I know, there is no possibility to set these configs for each API dynamically.

**Comment by MinniArora** [comment]
Ok. Thank you for a quick reply.

**Comment by tevosouza** [comment]
Yet....hehe
I'm working on it but I'm facing some personal problems that are "eating" my time.

**Comment by wbeck-fr** [comment]
Hello,
We made this with a custom policy.
`	protected void doApply(ApiRequest request, IPolicyContext context, TimeoutConfigBean config, IPolicyChain<ApiRequest> chain) {
		Map<String, String> mapPropertiesOfAPI = request.getApi().getEndpointProperties();
		String newTimeoutConnect = String.valueOf(config.getTimeoutConnect());
		String newTimeoutRead = String.valueOf(config.getTimeoutRead());
		// mettre a jour les properties d'un Endpoint
		mapPropertiesOfAPI.put("timeouts.connect", newTimeoutConnect );
		mapPropertiesOfAPI.put("timeouts.read", newTimeoutRead );

		mapPropertiesOfAPI.put("apiman-gateway.connector-factory.http.timeouts.connect", newTimeoutConnect );
		mapPropertiesOfAPI.put("apiman-gateway.connector-factory.http.timeouts.read", newTimeoutRead );

		request.getApi().setEndpointProperties(mapPropertiesOfAPI);

		request.getHeaders().put("timeoutConnect", newTimeoutConnect);
		request.getHeaders().put("timeoutRead", newTimeoutRead);

		chain.doApply(request);
	}`

**Comment by EricWittmann** [comment]
If you'd be willing to do it, you could open a PR to contribute that custom policy:  https://github.com/apiman/apiman-plugins

**Comment by wbeck-fr** [comment]
Thanks for the invitation. The PR is made

**Comment by EricWittmann** [comment]
@MinniArora See @wbeck-fr 's PR for the new custom policy!!
