### ISSUE TITLE
About WebSocket Protocol

### ISSUE THREAD

**Issue by OSMOSA44** [apiman/apiman#856]
Bonjour,

Are Wildfly and/or VertX gateways ready for Websocket protocol ?

Thanks for you answer,

Regards,

Laurent

**Comment by EricWittmann** [comment]
Hi @OSMOSA44 - unfortunately I don't think the apiman gateways support websockets.

**Comment by OSMOSA44** [comment]
Ok, then i forget :0(
Thanks ;0)
