### ISSUE TITLE
APIMAN Analytics

### ISSUE THREAD

**Issue by nishasumesh** [apiman/apiman#862]
How can I get the analytics in apiman.  What all are the analytics provided by APIMAN?

Need the following things:
1. Calls remaining / Calls success / Calls failed  etc

Can I use elastic search queries for that? Is there any document explaining how to use elastic search for queries?

**Comment by volkflo** [comment]
Hey :)
You can read a little about metrics in the [crash course](http://www.apiman.io/latest/crash-course.html#_api_metrics).
You find the "Metrics" tab on your API and on your Client Apps in the UI.
See:
![image](https://user-images.githubusercontent.com/13332383/86601155-4070de00-bfa1-11ea-9d9f-2c890022ca94.png)
![image](https://user-images.githubusercontent.com/13332383/86601348-7a41e480-bfa1-11ea-96b0-bca69e460c32.png)

If you configured a policy like the "rate limiting policy" you will see the remaining calls in the response of a request.
See:
![image](https://user-images.githubusercontent.com/13332383/86600012-bb38f980-bf9f-11ea-80de-33d060cdc325.png)

Additionally, if you use a standalone elasticsearch instance you can configure kibana for advanced analytics.

**Comment by nishasumesh** [comment]
@volkflo , Thanks ..  it worked ...
