### ISSUE TITLE
Sidebar for UI

### ISSUE THREAD

**Issue by tevosouza** [apiman/apiman#865]
Hi Guys!

I'm adding a fixed sidebar to apiman UI and I want to show you what I've done at the moment.

What you think about it
![image](https://user-images.githubusercontent.com/58958299/87255705-8cb99380-c463-11ea-9d75-5ac8ecf76e9a.png)

**Comment by volkflo** [comment]
It is looking good, very familiar ;)

**Comment by tevosouza** [comment]
pull request made #866 =)
