### ISSUE TITLE
Error while starting apiman from second time onwards

### ISSUE THREAD

**Issue by nishasumesh** [apiman/apiman#870]
First time with installation, everything worked fine. I stopped the server and started that next day, i am getting error while starting apiman. 
I could not find why this error happens from second time onwards. First time everything was working fine with out any error in logs.

Please find the attached logs.
[log_apiman.txt](https://github.com/apiman/apiman/files/4964143/log_apiman.txt)

**Comment by msavy** [comment]
The error indicates that elasticsearch is not running or is inaccessible
from the machine that apiman is running on

**Comment by nishasumesh** [comment]
I understood that but I don't know the reason why it is failing. I am using the downloaded bundle as such for startup. I am not installing elastic search separate. Also the url for elastic search "http://localhost:19200/". is giving me the below response "{
  "name" : "EXoH6v8",
  "cluster_name" : "apiman",
  "cluster_uuid" : "PeIwH6B6Qo-pFW3_rJZvUw",
  "version" : {
    "number" : "5.6.9",
    "build_hash" : "877a590",
    "build_date" : "2018-04-12T16:25:14.838Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}"

Theres is no error message or anything I am getting from elastic search. But the issue is none of my security policy details are loading properly.

**Comment by nishasumesh** [comment]
Earlier also I was getting this error after first successful startups, and when I posted the logs here , I got response to downgrade my java from jdk 11 to jdk 8. Now it is jdk8 and still the same error. First time I am getting evrything prefect including my elastic search. But from second time onwards when I start my apiman, I am getting elastic search error. Mine is mac os. btw.

**Comment by volkflo** [comment]
It seems that elasticsearch finished startup after the gateway tried to connect to it. The gateway should recover when elasticsearch is available/back.
Did you try to login after this? Are there follow up exceptions if you try to use an API?

As we started to use apiman we quickly switched to a standalone elasticsearch installation.
The embedded elasticsearch caused also problems for us.

**Comment by msavy** [comment]
The embedded Elastic is definitely only meant for quick testing or demos. 

Switching to a standalone elastic is definitely the way to go for anything long-lived. It's rather easy to accidentally blow it away by overwriting it.

As @volkflo says, it looks like the elastic poller recovered and connected successfully, but the data contained within perhaps is not what you expected.

**Comment by volkflo** [comment]
We simply used a docker container for elasticsearch.

@bekihm and I will contribute our elasticsearch 7 changes in the future and then we need another way for the quickstart/demo because the embedded elasticserach project is no longer maintained. Probably using docker.

**Comment by nishasumesh** [comment]
Hi Thanks for the response.

I tried with a standalone elastic search server . Downloaded from  https://www.elastic.co/downloads/elasticsearch
Now I am getting a different error .

I have updated the port number in apiman.properties as shown below.

# ---------------------------------------------------------------------
# The following are settings for using elasticsearch for various
# apiman components.
# ---------------------------------------------------------------------
apiman.es.protocol=http
apiman.es.host=localhost
apiman.es.port=**9200**
apiman.es.username=
apiman.es.password=
apiman.es.timeout=10000

# ---------------------------------------------------------------------
# Some hibernate settings only useful when JPA is the storage.type.
# ---------------------------------------------------------------------
apiman.hibernate.connection.datasource=java:jboss/datasources/apiman-manager
apiman.hibernate.dialect=io.apiman.manager.api.jpa.ApimanH2Dialect
apiman.hibernate.hbm2ddl.auto=**update**
[apimanlog.txt](https://github.com/apiman/apiman/files/4964874/apimanlog.txt)
[elastic_search_log.txt](https://github.com/apiman/apiman/files/4964875/elastic_search_log.txt)

**Comment by volkflo** [comment]
At moment apiman requires elasticsearch 5.X.
Please download an old version from https://www.elastic.co/downloads/past-releases/elasticsearch-5-6-16

ES 7 support will be contributed in the future.

**Comment by nishasumesh** [comment]
Thanx @volkflo , It worked now.
