### ISSUE TITLE
APIMan with postgres9.4

### ISSUE THREAD

**Issue by nishasumesh** [apiman/apiman#871]
I am trying to use apiman with my postgres server. I am able to create role and organization. But policies list is missing in the drop down. Can some one help me to add policies. I need the default list of policies apiman provides.

**Comment by nishasumesh** [comment]
It got resolved. 

First issue was apiman did not work with my  postgres :  It was a version issue. I changed the jar file version to postgresql-42.0.0 and it worked
Second issue was policies were not loading : took policy list from https://raw.githubusercontent.com/apiman/apiman/master/distro/data/src/main/resources/data/all-policyDefs.json here and imported.
Third issue was api gateway unauthorized issue :  This got fixed with the following solution
Configuration Endpoint: http://localhost:8080/apiman-gateway-api/
Username: apimanager
Password: admin123!

**Comment by volkflo** [comment]
Hi @nishasumesh,

just saw your post now.
Normally at the first startup, the content from this file https://github.com/apiman/apiman/blob/master/distro/data/src/main/resources/bootstrap/apiman-default-config.json are imported. And you don't have to do everything manually.
Maybe you should compare the contents of these two files. I am not sure how up to date the "all-policyDefs.json" is (https://raw.githubusercontent.com/apiman/apiman/master/distro/data/src/main/resources/data/all-policyDefs.json).

If you later switched the storage the data is missing. I am working on a better mechanism now that should avoid such problems in the future for new installations.

Regards,
Florian

**Comment by nishasumesh** [comment]
@volkflo , Thank you.

**Comment by nishasumesh** [comment]
"https://raw.githubusercontent.com/apiman/apiman/master/distro/data/src/main/resources/data/all-policyDefs.json" this file import is working fine. but the other one you have shared, though it has roles and gateways also included, import didn't work for me "https://github.com/apiman/apiman/blob/master/distro/data/src/main/resources/bootstrap/apiman-default-config.json"
