### ISSUE TITLE
Organization user viewing other organisations

### ISSUE THREAD

**Issue by nishasumesh** [apiman/apiman#872]
Hi,

I want the below scenarios to be created in apiman for my project
1. Want one organization with 5 different users
2. Each user will have specific roles and access rights. For example user 1 may not have access to user 2's apps / api's

I tried creating the above scenario in my apiman. Created an admin user with all roles and a tenant user with only api view permission.

But when I am logging in as tenant user, I am able to see all other organization details also.

![Screenshot 2020-07-28 at 6 04 57 PM](https://user-images.githubusercontent.com/25498796/88666658-0311f300-d0fe-11ea-980d-f19b5c1ed62b.png)
![Screenshot 2020-07-28 at 6 05 51 PM](https://user-images.githubusercontent.com/25498796/88666666-04dbb680-d0fe-11ea-8ec5-ae9413b2d611.png)

Is there any way i can restrict that view of all organization and its details to other non admin users.
Please help me to fix this, If this is not possible, i may have to leave apiman and try out something else :(

**Comment by volkflo** [comment]
Hi @nishasumesh,

the search in apiman will show every user all organizations and APIs.
But at the moment you are not able to see sensitive information about the APIs or organizations unless you are an admin-user (role: apiadmin or have the view-permissions). We changed this behaviour a few months ago. See: [PR-811](https://github.com/apiman/apiman/pull/811)
So your users e.g. will not see the implementation endpoint of an API.

The only problem is that the latest apiman release build is older than these changes (apiman-1.5.5 - Jan 22).
So you have to do a manually build for the latest "installer".

Maybe @msavy or @EricWittmann can perform a little release?

Regards,
Florian

**Comment by nishasumesh** [comment]
@volkflo , Thanx for the update.

**Comment by EricWittmann** [comment]
Sure, happy to do an Apiman release.  I'll try to get that done this week.

**Comment by nishasumesh** [comment]
Thank you  @EricWittmann

**Comment by EricWittmann** [comment]
This is in progress.  The deploy into maven central failed with what I assume to be a problem on Sonatype's end (Bad Gateway error).  I have to skip that part and do the rest manually now. :(

**Comment by EricWittmann** [comment]
Currently uploading the packages to the JBoss FTP site.

**Comment by EricWittmann** [comment]
OK the release of 1.5.7.Final is complete - the only thing that didn't work was deploying the core apiman artifacts to maven central.  But I think that may be OK.  The plugins successfully deployed, which I think may be the only artifacts that matter.

If I'm wrong about this let me know and I'll try the deploy step again.

@msavy

**Comment by msavy** [comment]
Hmm, I think should still work but I wouldn't want to swear on it!

**Comment by nishasumesh** [comment]
Can you provide the link from where I can download the build 1.5.7.Final.

**Comment by nishasumesh** [comment]
I tried the latest build 1.5.7.Final. I think there are some issues / may be functionality change. Please confirm

- I am a new user with client app admin and api admin roles (who can create and edit client apps and api's) , but now I am not able to add any plans to any of my api's also I am not able to add policies to any of may api's

- Once I logged in, if i have member access to a particular organization, I should be able to see that organization according to me. But in the latest build it is not showing even the orgs where i am a member of it.

**Comment by EricWittmann** [comment]
If you are a member of an org, then yes you should be able to see it.  If you don't then I assume that's a bug.  However it's been awhile since I've looked at any of this.  So I'll need to download the latest version and play around with it to refresh my memory.  There may be an "OrgView" permission that you would need to see an org.  So it might be possible to configure things in such a way that you can make someone a member of an Org but despite that they can't actually see the Org in the list.  I'll see what I can find out.

**Comment by EricWittmann** [comment]
OK I downloaded the latest quickstart and did some testing against that.  I did find a problem with the current configuration of roles and permissions.  I need to modify the **API Developer** and **Client App Developer** roles to include the `orgView` permission.  Without that change, my non-owner user (who I added as a member) could see the org in their list of orgs, but after clicking the org they got a 404.

Does that help?  Are you using the quickstart or something else?

Once I made that change I was able to do everything I wanted (as that member/non-owner user) including creating Plans.

**Comment by volkflo** [comment]
@EricWittmann I think this is caused by the refactoring of the REST API. 
I remember that the `orgView` permission was never or only sometimes checked.
Since we don't use the default roles this never caught our attention. We maybe should add the `orgView` permission to the apiman default roles. What do you think?

**Comment by EricWittmann** [comment]
Yes adding the `orgView` permission to the default roles would be good!
