### ISSUE TITLE
apiman-gateway-engine-redis failure

### ISSUE THREAD

**Issue by YHS2012** [apiman/apiman#887]
When I run the command "mvn clean install -Pinstall-all-wildfly10", the state of apiman-gateway-engine-redis is failure and the rest of api skipped.

![bugs](https://user-images.githubusercontent.com/68266434/89978346-e51cc480-dc9f-11ea-8189-203a1d39f26c.png)

**Comment by volkflo** [comment]
Hi @YHS2012,

can you post the error message from your logs?
Do you have docker installed?

**Comment by YHS2012** [comment]
Yes, it works after I installed Docker. Previously, the Docker has not added inside the requirements of building apiman. Thanks for your help !!
