### ISSUE TITLE
Apply Authentication Policy to a subset of paths

### ISSUE THREAD

**Issue by sasan-j** [apiman/apiman#891]
Hi

When defining an API, is it possible to only secure a subset of paths using an Authentication policy (e.g. Keycloak)?
For example I want the following to be freely accessible:
POST /users
POST /sessions/
But I want the following paths to be accessible only to authenticated users:
GET /users
GET /stuff
POST /stuff

Thanks in advance.

Best,
Sasan

**Comment by volkflo** [comment]
Hi @sasan-j,

Yes, this is possible. See my answer here: https://github.com/apiman/apiman/issues/868#issuecomment-658569077.
You have to set the Keycloak OAuth Policy and enable stripping of roles.
Then in your Authorization Policy, you can specify rules to your needs.

Hope this will help you :)

**Comment by EricWittmann** [comment]
I think to add to this answer - if I recall correctly the Authentication policies have an option to **not require** authentication credentials to be provided.  In other words, if you set that option to true, then the policy **will not fail** if the request contains no credentials.  You then must combine that with an Authorization policy to protect certain subpaths.

And I think you will need roles to exist for this approach to work.  Roles are supported for both OAuth and the Basic auth policies.

**Comment by volkflo** [comment]
I will close this due to inactivity. If there are further questions please reopen this issue or create a new one :)
