### ISSUE TITLE
Maven clean install "java/lang/outofmemoryerror" error.

### ISSUE THREAD

**Issue by iamakashk** [apiman/apiman#897]
Hi ,
I am facing some unusual issue which I am not understanding,
I have downloaded source code from 
[apiman source code](https://github.com/apiman/apiman/archive/apiman-1.5.1.Final.zip). When I am trying to do 
`sudo mvn clean install -Pinstall-all-wildfly10` I am getting out of memory issue.
![apimanissue2](https://user-images.githubusercontent.com/19202603/91531712-d6364300-e92a-11ea-9932-caa7bdee8fee.JPG)
![apimanissue3](https://user-images.githubusercontent.com/19202603/91531715-d7677000-e92a-11ea-9e05-335011b0d716.JPG)
![apimanissue1](https://user-images.githubusercontent.com/19202603/91531717-d8989d00-e92a-11ea-8d28-ce0d5ad1fc90.JPG)

Can someone help me with this?

**Comment by volkflo** [comment]
Hi @iamakashk,

first of all, we recommend using the latest release (https://github.com/apiman/apiman/releases/tag/apiman-1.5.7.Final) or the latest master branch.
1. Which version of java are you using? `java -version`
2. How much memory is available on your system?

Please note if you use the actual code on the master branch that the command recently changed to `mvn clean install -Pinstall-all-wildfly`

**Comment by iamakashk** [comment]
Hi @volkflo 
Here is my java version:
`$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200728_727 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)`

I have 16GB ram machine. 
Just FYI ,
I changed 
`<repository>
      <id>central</id>
      <name>Central Repository</name>
      <url>http://repo.maven.apache.org/maven2</url>
     ...
    </repository>
` to this 
`<repository>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo.maven.apache.org/maven2</url>
     ...
    </repository>
`
Also 
`<version.bundle.plugin>2.5.3</version.bundle.plugin>` to this 
`<version.bundle.plugin>4.2.1</version.bundle.plugin>`

Just now I am able to complete the clean install process.
Noted on your 
`mvn clean install -Pinstall-all-wildfly` change. Will try this again.

**Comment by volkflo** [comment]
Yes, the `http` to `https` was changed this year. 
The 1.5.1 Release is from 2018. I think the best is to switch to the latest version :)

Please note that we actually in the middle of a new apiman release (2.0) process.

**Comment by iamakashk** [comment]
Hi @volkflo ,
I tried with [this url](https://github.com/apiman/apiman/releases/tag/apiman-1.5.7.Final) and `mvn clean install -Pinstall-all-wildfly` this command. but ran into following error 
`[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ apiman-common-plugin ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /home/etp/Desktop/apiman0/apiman-apiman-1.5.7.Final/common/plugin/target/classes
[INFO] /home/etp/Desktop/apiman0/apiman-apiman-1.5.7.Final/common/plugin/src/main/java/io/apiman/common/plugin/PluginUtils.java: /home/etp/Desktop/apiman0/apiman-apiman-1.5.7.Final/common/plugin/src/main/java/io/apiman/common/plugin/PluginUtils.java uses or overrides a deprecated API.
[INFO] /home/etp/Desktop/apiman0/apiman-apiman-1.5.7.Final/common/plugin/src/main/java/io/apiman/common/plugin/PluginUtils.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ apiman-common-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ apiman-common-plugin ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/etp/Desktop/apiman0/apiman-apiman-1.5.7.Final/common/plugin/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ apiman-common-plugin ---
[INFO] Surefire report directory: /home/etp/Desktop/apiman0/apiman-apiman-1.5.7.Final/common/plugin/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.apiman.common.plugin.PluginClassLoaderTest
Hello from apiman-quickstarts-plugin-with-deps::DepsPluginMain!
{"field1":"value1","field2":"value2"}
Hello from apiman-quickstarts-plugin::PluginMain!
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.578 sec <<< FAILURE! - in io.apiman.common.plugin.PluginClassLoaderTest
testLoadClass(io.apiman.common.plugin.PluginClassLoaderTest)  Time elapsed: 0.01 sec  <<< FAILURE!
java.lang.AssertionError: expected:<io.apiman.notfound.MyClass> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.apiman.common.plugin.PluginClassLoaderTest.testLoadClass(PluginClassLoaderTest.java:75)

Running io.apiman.common.plugin.PluginCoordinatesTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in io.apiman.common.plugin.PluginCoordinatesTest

Results :

Failed tests: 
  PluginClassLoaderTest.testLoadClass:75 expected:<io.apiman.notfound.MyClass> but was:<null>

Tests run: 6, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for apiman 1.5.7.Final:
[INFO] 
[INFO] apiman ............................................. SUCCESS [  3.152 s]
[INFO] apiman-common ...................................... SUCCESS [  0.109 s]
[INFO] apiman-common-auth ................................. SUCCESS [ 14.024 s]
[INFO] apiman-common-util ................................. SUCCESS [  7.794 s]
[INFO] apiman-common-config ............................... SUCCESS [  5.552 s]
[INFO] apiman-common-logging .............................. SUCCESS [  0.077 s]
[INFO] apiman-common-logging-core ......................... SUCCESS [  4.702 s]
[INFO] apiman-common-plugin ............................... FAILURE [  1.658 s]
[INFO] apiman-gateway ..................................... SKIPPED
[INFO] apiman-gateway-engine .............................. SKIPPED
[INFO] apiman-gateway-engine-beans ........................ SKIPPED
[INFO] apiman-gateway-engine-core ......................... SKIPPED
[INFO] apiman-common-logging-log4j2 ....................... SKIPPED
[INFO] apiman-common-es ................................... SKIPPED
[INFO] apiman-common-net .................................. SKIPPED
[INFO] apiman-common-servlet .............................. SKIPPED
[INFO] apiman-common-logging-slf4j ........................ SKIPPED
[INFO] apiman-distro ...................................... SKIPPED
[INFO] apiman-distro-data ................................. SKIPPED
[INFO] apiman-manager ..................................... SKIPPED
[INFO] apiman-manager-api ................................. SKIPPED
[INFO] apiman-manager-api-beans ........................... SKIPPED
[INFO] apiman-distro-ddl .................................. SKIPPED
[INFO] apiman-manager-api-config .......................... SKIPPED
[INFO] apiman-manager-api-core ............................ SKIPPED
[INFO] apiman-gateway-api ................................. SKIPPED
[INFO] apiman-gateway-api-rest ............................ SKIPPED
[INFO] apiman-manager-api-gateway ......................... SKIPPED
[INFO] apiman-manager-api-export-import-api ............... SKIPPED
[INFO] apiman-manager-api-rest-exceptions ................. SKIPPED
[INFO] apiman-manager-api-security ........................ SKIPPED
[INFO] apiman-manager-api-rest ............................ SKIPPED
[INFO] apiman-test ........................................ SKIPPED
[INFO] apiman-test-common ................................. SKIPPED
[INFO] apiman-manager-api-migrator ........................ SKIPPED
[INFO] apiman-manager-api-rest-impl ....................... SKIPPED
[INFO] apiman-manager-api-jpa ............................. SKIPPED
[INFO] apiman-manager-api-es .............................. SKIPPED
[INFO] apiman-manager-api-jdbc ............................ SKIPPED
[INFO] apiman-manager-api-hawkular ........................ SKIPPED
[INFO] apiman-manager-api-war ............................. SKIPPED
[INFO] apiman-manager-api-ispn ............................ SKIPPED
[INFO] apiman-manager-api-war-wildfly8 .................... SKIPPED
[INFO] apiman-manager-ui .................................. SKIPPED
[INFO] apiman-manager-ui-war .............................. SKIPPED
[INFO] apiman-manager-ui-war-wildfly8 ..................... SKIPPED
[INFO] apiman-gateway-engine-filesystem ................... SKIPPED
[INFO] apiman-gateway-engine-storage-common ............... SKIPPED
[INFO] apiman-gateway-engine-hazelcast .................... SKIPPED
[INFO] apiman-gateway-engine-ispn ......................... SKIPPED
[INFO] apiman-gateway-engine-es ........................... SKIPPED
[INFO] apiman-gateway-engine-hawkular ..................... SKIPPED
[INFO] apiman-gateway-engine-jdbc ......................... SKIPPED
[INFO] apiman-gateway-engine-influxdb ..................... SKIPPED
[INFO] apiman-test-policies ............................... SKIPPED
[INFO] apiman-gateway-engine-policies ..................... SKIPPED
[INFO] apiman-gateway-platforms ........................... SKIPPED
[INFO] apiman-gateway-platforms-servlet ................... SKIPPED
[INFO] apiman-gateway-api-rest-impl ....................... SKIPPED
[INFO] apiman-gateway-platforms-war ....................... SKIPPED
[INFO] apiman-gateway-platforms-war-wildfly8 .............. SKIPPED
[INFO] apiman-gateway-platforms-war-wildfly8-api .......... SKIPPED
[INFO] apiman-gateway-platforms-war-wildfly8-gateway ...... SKIPPED
[INFO] apiman-distro-es ................................... SKIPPED
[INFO] apiman-distro-wildfly10 ............................ SKIPPED
[INFO] apiman-distro-eap7 ................................. SKIPPED
[INFO] apiman-manager-api-war-tomcat8 ..................... SKIPPED
[INFO] apiman-manager-ui-war-tomcat8 ...................... SKIPPED
[INFO] apiman-gateway-platforms-war-tomcat8 ............... SKIPPED
[INFO] apiman-gateway-platforms-war-tomcat8-api ........... SKIPPED
[INFO] apiman-gateway-platforms-war-tomcat8-gateway ....... SKIPPED
[INFO] apiman-distro-tomcat8 .............................. SKIPPED
[INFO] apiman-distro-wildfly11 ............................ SKIPPED
[INFO] apiman-gateway-platforms-vertx3-common ............. SKIPPED
[INFO] apiman-gateway-engine-vertx-eb-inmemory ............ SKIPPED
[INFO] apiman-gateway-engine-vertx-polling ................ SKIPPED
[INFO] apiman-gateway-engine-3scale ....................... SKIPPED
[INFO] apiman-gateway-engine-prometheus ................... SKIPPED
[INFO] apiman-gateway-platforms-vertx3 .................... SKIPPED
[INFO] apiman-distro-vertx ................................ SKIPPED
[INFO] apiman-manager-api-micro ........................... SKIPPED
[INFO] apiman-manager-test ................................ SKIPPED
[INFO] apiman-manager-test-api ............................ SKIPPED
[INFO] apiman-gateway-engine-osgi ......................... SKIPPED
[INFO] apiman-gateway-engine-redis ........................ SKIPPED
[INFO] apiman-gateway-engine-vertx-shareddata ............. SKIPPED
[INFO] apiman-gateway-platforms-war-micro ................. SKIPPED
[INFO] apiman-gateway-test ................................ SKIPPED
[INFO] apiman-test-suite .................................. SKIPPED
[INFO] apiman-tools ....................................... SKIPPED
[INFO] apiman-tools-ddl ................................... SKIPPED
[INFO] apiman-tools-i18n .................................. SKIPPED
[INFO] apiman-tools-jdbc .................................. SKIPPED
[INFO] apiman-tools-ldap .................................. SKIPPED
[INFO] apiman-tools-services .............................. SKIPPED
[INFO] apiman-tools-server-all ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  42.789 s
[INFO] Finished at: 2020-08-28T13:40:15+05:30
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "install-all-wildfly" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project apiman-common-plugin: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/etp/Desktop/apiman0/apiman-apiman-1.5.7.Final/common/plugin/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apiman-common-plugin`

for which I made a change in pom.xml
added 
`<testFailureIgnore>true</testFailureIgnore>`
in following block.
` <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${version.surefire.plugin}</version>
          <configuration>
                  <testFailureIgnore>true</testFailureIgnore>
            <systemProperties>
              <java.io.tmpdir>${project.build.directory}</java.io.tmpdir>
            </systemProperties>
            <argLine>-Xmx1024m</argLine>
          </configuration>
        </plugin>
        <plugin>
`
after this I was able to clean install successfully. I hope this is the right process.

**Comment by volkflo** [comment]
Sorry, maybe I was not clear enough:

-  For the latest release (https://github.com/apiman/apiman/releases/tag/apiman-1.5.7.Final) it is still `mvn clean install -Pinstall-all-wildfly10`
- For the latest master branch (https://github.com/apiman/apiman/archive/master.zip) it is `mvn clean install -Pinstall-all-wildfly`

In general, there shouldn't be any need to change the `pom.xml`.

**Comment by iamakashk** [comment]
Hey @volkflo It worked. but I had to change pom.xml as mentioned [here](https://github.com/apiman/apiman/issues/897#issuecomment-682402359). But I am not sure if we can run apiman in debug mode in ubuntu 18.04( It was working before in windows 10). Could you please help me out here if I am missing something here ?

Thanks in advance.

**Comment by volkflo** [comment]
Hi @iamakashk

Take a look at this [readme ](https://github.com/apiman/apiman/tree/master/tools/devenv). There is explained how you create a local development environment with debug possibilities.

I am not sure if this is what you looking for. Can you please explain a little bit more and maybe add the full log of the failing tests?

**Comment by iamakashk** [comment]
@volkflo Thanks for the help man!! 😊
Closing the issue.
