### ISSUE TITLE
Apiman 2.0.0.Final pointing to old plugin versions

### ISSUE THREAD

**Issue by EricWittmann** [apiman/apiman#907]
Does anyone remember how this works?  When I install Apiman 2.0.0.Final and go to the Plugins admin page to install a plugin, the plugin versions are all 1.5.8-SNAPSHOT rather than 2.0.0.Final.  I can't remember where that happens.  There's a registry of them somewhere.  I haven't looked into it yet...

@apiman/maintainers

**Comment by volkflo** [comment]
@EricWittmann I think it is taken from this file here: https://github.com/apiman/apiman-plugin-registry/blob/master/registry.json.

In this repository is also an additional release script. I think we have to somehow integrate this into the github workflow too.

At least this is configured here `distro/wildfly/src/main/resources/overlay/standalone/configuration/apiman.properties`.

**Comment by EricWittmann** [comment]
OK so it's this file then:  https://github.com/apiman/apiman/blob/master/distro/wildfly/src/main/resources/overlay/standalone/configuration/apiman.properties#L4

I think we should update that URL during a release to point to a tagged version of that file.  And then updated it back to `master` when the release is done.

**And** we should do as you suggest and update the versions in the `registry.json` file whenever a release is done.

**Comment by EricWittmann** [comment]
BTW I've updated that `registry.json` file directly for now - the versions are all 2.0.0.Final.  Thanks for the pointer. :)

Sadly when I test actually installing a plugin via the UI, it doesn't work (it just redirects me back to the dashboard).  No errors on the javascript console either.  Tested using 2.0.0.Final via docker.  Will also test without docker just to be sure, but I expect the same result.

**Comment by volkflo** [comment]
Okay, that sounds a bit strange. I will try to build the 2.0 release locally too and give it some general testing :)

**Comment by volkflo** [comment]
Mhh, if I call the URL of the "Install" Button in a new browser tab it is working.
I used this URL: https://localhost:8443/apimanui/api-manager/new-plugin?groupId=io.apiman.plugins&artifactId=apiman-plugins-apikey-policy&version=2.0.0.Final&classifier=&type=

I will have a deeper look into this, probably tomorrow.
But it seems that this bug also exists before the 2.0 release

**Comment by EricWittmann** [comment]
Let me know if you get a chance to look at it.  I probably can't carve out time for this until Monday.  If you don't get a chance to look before then I'll do it. :)
