### ISSUE TITLE
Implement JPA backend for the developer portal

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman#919]
The developer portal currently works only with elasticsearch as a storage driver for the Manager UI.
To improve the overall setup and quickstart it would be nice to have also a JPA implementation.

Where to start?
https://github.com/apiman/apiman/blob/5c85f0e1a19e13804f7dc2a1634ac0525b6a57ff/manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/JpaStorage.java#L176-L182

**Comment by OmarMorales71** [comment]
@volkflo Hello Can I work on this? are you asking for implement DeveloperBean as a Jpa identity and create its repository?

**Comment by volkflo** [comment]
@OmarMorales71 I think nobody is working on this right now, so you can work on this :)

I think there is no that much to do:

- You have to implement all methods about the DeveloperBean in `manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/JpaStorage.java`
- You have to define the database tables here `https://github.com/apiman/apiman/tree/master/distro/data/src/main/resources/ddls`
- And there are also test, for e.g. `manager/test/api/src/test/resources/test-plans/exportDeveloper-testPlan.xml` there you have only to remove the `skipStorage="jpa"`

I hope this helps you a little bit :)
Feel free to ask further questions if things are not clear enough.

**Comment by OmarMorales71** [comment]
@volkflo I'm working on it!

**Comment by OmarMorales71** [comment]
@volkflo 
`src/main/java/io/apiman/manager/api/beans/developers/DeveloperBean.java `
private Set<DeveloperMappingBean> clients = new LinkedHashSet<>();

Can you tell more about these relationship? is OneToMany o ManyToMany? (If there is a relationship, I suppose I have to implement Jpa to DeveloperMappingBean also?)

```java
public class DeveloperBean implements Serializable {

    private static final long serialVersionUID = 7127400624541487145L;

    @Id
    @Column(nullable = false)
    private String id;
    private Set<DeveloperMappingBean> clients = new LinkedHashSet<>();
```

**Comment by OmarMorales71** [comment]
@volkflo If I have to build a relationship between DeveloperMappingBean and Developer Bean I have to change the data type of the attributes of DeveloperMappingBean right?

From this
```java
public class DeveloperMappingBean implements Serializable {

    private static final long serialVersionUID = -5334196591430185705L;

    private String clientId;
    private String organizationId;
```
To this?
```java
public class DeveloperMappingBean implements Serializable {

    private static final long serialVersionUID = -5334196591430185705L;

    private ClientBean client;
    private OrganizationBean organization;
```

**Comment by OmarMorales71** [comment]
@volkflo I made a draft PR. Could you check it? Let me know If I understood the relationship between DeveloperBean and the clients.

**Comment by OmarMorales71** [comment]
@volkflo Hey, checking the DeveloperResourceImpl, it's using DeveloperMappingBean. Can you explain me more about it? I don't understand why using  DeveloperMappingBean instead of ClientBean to create the relationship between developer and clients. Thanks you so much.

**Comment by volkflo** [comment]
Thanks for your contribution @OmarMorales71. I will have a look at your changes and questions after the holiday season :)Am 19.12.20, 04:15 schrieb OmarMorales71 <notifications@github.com>:

   
  @volkflo Hey, checking the DeveloperResourceImpl, it's using DeveloperMappingBean. Can you explain me more about it? I don't understand why using DeveloperMappingBean instead of ClientBean to create the relationship between developer and clients. Thanks you so much.

**Comment by volkflo** [comment]
Hi @OmarMorales71,

at the moment the developer portal and its backend are designed to show/send only the minimum of information that is needed to access and API. So the potential developer has in most of the cases no access to the Manager UI of apiman itself.
So we decided to use a mapping between name and clients because we only need the client version and the corresponding api-key. If we would add the whole client been instead of `private Set<DeveloperMappingBean> clients = new LinkedHashSet<>();` we would send the whole client object back in the REST response and this is what we avoid.

Please have also a look at the comments of @bekihm on the PR directly.

You can find a lot of information about the developer portal in the documentation of our commercial and supported product Scheer PAS.

**Comment by volkflo** [comment]
That is done for the upcoming 3.x version of apiman in the main project.
But the old devportal will be deprecated and replaced by a new version.
