### ISSUE TITLE
should we have EditorConfig for every IDE?

### ISSUE THREAD

**Issue by juniorjainsahab** [apiman/apiman#925]
# What is EditorConfig?
_EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems._
https://editorconfig.org

**Comment by bekihm** [comment]
@juniorjainsahab sounds like a nice idea, can you come up with such a config?

@apiman/maintainers What do you think about it?

**Comment by volkflo** [comment]
@bekihm and @juniorjainsahab Please see my comment below the PR.
