### ISSUE TITLE
Can't use authentification on a private Nexus

### ISSUE THREAD

**Issue by wbeck-fr** [apiman/apiman#932]
Hi,
We use a private Nexus repository with an authentification (Basic Auth).  We try to add authentification in the url but the method DefaultPluginRegistry.downloadArtifact don't take the argument.
A quick and dirty correction is the URL.getUserInfo()  method and add the authorisation in the header.
Best regards

**Comment by wbeck-fr** [comment]
Pull request made

**Comment by EricWittmann** [comment]
Fixed in https://github.com/apiman/apiman/pull/936

**Comment by EricWittmann** [comment]
Nice, thanks @wbeck-fr
