### ISSUE TITLE
Vert.x gateway - Elasticsearch - /apiman_gateway/dataVersion/instance not found

### ISSUE THREAD

**Issue by james-bostock** [apiman/apiman#934]
Hi,

I am trying to get the Apiman 1.5.7.Final Vert.x gateway to run with external Elasticsearch and Keycloak instances.

The hostname of the Elasticsearch instance is `optima-apiman-elasticsearch` and, from the machine where the gateway is running, all looks good:

```
$ curl http://optima-apiman-elasticsearch:9200
{
  "name" : "0tsjruB",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "2KdXh_pUTNm2-qEJaLizRA",
  "version" : {
    "number" : "5.6.12",
    "build_hash" : "cfe3d9f",
    "build_date" : "2018-09-10T20:12:43.732Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
```
According to its log, the gateway is reaching the Elasticsearch instance:
```
[DEBUG] 2020-11-19 16:15:37.370 [ESRegistryCacheInvalidator] JestHttpClient - GET method created based on client request
[DEBUG] 2020-11-19 16:15:37.370 [ESRegistryCacheInvalidator] JestHttpClient - Request method=GET url=http://optima-apiman-elasticsearch:9200/_cluster/health/_all
[DEBUG] 2020-11-19 16:15:37.407 [ESRegistryCacheInvalidator] AbstractAction - Request and operation succeeded
[DEBUG] 2020-11-19 16:15:37.408 [ESRegistryCacheInvalidator] JestHttpClient - HEAD method created based on client request
[DEBUG] 2020-11-19 16:15:37.408 [ESRegistryCacheInvalidator] JestHttpClient - Request method=HEAD url=http://optima-apiman-elasticsearch:9200/apiman_gateway
[DEBUG] 2020-11-19 16:15:37.411 [ESRegistryCacheInvalidator] AbstractAction - Request and operation succeeded
```
However, the next thing that I see in the log is:
```
[DEBUG] 2020-11-19 16:15:37.413 [ESRegistryCacheInvalidator] JestHttpClient - GET method created based on client request
[DEBUG] 2020-11-19 16:15:37.413 [ESRegistryCacheInvalidator] JestHttpClient - Request method=GET url=http://optima-apiman-elasticsearch:9200/apiman_gateway/dataVersion/instance
[DEBUG] 2020-11-19 16:15:37.420 [ESRegistryCacheInvalidator] AbstractAction - Response is failed. errorMessage is 404 Not Found
```
And, if I try this manually:
```
$ curl http://optima-apiman-elasticsearch:9200/apiman_gateway/dataVersion/instance
{"_index":"apiman_gateway","_type":"dataVersion","_id":"instance","found":false}
```
Running **curl** with the -v option confirms the 404 status code.

As these messages are `DEBUG` level, does that mean that they can be safely ignored?

At what point does the information that the gateway is looking for get created?

Thanks in advance

**Comment by volkflo** [comment]
If I remember this is okay. The `dataVersion` should be created if you publish the first things to the gateway and then it shouldn't return 404 I think.

Please note the apiman 2.0 release (support for Elasticsearch 7+). Because Elasticsearch 5.X has reached the end of support

**Comment by james-bostock** [comment]
Our production deployments are based on Openshift 3.11 which includes Elasticsearch 5.6. We have avoided version 2.0.0 mainly for being a *.0.0 release. When 2.0.1 is released, that decision will be revisited.

I will report back about the 404 issue once I manage to get something published to the gateway :-).

Thanks!

**Comment by james-bostock** [comment]
Hi,
Having managed to publish some APIs to the gateway, the 404 messages no longer occur and, using **curl**, I can see that the data the gateway is looking for is present in Elasticsearch:
```
$ curl http://optima-apiman-elasticsearch:9200/apiman_gateway/dataVersion/instance
{"_index":"apiman_gateway","_type":"dataVersion","_id":"instance","_version":251,"found":true,"_source":{"updatedOn":1606167321564}}
```

Thanks again for your support!

**Comment by volkflo** [comment]
Great to hear that is working :)
