### ISSUE TITLE
Allow keycloak redirct_uri from non-https hosts.

### ISSUE THREAD

**Issue by tevosouza** [apiman/apiman#945]
Hi guys, I'm back! 
I'm updating myself on the apiman changes
you guys really worked hard here ;)

Well, On client configuration in keycloak, only https requests is allowed (8443 port) when I try to access from localhost:8080, I got an error of redirect_uri.
My proposal is to allow both https and non-https as valid redirects and change web origin from '*' to '+' to allow only valid redirects as web origin, if you guys agree with it I submit a PR changing this behavior.

**Comment by volkflo** [comment]
I remember that @EricWittmann also was not that happy with my changes to force the use of https :)
I am fine with a PR. Can you send me a source about the `+`  (sounds really interesting to me).

Please note that there must be also a default H2 DB changed for the quickstarts (https://github.com/apiman/apiman/tree/master/distro/wildfly/src/main/resources/overlay/standalone/data/h2)

**Comment by tevosouza** [comment]
I'll submit a PR changing this behavior.
The source of '+' on origins is own KeyCloak on the client settings

![image](https://user-images.githubusercontent.com/58958299/103543141-cc928e00-4e7c-11eb-9fd4-e052d5f2c56a.png)
