### ISSUE TITLE
latest Apiman docker image doesn't allow logins

### ISSUE THREAD

**Issue by mark-kumoco** [apiman/apiman#957]
When running the latest official docker image (updated yesterday) on Ubuntu 20.04 (docker 20.10.2) I get an error when accessing the /apimanui login page:

"We are sorry...
Invalid parameter: redirect_uri"

However, if I run 2.0.0.Final on the same machine (killing previous container, of course) I am able to login fine.

Has anyone else experienced this?

Mark

**Comment by tevosouza** [comment]
Hi @mark-kumoco 
What url you are using to access apimanui 

if you using `http://localhost:8080/apimanui` try to access on `https://localhost:8443/apimanui` 
The error that you said appears a miss-configuration of apimanui client on keycloak.

**Comment by volkflo** [comment]
Mhh for me, the redirect is working but after the login, I got this:
![image](https://user-images.githubusercontent.com/13332383/106611763-a558da80-6568-11eb-9299-3e4f3969bd70.png)
@tevosouza Do you have any idea about this wildfly error?

**Comment by mark-kumoco** [comment]
Hi tevosouza,
Both 8080 and 8443 give the same error. I cleared my browser cache before trying again. btw I access apiman from a remote machine on a local network.
Mark

**Comment by tevosouza** [comment]
> Mhh for me, the redirect is working but after the login, I got this:
> ![image](https://user-images.githubusercontent.com/13332383/106611763-a558da80-6568-11eb-9299-3e4f3969bd70.png)
> @tevosouza Do you have any idea about this wildfly error?

I'll try to run it on docker

@mark-kumoco 
Can you show us the command that you used to initialize docker container?

**Comment by mark-kumoco** [comment]
$ docker run -td -p 8443:8443 -p 8080:8080 -p 9990:9990 apiman/on-wildfly

I've just tried on a Centos 7 machine (Docker version 19.03.11, build 42e35e61f3) and I get the same error as on Ubuntu:

"We are sorry...
Invalid parameter: redirect_uri"

**Comment by mark-kumoco** [comment]
eh, but interestingly, On the Centos 7 machine I tried:

docker run -td -p 8443:8443 -p 8080:8080 -p 9990:9990 apiman/on-wildfly:2.0.0.Final

And I get a login page, so I input the default username and password and get a "Forbidden" error. So for me, 2.0.0.Final works AOK on Ubuntu, but not on Centos 7.

**Comment by tevosouza** [comment]
I do the same command of @mark-kumoco and it worked for me
![image](https://user-images.githubusercontent.com/58958299/106613499-053f8900-6549-11eb-80f1-f9c100a1104c.png)

`$ docker run -td -p 8443:8443 -p 8080:8080 -p 9990:9990 apiman/on-wildfly`
(copy and paste command)

**Comment by mark-kumoco** [comment]
Ok, so you are accessing it locally, can you access over the network?

**Comment by mark-kumoco** [comment]
What OS is docker running on, in your instance?

**Comment by tevosouza** [comment]
Got it,
To access from network you need to add it as valid redirect on keycloak 
Go to http://localhost:8080/auth/ (from localhost of course) do the login with the same credentials

Select the client that you want to allow and include the URL on valid redirects it should solve your problem
![image](https://user-images.githubusercontent.com/58958299/106614122-bb0ad780-6549-11eb-9b7f-2ef29bf63b4a.png)

e.g. https://mypchostname:8443/apimanui/*

**Comment by tevosouza** [comment]
> What OS is docker running on, in your instance?

Debian Buster
```
        _,met$$$$$gg.          me@mypcname 
    ,g$$$$$$$$$$$$$$$P.       ----------------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 10 (buster) x86_64 
 ,$$P'              `$$$.     Host: Latitude 5410 
',$$P       ,ggs.     `$$b:   Kernel: 5.9.0-0.bpo.5-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 21 hours, 38 mins 
 $$P      d$'     ,    $$P    Packages: 2415 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: zsh 5.7.1 
 $$;      Y$b._   _,d$P'      Resolution: 1920x1080 
 Y$$.    `.`"Y$$$$P"'         DE: GNOME 3.30.2 
 `$$b      "-.__              WM: GNOME Shell 
  `Y$$                        WM Theme: whitesur-light 
   `Y$$.                      Theme: whitesur-light [GTK2/3] 
     `$$b.                    Icons: McMojave-circle-blue [GTK2/3] 
       `Y$$b.                 Terminal: tilix 
          `"Y$b._             CPU: Intel i7-10610U (8) @ 4.900GHz 
              `"""            GPU: Intel UHD Graphics 
                              Memory: 4392MiB / 15613MiB 
```

**Comment by mark-kumoco** [comment]
Yes that does work! Thanks.

**Comment by tevosouza** [comment]
@mark-kumoco

Very good to see it  ;)
If you do not have any other doubt please close this issue and I hope that you take good API management =P

**Comment by mark-kumoco** [comment]
It works on fine the Ubuntu machine, but not on the Centos machine. I still get the "Forbidden" error. @volkflo can you test the fix on your rig?

**Comment by tevosouza** [comment]
Maybe you all already know but CentOS support will be ceased in 2021 [CentOS Support](https://wiki.centos.org/About/Product) 
I don't think spending efforts to support update on this platform is a good idea considering the actual state of apiman development (maintenance mode)

**Comment by msavy** [comment]
Plenty of us are trying to kick back Apiman into full swing again. Don't
worry about that :-)!

**Comment by mark-kumoco** [comment]
Ah ok. Thanks for your help!!

**Comment by mark-kumoco** [comment]
Amazing support btw!!
