### ISSUE TITLE
Add caching of Maven artifacts to our GH Actions CI 

### ISSUE THREAD

**Issue by msavy** [apiman/apiman#977]
See:
  https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows

And: 
  https://github.com/actions/cache

Check the Java example

Basically, cache ~/.m2/repository to avoid downloading everything each time

**Comment by GOusignu** [comment]
Could I work on this?

**Comment by msavy** [comment]
CI sometimes fails because of our excessive numbers of requests to mvn central. Let's bump this up the list of priorities and do it imminently. I'll take it
