### ISSUE TITLE
Docker-compose quickstart distributions

### ISSUE THREAD

**Issue by msavy** [apiman/apiman#985]
As has been suggested by several folk, maintaining some simple docker-compose definitions could be today's version of a super-fast quickstart environment that is actually functional and representative.

That could enable us to start up a database with a more 'prod' type configuration than testcontainers, set up persistent volumes, etc.

Downside is that people would need docker to use that, but even Windows has docker these days, doesn't it?

For those [not familiar with docker-compose](https://docs.docker.com/compose/), it's a simple definition file that lets you start up and manage multiple docker containers together with associated stuff like volumes, mounting files, etc. 

So we could have something like `docker-compose -f apiman-es.compose.yml up` (or whatever) and that would start all Apiman components, appropriate databases with sensible config, plus inject configuration files/mounts, volumes, etc... 

Downsides would be that meddling with certain files would be harder, but we could potentially get around that by having them outside the docker image and using compose to mount them. And the usual Docker faff.

Discuss! Alternative thoughts welcome.

@apiman/api-developers

**Comment by volkflo** [comment]
I think this is the way to go these days. 
God and maintainable docker-compose files are easier to maintain and easier to use for the end user.
The advantage of docker-compose is also that you can switch very easily from "quickstart" to a "production " mode because the settings are mostly the same.

**Comment by msavy** [comment]
@BastianGem is going to (hopefully) spearhead the effort on this topic. 

I think it's a very high priority for the community and I am really keen to make this happen soon. I've scheduled it for 2.2 as there is almost certainly not enough time to get it into 2.1

**Comment by volkflo** [comment]
First tasks:

- [ ] Include Dockerfiles for tomcat and vert.x
- [ ] Provide Docker-Compose Quickstart for Keycloak, Manager, Gateway with Postgres DB
- [ ] Easy configuration with env file and file mounting documentation

Second tasks:

- [ ] Inlcude elasticsearch and kibana for metrics

**Comment by msavy** [comment]
See #1943

**Comment by msavy** [comment]
They are going to hold off a bit longer, so we can rely on adapter still.

**Comment by msavy** [comment]
This is going to be in the Docker repo
