### ISSUE TITLE
Having unique api gateway for each user

### ISSUE THREAD

**Issue by iamakashk** [apiman/apiman#993]
Hi 
I am working with apiman for multi tenant application where in I want to have unique gateway for each customer or user of my application. I have gone through the documentation but could not figure out how manage gateway section is helping us.
![image](https://user-images.githubusercontent.com/19202603/108940941-3576d500-767a-11eb-89a1-ca16daec8b50.png)

I want to have following format:
For customer 1(Puma) my apiman gateway would look something like this.
[(http://localhost:8080/puma-gateway/path/to/resource](http://localhost:8080/puma-gateway/path/to/resource)

For customer 2(Nike) my apiman gateway would look something like this.
[http://localhost:8080/nike-gateway/path/to/resource](http://localhost:8080/nike-gateway/path/to/resource)
Is is possible to have unique gateway for each customer/user ? If yes how do we configure them?

Please let me know. Thanks for the help in advance!:)

**Comment by volkflo** [comment]
Hi @iamakashk,
please have a look at this old issue: https://github.com/apiman/apiman/issues/711
Eric explained the gateway mechanism very well in the conversation. 

In short:
* You have to deploy multiple gateways (the easiest is the vert.x version)
* You have to configure a separate index/db-table for each gateway otherwise they will form a cluster

**Comment by volkflo** [comment]
@msavy I think you referenced the wrong issue here?

**Comment by msavy** [comment]
@iamakashk was @volkflo's answer sufficient for you? If so, can you close this issue.

If not, please feel free to expand :-).

**Comment by iamakashk** [comment]
> @iamakashk was @volkflo's answer sufficient for you? If so, can you close this issue.
> 
> If not, please feel free to expand :-).

Thats really helped. Thanks @volkflo @msavy . As always you guys are saviors!!!😊😎
